### ISSUE TITLE
How can I make the media player image rounded?

### ISSUE THREAD

**Issue by XMelph** [Aylur/dotfiles#1]
![Captura de tela de 2022-11-12 09-39-37](https://user-images.githubusercontent.com/113995667/201474334-f2a3864e-38d2-473c-8d27-d267faef21cb.png)
First, thank you very much for the great extension, I just have a small question about the image of the media player, could you force it to have rounded corners? If yes, could you tell me how to implement it in the extension?

**Comment by Aylur** [comment]
I have spent like a day trying to figure out a way to make it rounded the first time, but then gave up and went the easy way. The widget that displays the picture is St.Icon and there is no way to make it rounded. Then I tried making the image as a background to a widget and rounding it, but then it lead to loading and freezing issues.
I now actually know a bit about javascript so I will come back to this, but I have other goals to finish first

**Comment by XMelph** [comment]
No problem, I think I'll try something later on the extension. I'm currently working on a personal project (the theme you can see in the image). Hope you don't mind, I used Smooth and Ivory theme as a base for the shell. Again, thank you so much for the great extension! I really loved it.

**Comment by XMelph** [comment]
Oh, btw how can I make notifications appear below the quick-settings like they have in the quick-settings of GNOME 43?

**Comment by Aylur** [comment]
Check out the [extension's repo](https://github.com/Aylur/gnome-extensions). Now it is rounded.
