### ISSUE TITLE
gnome-control-center won't launch in the current configuration outside of GNOME Shell

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#101]
There is a widget button inside the Wi-Fi button, which is titled Network, and invokes the gnome-control-center. Installing it didn't work for me on Hyprland.

I found [here](https://unix.stackexchange.com/a/487148/573546) that you need to invoke it as `env XDG_CURRENT_DESKTOP=GNOME gnome-control-center`. Either way, I think invoking `network-manager-applet` is a better choice than the full fledged `gnome-control-center`.

Add this to the dependency list too.

**Comment by blacklightpy** [comment]
Oh ok, I forgot you used home-manager. Still, it will be confusing for users who don't use home manager..
I don't think adding the flag in the exec part will cause an issue. Anyways, that's addressed.

Also, what's wrong with `nm-applet`, but not with `gnome-control-center`?

**Comment by Aylur** [comment]
`nm-applet` is a systray item, while `gnome-control-center` is an application. I don't need a systray item for the network when I already have that information in the quicksettings menu
