### ISSUE TITLE
Notification in Notification Panel Reaveler is Buggy

### ISSUE THREAD

**Issue by ldelossa** [Aylur/dotfiles#102]
Hey there,

As you probably know I've been chewing through your dotfiles and AGS for my Sway setup. 

I noticed that the reveal animation for a notification's action is rather buggy. Not sure why this occurs. Any idea?

https://github.com/Aylur/dotfiles/assets/5642902/aa2be40e-35b9-4e01-9067-c638768f57a1

**Comment by Aylur** [comment]
I just pushed an update to ags addressing this https://github.com/Aylur/ags/commit/0c23615921a42306f9d12f0d81a76ed9cff9a49a

**Comment by ldelossa** [comment]
Yup, fixed. I was in 1.5.4
