### ISSUE TITLE
floating dock position

### ISSUE THREAD

**Issue by killown** [Aylur/dotfiles#103]
how can I set the dock for the left? actually I try anchor["left"] but it will keep the horizontal position

**Comment by Aylur** [comment]
You need to make its content vertical, and probably the revealer animation slide right

**Comment by nine7nine** [comment]
IIRC (I use Left-side Dock in AGS), aside from changing the revealer animation and anywhere that said 'bottom' to 'left' in FloatingDock.js - i also had to add:

```
        child: Widget.Box({
+           vertical: true,
```

Then to get the dock to appear vertically, I had to add/edit Dock.js. Specifically, I had to add:

```
vertical: 'false',
```

to both const Taskbar and PinnedApps... Without adding the above, the dock still appeared horizontally. ~ which seems counterintuitive, i guess.

I may have also played with some alignment stuff, as well.
