### ISSUE TITLE
Notification issues after latest changes

### ISSUE THREAD

**Issue by Balssh** [Aylur/dotfiles#105]
Hi, updated my conf to match your latest commits and it seems there's an error with Notifications isHovered():
![image](https://github.com/Aylur/dotfiles/assets/82440615/ded462e1-2d00-44c1-8b5d-645bae46c0df)
is this a genuine issue or am I missing some dependencies?

**Comment by Aylur** [comment]
Update ags too

**Comment by Balssh** [comment]
Ah yes, switched to the ags git package from AUR and now it works. Thanks!
