### ISSUE TITLE
bluetooth connection hangs everything

### ISSUE THREAD

**Issue by killown** [Aylur/dotfiles#107]
the entire ags hangs with any bluetooth connection

== Stack trace for context 0x563078c80590 ==
#0   7fff595f64c0 b   resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59 (610f93b44c0 @ 157)
Aylur/ags#1   7fff595f6500 I   resource:///com/github/Aylur/ags/widgets/widget.js:32 (610f93c5e20 @ 24)
Aylur/ags#2   7fff595f6d90 I   resource:///com/github/Aylur/ags/widgets/widget.js:11 (610f93c9ce0 @ 27)
Aylur/ags#3   7fff595f6d90 I   resource:///com/github/Aylur/ags/widget.js:74 (610f93c5bf0 @ 22)
Aylur/ags#4   7fff595f6d90 I   resource:///com/github/Aylur/ags/widget.js:77 (610f93c5c40 @ 18)
Aylur/ags#5   7fff595f6d90 I   file:///home/neo/.config/ags/js/quicksettings/widgets/Bluetooth.js:52 (30a646b513d0 @ 304)
Aylur/ags#6   7fff595f6e20 I   self-hosted:221 (610f9370970 @ 267)
Aylur/ags#7   7fff595f6e20 I   file:///home/neo/.config/ags/js/quicksettings/widgets/Bluetooth.js:46 (30a646b51330 @ 40)
Aylur/ags#8   7fff595f6ea0 I   resource:///com/github/Aylur/ags/widgets/widget.js:105 (610f93c9420 @ 110)
Aylur/ags#9   7fff595f7b00 I   resource:///com/github/Aylur/ags/service/bluetooth.js:121 (610f93fa8d0 @ 17)
Aylur/ags#10   7fff595f8750 I   resource:///com/github/Aylur/ags/service.js:61 (610f93b2bf0 @ 40)
Aylur/ags#11   7fff595f8750 I   resource:///com/github/Aylur/ags/service/bluetooth.js:71 (610f93fa560 @ 29)
Aylur/ags#12   7fff595f8750 I   resource:///com/github/Aylur/ags/service/bluetooth.js:144 (610f93faa10 @ 38)
Aylur/ags#13   563078d6c438 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (610f937c420 @ 139)

(com.github.Aylur.ags:147877): Gjs-CRITICAL **: 09:53:38.883: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was notify on Gjs_Bluetooth 0x5630795594d0.
== Stack trace for context 0x563078c80590 ==
#0   7fff595f8750 I   resource:///com/github/Aylur/ags/service.js:60 (610f93b2bf0 @ 20)
Aylur/ags#1   7fff595f8750 I   resource:///com/github/Aylur/ags/service/bluetooth.js:145 (610f93faa10 @ 59)
Aylur/ags#2   563078d6c438 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (610f937c420 @ 139)

**Comment by Aylur** [comment]
>because this was fixed sometime ago already

in https://github.com/Aylur/dotfiles/commit/a2f989bbad725710675426db792f75134021d0f1
