### ISSUE TITLE
AGS starts normally but nothing happens when using dotfiles

### ISSUE THREAD

**Issue by ScorpThePotato** [Aylur/dotfiles#109]
Firstly I'd like to thank you for making this tool since it's the only one that is customizable and fast enough for me.

I followed the README instructions but I can't get ags to load. It does run the config since the first time it spit out a version mismatch error and I had to update my ags package for it to work. Now it starts up and nothing happens even if left alone for several minutes. It also doesn't reserve screen space at the top if that is significant. If I replace your dotfiles with a simple config from the ags wiki it does work as expected.

I've tried using the --inspector tag but nothing changed and the inspector never launched after 10 minutes. 
I have already tried reinstalling both ags and the config files.

Command output:
```
❯ ags

(com.github.Aylur.ags:20835): Gjs-Console-CRITICAL **: 13:53:14.047: Error: Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found
@resource:///com/github/Aylur/ags/service/bluetooth.js:4:28
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
``` 

I have tried installing the gnome-bluetooth package from the official repo but it did not help with the error or the issue.

System Info:
OS: Arch Linux (up to date)
Packages: hyprland-git ,aylurs-gtk-shell-git and required dependencies listed in README

**Comment by Aylur** [comment]
You need to install `gnome-bluetooth-3.0`. The package you installed is v1.0
GnomeBluetooth is an optional dependency and the AUR package doesn't install it for you
