### ISSUE TITLE
Notifications Timeout

### ISSUE THREAD

**Issue by SychoAN** [Aylur/dotfiles#110]
after making screen record with this code
ags -b hypr -r 'recorder.screenshot(true)'

it shows a notification but it disappears so fast 
I want to increase the timeout so I can click on it instead of opening the notification panel (:
can you help ?

**Comment by Aylur** [comment]
https://github.com/Aylur/ags/wiki/configuration#config-object
You can play with these options

But it sounds more like the issue that was fixed a while ago

```bash
cat ~/.config/ags/package.json | jq .version
ags --version
```
what versions?

**Comment by SychoAN** [comment]
both are version "1.5.4"
thx, I'll try this options
