### ISSUE TITLE
The bar stops responding while using spotifyd 

### ISSUE THREAD

**Issue by mateodd25** [Aylur/dotfiles#111]
First, I want to thank you for your fantastic work. It is absolutely amazing.

Now the real issue: I often use spotify via this daemon https://github.com/Spotifyd/spotifyd. I noticed that if I reproduce music through spotifyd the bar completely breaks; it is not responsive at all. If I kill the spotifyd process everything goes back to normal. I tried running ags on the console to see if I could spot an error, but it registers nothing.

**Comment by c-danil0o** [comment]
I have the exact same issue with the thorium browser playing media. The bar freezes and there is nothing shown in the logs. After stopping the browser and resetting ags everything goes back to normal.

**Comment by SolAstri** [comment]
+1
