### ISSUE TITLE
scaling issues

### ISSUE THREAD

**Issue by TwelveNight** [Aylur/dotfiles#114]
my os
![image](https://github.com/Aylur/dotfiles/assets/113519679/d170bd18-7959-4420-9293-fce66a0f8dd6)
the widgets have some scaling issues in my case
![image](https://github.com/Aylur/dotfiles/assets/113519679/7e142e56-faa5-4fdc-b339-fbb109d32bc9)
![image](https://github.com/Aylur/dotfiles/assets/113519679/d857370b-cbdd-4e38-9240-e2aa5ec304d7)

**Comment by Aylur** [comment]
try using non mono spaced font

**Comment by TwelveNight** [comment]
I'm sorry, but is this what you mean? 
![image](https://github.com/Aylur/dotfiles/assets/113519679/de4fe70b-96d2-48b3-8315-0887d9ececf7)
It seems not effective
How to set it up permanently?

**Comment by TwelveNight** [comment]
I have another problem that where are this titles from
![image](https://github.com/Aylur/dotfiles/assets/113519679/c4a0a722-3b75-46a6-a927-a981b8dfc13c)
I want to add my own pinned_apps

**Comment by Aylur** [comment]
>I'm sorry, but is this what you mean?

no, the one above `font.font`
FiraCode is a monospaced font, its not a great choice for GUI

**Comment by Aylur** [comment]
> where are this titles from

get a list by running
```bash
ags -r "(await import('./service/applications.js')).default.list.map(app => app.desktop)" | tr ',' '\n'
```

**Comment by daUnknownCoder** [comment]
> get a list by running

```bash
ags -r "(await import('./service/applications.js')).default.list.map(app => app.desktop)" | tr ',' '\n'

(com.github.Aylur.ags:25981): Gjs-WARNING **: 16:39:22.534: JS ERROR: Exception in method call: RunJs: SyntaxError: missing ) in parenthetical @ resource:///com/github/Aylur/ags/app.js:3:14

(com.github.Aylur.ags:27177): Gjs-CRITICAL **: 16:39:22.536: JS ERROR: Gio.IOErrorEnum: GDBus.Error:org.gnome.gjs.JSError.SyntaxError: missing ) in parenthetical
_proxyInvoker@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:122:46
_makeProxyMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:147:30
default@resource:///com/github/Aylur/ags/client.js:48:21
main@resource:///com/github/Aylur/ags/main.js:111:16
@file:///usr/bin/ags:36:31


(com.github.Aylur.ags:27177): Gjs-CRITICAL **: 16:39:22.537: Module file:///usr/bin/ags threw an exception
```

i m getting this

**Comment by daUnknownCoder** [comment]
> It seems not effective

go to ~/.config/ags/js/icons.js, search for mpris, they are simple icons which you can manipulate the spacing for the same, like what works for me is:
```js
    mpris: {
        fallback: 'audio-x-generic-symbolic',
        shuffle: {
            enabled: ' 󰒟',
            disabled: ' 󰒟',
        },
        loop: {
            none: ' 󰓦',
            track: ' 󰓦',
            playlist: ' 󰑐',
        },
        playing: ' 󰏦',
        paused: ' 󰐍',
        stopped: ' 󰐍',
        prev: ' 󰒮',
        next: ' 󰒭',
    },
```

![image](https://github.com/Aylur/dotfiles/assets/84800625/15c0b2ba-e7a6-4b21-97ab-08dd507ab6d5)

mine's this
