### ISSUE TITLE
temperture issuse

### ISSUE THREAD

**Issue by TwelveNight** [Aylur/dotfiles#115]
Hey,I`m back again,I like this dotfiles,but I encounter many problems I can not solve alone
![image](https://github.com/Aylur/dotfiles/assets/113519679/577bc981-6a1a-4fd3-acad-e8132aa36b24)
It can not detect my cpu temperture,what backend should be used to detect it？

**Comment by Aylur** [comment]
Have you tried setting the system file path in options.js?

**Comment by TwelveNight** [comment]
Did you say this? I didn't change it
![image](https://github.com/Aylur/dotfiles/assets/113519679/3a5d3111-d9c8-48d1-8e47-6dd3caafd842)

**Comment by Aylur** [comment]
Yes, change it to where you want to read your temperature
