### ISSUE TITLE
system tray issue

### ISSUE THREAD

**Issue by TwelveNight** [Aylur/dotfiles#116]
Left-click and right-click the tray icon behave the same,but some app should behave not the same like obs...
Is this a problem with ags itself?

**Comment by Aylur** [comment]
It's not, it's just how I set it up. If you want you can edit it in SysTray.js

**Comment by TwelveNight** [comment]
> It's not, it's just how I set(设置) it up. If you want you can edit it in SysTray.js

`on_primary_click: (_, event) => item.activate(event),` I fix with this
