### ISSUE TITLE
my config expects v1.5.5, but your ags is v1.5.4

### ISSUE THREAD

**Issue by houssemko** [Aylur/dotfiles#118]
I'm getting this message after following the guide .

**Comment by Balssh** [comment]
You need to use the latest AGS for this to work. For me it meant using the aylur-gtk-shell-git from AUR.

**Comment by ahmadjerjawi** [comment]
And if you don't want to just edit the config file for package and probably work the same except some problems but better to update

**Comment by houssemko** [comment]
i'm stuck on this error now
` ags                                                                                          ░▒▓ ✔   5s ▓▒░

(com.github.Aylur.ags:114085): Gjs-Console-CRITICAL **: 15:12:51.324: Hyprland is not running

(com.github.Aylur.ags:114085): Gjs-Console-CRITICAL **: 15:12:51.325: Gio.IOErrorEnum: Could not connect: No such file or directory
socket@resource:///com/github/Aylur/ags/service/hyprland.js:7:6
Hyprland@resource:///com/github/Aylur/ags/service/hyprland.js:109:26
@resource:///com/github/Aylur/ags/service/hyprland.js:281:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 `

**Comment by Aylur** [comment]
well, is Hyprland running?

**Comment by houssemko** [comment]
no i'm on gnome but i have hyprland installed

**Comment by Aylur** [comment]
This project doesn't work on Gnome, this works on top of a wayland compositor called Hyprland.
I'll just link you this other issue instead of explaining it again https://github.com/Aylur/dotfiles/issues/79
