### ISSUE TITLE
How can I add a name to the  mpris`s black_list

### ISSUE THREAD

**Issue by TwelveNight** [Aylur/dotfiles#119]
![image](https://github.com/Aylur/dotfiles/assets/113519679/84cae3ff-cff7-4624-a54c-47d8420c59b5)
![image](https://github.com/Aylur/dotfiles/assets/113519679/2e4c5707-440d-472b-84cd-b5be62950d2f)
![image](https://github.com/Aylur/dotfiles/assets/113519679/b8063c82-7dd1-4ec8-870d-28760038bda5)
I tried the four class/title,but nothing happen
I also tried `ags -r "(await import('./service/applications.js')).default.list.map(app => app.desktop)" | tr ',' '\n'`

**Comment by Aylur** [comment]
It doesn't check for application, it checks for an mpris player. The player attributes mentioned in the note to be exact
`ags -r "(await import('./service/mpris.js')).default.players.map(player => player.name)"`
chromium browsers usally have the name `chromium`
