### ISSUE TITLE
Fonts / Glyphs?

### ISSUE THREAD

**Issue by hazzardr** [Aylur/dotfiles#12]
Hey! Love the rice, just learning Eww myself. 

When I launch Hyprland using this setup, I get a bunch of unrecognized fonts / glyphs (granted this is a fresh install for me).

Do you list out which fonts / glyphs etc you need for your bars? Thanks!

**Comment by Aylur** [comment]
I am using [Ubuntu Nerd Font](https://www.nerdfonts.com/font-downloads) but you can set it to some other Nerd Font one aswell in .config/eww/scss/variables.scss
