### ISSUE TITLE
Weird artifacts when clicking the desktop

### ISSUE THREAD

**Issue by Balssh** [Aylur/dotfiles#121]
I noticed some errors while running AGS in the terminal, config being almost the same as in @Aylur dots. I am curious about debugging them but I'm a bit lost about where to begin. The error in question is:

```
(com.github.Aylur.ags:146402): Gjs-CRITICAL **: 22:47:07.734: Attempting to call back into JSAPI 
during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ 
widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), 
or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on AgsBox 0x556ca1657380.
== Stack trace for context 0x556ca08989a0 ==
#0   556ca095b418 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (2f145d97c420 @ 139)
```

**Comment by Aylur** [comment]
I moved this issue, because the error log is not ags releated, it is from my config. Its from the `NotificationList` widget in `NotificationColumn.js`
You can ignore it, I am not sure about the cause, but I will fix it sometime

**Comment by Balssh** [comment]
Oh good to know. Thanks for the fast reply and for your work!
