### ISSUE TITLE
temperature-symbolic missing

### ISSUE THREAD

**Issue by alex071299** [Aylur/dotfiles#123]
Hi a few updates ago I realized the temperature-symbolic isn't working anymore.
![2023-12-19_12-41-24](https://github.com/Aylur/dotfiles/assets/34168076/56a508ce-3c66-4b31-9c17-969b5d8af746)
I'm using your original config except edited my username and git mail address.
When running ags i get this message: Error: can't assign "temperature-symbolic" as icon, it is not a file nor a named icon.
When searching for this icon i get a result in Qogir/symbolic/status/temperature-symbolic.svg but not in 24 folders as the other icons.
![2023-12-19_12-44-23](https://github.com/Aylur/dotfiles/assets/34168076/7156f525-d39d-4848-b35e-fdfa705d459c)

**Comment by Aylur** [comment]
It comes with the `gnome-system-monitor` package on NixOS which I have installed in `nixos/hyprland.nix`

**Comment by alex071299** [comment]
Oh ok. But this package is also installed in my hyprland.nix.

**Comment by alex071299** [comment]
I rebuilded from scratch now its working. I cant see any different. Sorry for bothering :)

**Comment by alex071299** [comment]
The problem came back after removing gnome-wearther. Seems like the icon came from this package. After reinstalling the icon came back.
