### ISSUE TITLE
keybind for don't disturb mode

### ISSUE THREAD

**Issue by SychoAN** [Aylur/dotfiles#125]
bind= ,Print, exec, ags -b hypr -r 'recorder.screenshot()'

is there's something like this in your config but for notifications ?
I want a bind to toggle don't disturb mode

-also I wonder why you don't add your config as the default config for ags
It would be easier to update the app with your new changes on the configs

thanks for your hard work❤️

**Comment by Aylur** [comment]
you can toggle dnd using cli like this
```bash
ags -r "
  const n = (await import('./service/notifications.js')).default;
  n.dnd = !n.dnd;
"
```

or you could make a global function in your config
```js
import Notifications from 'resource://com/github/Aylur/ags/service/notifications.js';

globalThis.toggleDND = function() {
  Notifications.dnd = !Notifications.dnd;
}
```
```bash
ags -r "toggleDND()"
```

>also I wonder why you don't add your config as the default config for ags

Because it is my personal setup, tailored for me and not for general use, its only linked on the ags wiki as an example
There will never be a default config, because its not the goal of the project
