### ISSUE TITLE
Error eww::widgets main_monitor not found

### ISSUE THREAD

**Issue by MalpenZibo** [Aylur/dotfiles#13]
If I click on buttons that trigger the `launcher` script I'll get the following error on `eww logs` and nothing happens.

```
ERROR eww::widgets > WARNING: command ~/.config/eww/scripts/launcher toggle_menu powermenu timed out
Variable not found "main_monitor"
```

**Comment by Aylur** [comment]
Edit the the script like this
```bash
# MAIN=$(eww get main_monitor)
MAIN=""
```
It is a leftover from my previous multimonitor setup
