### ISSUE TITLE
External monitor brightnessctl support requires ddcci-driver-linux driver

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#132]
This could be added to the guide.

**Comment by blacklightpy** [comment]
The DDC/CI driver (`ddcci-linux`) is meant to be installed with DKMS. However the master branch only supports upto kernel 6.4 as of now.

As an alternative, `i2c_dev` module can be loaded to enable an interface to the monitor, through which the tool `ddcutil` can communicate to the DDC/CI address.

Anyways hope this helps someone. My monitor had terrible display at other brightness values, so it didn't help me 🙁

**Comment by vicentelyrio** [comment]
I have success using https://aur.archlinux.org/packages/ddcci-driver-linux-dkms-git with 6.9 kernel
