### ISSUE TITLE
ags crashes when scrolling continuously over the volume widget

### ISSUE THREAD

**Issue by NoamLeshem** [Aylur/dotfiles#134]
This might be a niche issue because it is less likely to happen with regular mice, but with mice that support so-called 'infinite scrolling' such as Logitech MX series and the Logitech gaming G series it will happen.

https://github.com/Aylur/dotfiles/assets/47627214/5e53d78c-2ecb-4548-b086-c4569e46c6f6

Basically the animation keeps on getting more intense until it goes out of the screen and crashes.

it crashes for both scrolling down and for scrolling up.

it crashes with the following error:
```
(com.github.Aylur.ags:7332): Gdk-CRITICAL **: 20:10:41.919: ../gtk/gdk/wayland/gdkdisplay-wayland.c:1428: Unable to create Cairo image surface: invalid value (typically too big) for the size of the input (surface, pattern, etc.)
```

**Comment by quadbyte** [comment]
Having the same crash if I use my volume knob to fluctuate quickly between min and max.

It seems the smoothing/interpolation code in Progress.js triggers an ags crash by requesting an invalid css height.

I believe we should cancel previous "timeout" calls if the value changes again, but did not find a way to do it.

I came up with a dirty fix for now by clamping the fill_size to a valid range.

![image](https://github.com/Aylur/dotfiles/assets/2170677/0060fbe1-d5df-4d3f-90fd-640f3aef2a86)

**Comment by Aylur** [comment]
should be fixed now after the ts migration
the previous animations are now cancelled, should smooth it out
