### ISSUE TITLE
icons in the overview doesn't show up 

### ISSUE THREAD

**Issue by meduk0** [Aylur/dotfiles#135]
btw i use your work in arch i might give you an innstall script if you want .
so in my dock i can see all the icons of the apps i choose but when using the overview i cant see except kitty or the gnome files any help also can you help me set gnome powerdemon instead of asusctl and how to set one for envycontrol(yeah had some exams so i cant do some js learning ) i will appreciate that 
happy new year

**Comment by Aylur** [comment]
>btw i use your work in arch i might give you an innstall script if you want .

thanks, but I don't use Arch, I don't need it.

>so in my dock i can see all the icons of the apps i choose but when using the overview i cant see except kitty or the gnome files 

see #59 

>also can you help me set gnome powerdemon instead of asusctl and how to set one for envycontrol

If you have an exact question, I'm happy to help, but you will have to figure it out yourself
