### ISSUE TITLE
Icons broken/missing

### ISSUE THREAD

**Issue by jonkke8** [Aylur/dotfiles#136]
Icons seem to be missing from the bar (this is the far right part of the bar)
![right side of bar](https://github.com/Aylur/dotfiles/assets/45978346/6820bf04-a8b3-4bf2-a63d-a2f5d037d09d)

**Comment by Aylur** [comment]
Seems like you don't have an icon theme set

**Comment by jonkke8** [comment]
That does make sense... may I ask what icon theme are you using?

**Comment by Aylur** [comment]
I use [MoreWaita](https://github.com/somepaulo/MoreWaita) which is basically the default Gnome icons with a few additions

**Comment by nxy7** [comment]
Sorry to bother you @Aylur with similar question, but is that the only icon pack you use? I have issues with icons in my system tray
![20240125_00h56m41s_grim](https://github.com/Aylur/dotfiles/assets/32909532/1698d0b1-3c34-4f9a-a846-b89911d4ed96)
and I think adding MoreWaita to my config solved issues with some icons, but it seems like there's still more missing.

**Comment by Aylur** [comment]
MoreWaita depends on Adwaita, I guess you don't have that installed
