### ISSUE TITLE
Top Bar: Set specific Icon Theme For certain Parts

### ISSUE THREAD

**Issue by shard77** [Aylur/dotfiles#138]
Hello, I changed the icon theme from your nix dotfiles:

```nix
gtk = {
    enable = true;
    font.name = "Ubuntu Nerd Font";
    theme.name = gtk-theme;
    cursorTheme = {
      name = cursor-theme;
      package = cursor-package;
    };
    iconTheme.name = "Reversal-dark";
    gtk3.extraCss = ''
      headerbar, .titlebar,
      .csd:not(.popup):not(tooltip):not(messagedialog) decoration{
        border-radius: 0;
      }
    '';
  };
```

This works fine for the dock, but for some reason, I see the correct theme icon appear for a second on the `FocusedClient` widget, but then it disappears. I tried to debug but I did not understand why this happens, if you have any idea, it would help me a lot.

Also, I'd like to use `MoreWaita` for the right part of the bar, is it possible to set two different icon themes through the config or ags?

Thank you in advance, sorry if this may not be the right place to ask ^^' .

**Comment by Aylur** [comment]
> I see the correct theme icon appear for a second on the FocusedClient widget, but then it disappears

weird, setting another icon theme should just work

you can specify a theme on widgets in css with `-gtk-icon-theme` see https://docs.gtk.org/gtk3/css-properties.html

```js
.panel .end image {
    -gtk-icon-theme: "MoreWaita";
}
```

**Comment by shard77** [comment]
alright, thank you very much.
Yeah.. it's weird, I still have the problem, the icons just disappear forever somehow :/ and that happens also if I use whitesur. I also made sure to manually specify output folder for the font like you did for MoreWaita, but still same problem. I do get them for the dock.
