### ISSUE TITLE
Widgets not initiating on start

### ISSUE THREAD

**Issue by BSIT-Evanism** [Aylur/dotfiles#14]
I installed all the dependencies and apps needed for the setup but everytime I start hyprland, the eww widgets doesn't start or show up and need manual initiation to make it show up such as `bash ~/.config/eww/scripts/init`

All the functionality works on the widgets such as volume, brightness etc. The app launcher also bugs without the cat wallpaper and the volume widget on the right side not showing up

Distro used: Fedora 38 workstation edition
Hyprland: copr repo for fedora 38

**Comment by thyeun** [comment]
@BSIT-Evanism can assist me on my issue regarding the wallpaper, the app-launcher and the player

My app-launcher appear empty 
![Screenshot_2023-05-09-23-06-57_10619](https://github.com/Aylur/dotfiles/assets/1939446/ed56b819-19e2-4fd4-ac71-4d20231dd665)

Player not appear
![Screenshot_2023-05-09-22-59-39_32400](https://github.com/Aylur/dotfiles/assets/1939446/1d8df503-1210-49da-87af-d4045df3b31c)

No wallpaper and no avatar
![Screenshot_2023-05-09-23-09-28_29812](https://github.com/Aylur/dotfiles/assets/1939446/746b8d6b-613c-4530-847f-6cfbb51299c2)

but i can launch it everytime i logon, you can try to put the ```init``` into your ```hyprland.conf``` with the below line
```exec-once = ~/.config/eww/scripts/init```
