### ISSUE TITLE
Ags version

### ISSUE THREAD

**Issue by LightDev1** [Aylur/dotfiles#141]
Hi! Maybe my question is stupid but how you use ags 1.6.4 in your config? I can only 1.6.3 or 1.7.0 in archlinux

**Comment by Aylur** [comment]
1.6.3 was tagged as a release, 1.6.4 wasn't and the current git version is 1.7.0
I just haven't updated this repo yet

**Comment by LightDev1** [comment]
Am i able to workaround myself or better to wait while you update this repo?

**Comment by Aylur** [comment]
you can just remove the version check in `config.js` it should still work

**Comment by LightDev1** [comment]
thanks!!
