### ISSUE TITLE
Wrong Login

### ISSUE THREAD

**Issue by AngryOwlAdv** [Aylur/dotfiles#142]
Everytime i install this flake on a minimal nixos install the user/password no longer works.

This is the command i use
`sudo nixos-rebuild boot --flake github:Aylur/dotfiles --impure `

**Comment by Aylur** [comment]
probably because of how users are hardcoded in `configuration.nix`
I would really advise against doing this anyway
just clone the repo edit whatever file you want and build that
also if you are looking for my ags setup, its managed with home-manager and not through NixOS and I don't use the home-manager nixos module

**Comment by AngryOwlAdv** [comment]
> probably because of how users are hardcoded in `configuration.nix` I would really advise against doing this anyway just clone the repo edit whatever file you want and build that also if you are looking for my ags setup, its managed with home-manager and not through NixOS and I don't use the home-manager nixos module

Are u using fedora with nix?

**Comment by Aylur** [comment]
Used to use Fedora+home-manager, but I'm on NixOS now

**Comment by AngryOwlAdv** [comment]
I swear my brain is not able to comprehend how to install this config

**Comment by AngryOwlAdv** [comment]
This is what i do
1. I clone the git
2. I change the username in flake.nix using sed -i
3. I run nixos-rebuild boot . —impure

My login credentials no longer work after rebooting

**Comment by Aylur** [comment]
but why are you trying to `nixos-rebuild`? My NixOS config is pretty much just hardware and locale specifications

**Comment by AngryOwlAdv** [comment]
Fixed it, im retarded

**Comment by akshitgaur2005** [comment]
Wait! I am retarted too! How did you fix it?
