### ISSUE TITLE
When pressing record, screenshot or application launcher shortcut, a second bar is created

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#143]
AGS refresh is CTRL+SHIFT+R.
Recorder is SUPER+SHIFT+R
Screenshot is SUPER+SHIFT+P and SUPER+ALT+P.
App Launcher is SUPER+R.

I'm on Hyprland.

I believe this happens due to something with `execAsync()`? This has happened to me some times before. I don't remember under what circumstances this occurs.

I refresh AGS and it goes away, but it again returns when I press these shortcuts.

SUPER+P, SUPER+J, SUPER+Q, SUPER+V, SUPER+F, etc. don't have this problem.

Further pressing the keys carry out the function of the key, they don't create new bars. But the first press will not screenshot or start recording, it will simply add a new bar.

**Comment by Aylur** [comment]
sounds like a `--bus-name` flag issue
I see now that I left a `-b hypr` flag in the readme which I use
but the other bindings don't 

so you are probably launching it with `ags -b hypr`
but the other keybindings don't specify a bus so it launches a new process

**Comment by blacklightpy** [comment]
Ahh makes sense. Because my original launch was just `exec_once ags & blablabla`, but when I reloaded it with Ctrl+Shift+R, it's now based on the `ags -b hypr` keybinding.

So how do I fix it?

**Comment by blacklightpy** [comment]
Also what could be the uses of a bus here?

**Comment by Aylur** [comment]
I use `-b hypr` for my setup only so that I don't have to specify `-b test` for example, when I am developing it

**Comment by daUnknownCoder** [comment]
dumb question but how do u refresh ags, can u provide the hyprland config?

**Comment by Aylur** [comment]
https://github.com/Aylur/dotfiles/blob/a1f4795aae6aeff3eb3c332c39ca7094f812b88e/home-manager/hyprland.nix#L119
```
bind = CTRL SHIFT, R,  exec, ags -b hypr quit; ags -b hypr
```

**Comment by blacklightpy** [comment]
* `bind = CTRL SHIFT, R,  exec, ags quit; ags` 😁
@daUnknownCoder
