### ISSUE TITLE
Use Hyprland active/inactive window borders

### ISSUE THREAD

**Issue by kaibagley** [Aylur/dotfiles#144]
Hey, thanks for the beautiful dotfiles!

I've been using Linux for a while, but only recently got into customizing things so I'm very new to Hyprland and AGS. 
I'd like to use the Hyprland window borders instead of the borders in these dotfiles, but I'm unsure of how to do that. At the moment, I'm just running `hyprctl reload` after running `ags` which works, but leads to bigger gaps between the top bar and the windows.

![image](https://github.com/Aylur/dotfiles/assets/53884957/f44f133b-cd2c-4ace-bea3-ebfd164db8dd)

Without running `hyprctl reload`, I have the AGS defined window borders which I don't prefer, but I also have the windows on my second monitor touching the screen edge, with no gaps like there is on the other sides, since I changed the TopBar to only be on monitor 0.

![image](https://github.com/Aylur/dotfiles/assets/53884957/6efd7322-93e1-422b-9d2d-6722c5f43956)

So what I want is either:
1. After `hyprctl reload`, decrease the size of the larger gap between the TopBar and the windows on the monitor with the TopBar. So the gap between the TopBar and Firefox in the top image is the size of the gaps everywhere else.
2. Use Hyprland window borders rather than AGS, and somehow add a gap on top of the second monitor that doesn't have the TopBar

But my brain is currently not large enough to know how to do one myself...
Thanks for any help!

**Comment by Aylur** [comment]
the code you are looking for is in `js/setup/hyprland.js`
edit the `setupHyprland` function to fit your needs
