### ISSUE TITLE
The settings button isn't working some "`AgsBase_Gtk_Window` is already registered" issue

### ISSUE THREAD

**Issue by daUnknownCoder** [Aylur/dotfiles#148]
i get this:
![2024-01-27-221746_hyprshot](https://github.com/Aylur/dotfiles/assets/84800625/15a79d59-5884-44ab-a86f-9c98ec06a6fb)
```js
(com.github.Aylur.ags:165428): Gjs-Console-CRITICAL **: 22:17:44.140: Type name AgsBase_Gtk_Window is already registered
```
![2024-01-27-221656_hyprshot](https://github.com/Aylur/dotfiles/assets/84800625/498d2883-d8fe-43f7-8741-3fdd5b7e2ebb)

idk why this happened when i switched to `1.6.3` and ags doesnt even start in the latest git version `1.7.3`

and this is something more i get:
```js
(com.github.Aylur.ags:165428): Gjs-CRITICAL **: 22:20:40.165: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_AgsLabel 0x55a1226b1fa0.
== Stack trace for context 0x55a120e43950 ==
#0   55a120f05c18 i   resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (3ae82c47c420 @ 139)
```

**Comment by Aylur** [comment]
seems like you have an outdated version of my dotfiles, there were a few breaking changes since then
either update the config, or rollback ags

**Comment by daUnknownCoder** [comment]
i m using `1.5.3` but i dont know what to update coz i have done many edits and a lot of reformatting and styling and more widgets and all so which file or folder may i have to update?

**Comment by Aylur** [comment]
I refactored a lot of things since then, so I don't know, checkout the commits maybe you can figure it out.
