### ISSUE TITLE
max_width_chars does not truncate characters to given value

### ISSUE THREAD

**Issue by daricoder** [Aylur/dotfiles#149]
```
//style.css
.playerctl {
  letter-spacing: 4px;
}

//config.js
const playerctl_label = Widget.Label({
  class_name: "playerctl",
  label: "test test",
  max_width_chars: 5,
  truncate: "end",
  wrap: false,
});

```
result with letter-spacing: te...
result without letter-spacing:test...

in eww truncates correctly with or without letter-spacing

**Comment by Aylur** [comment]
Eww doesn't use Gtk for this, they slice the string in rust code.
This is the expected behavior with Gtk. If you want exact number of letters, you can manipulate the string as needed

**Comment by daricoder** [comment]
hi @Aylur , today I took the time to review this. 
truncate aka "ellipsize" does not work correctly for css letter-spacing. Adding max-width-chars to a very high value (e.g. 500) and the "test" tag (length:4) results in adding the ellipsise string to the end. This doesn't happen if I remove the letter-spacing. I know this is a gtk problem already mentioned by eww at the time. However, they have solved it either with rust. 

> they slice the string in rust code.

> If you want exact number of letters, you can manipulate the string as needed

It is useless to slice the string to something smaller with js (with letter-spacing) if the string "ellipsize" will always be added to the end, whether or not it exceeds the max_with_chars.

Letter-spacing causes many problems for labels in gtk3+, like the issue I created a week ago, which you told me you didn't know because at the beginning line-break was added and when the label was changed the spacing was recalculated and it worked. However, this has also been solved in eww with rust below.

In any case, I think you should open this issue until you can solve it.
```
// ags.config
const label = Widget.Label({
  label: "test",
  class_name: "test",
  max_width_chars: 500, // with or without it doesn't matter
  truncate: "end", // the problem
});

// style.css
.test{
letter-spacing:5px
}

/*
result: with letter-spacing and max-width-chars 500
tes...

without letter-spacing and max-width-chars 500
test
*/
```
