### ISSUE TITLE
Cant change app icon (fedora icon)

### ISSUE THREAD

**Issue by Azkaas** [Aylur/dotfiles#15]
Is there a way to change the fedora icon? As the title say, i cant seem to find that icon.

First time im using eww bar so im a little lost :/

**Comment by thyeun** [comment]
@Azkaas you can change the icon from the file ```bar_widgets.yuck```

**Comment by Azkaas** [comment]
Found it :) Thanks a ton!

**Comment by thyeun** [comment]
you know how to make the player appear on the bar? my player still not appear
