### ISSUE TITLE
Some apps are not respecting the adw-gtk3-dark gtk theme 

### ISSUE THREAD

**Issue by AngryOwlAdv** [Aylur/dotfiles#150]
Apps like nautilus,calendar and gnome settings do not respect the gtk theme. Not sure how to fix.
![2024-01-29_16-20-55](https://github.com/Aylur/dotfiles/assets/52570194/271404a8-3758-4dd2-b9f9-d4f3606a2277)

**Comment by Aylur** [comment]
I've had this issue since gnome 45 was released, It seems to not pick up the gsettings, its an issue with gtk/libadwaita
