### ISSUE TITLE
ambiguous indirect export FontIcon.js:2:19

### ISSUE THREAD

**Issue by theunpleasantowl** [Aylur/dotfiles#152]
I'm running the latest stable version (i.e. AGS 1.6.3) and I set up the dotfiles from this repo. When I run `ags` I get this error:

```
(com.github.Aylur.ags:34046): Gjs-WARNING **: 19:48:31.541: JS ERROR: SyntaxError: ambiguous indirect export: register @ file:///home/tsu/.config/ags/js/misc/FontIcon.js:2:19
```

I don't understand. Did I do something wrong?

**Comment by Aylur** [comment]
My dotfiles follow the git version which is currently at 1.7.3
Either update ags, or get an earlier version of my dotfiles that's 1.6.3 compatible
