### ISSUE TITLE
Widget does not close when clicked outside of it, after closing widget activewindow doesnt have text input focus

### ISSUE THREAD

**Issue by daUnknownCoder** [Aylur/dotfiles#153]
I am not able to regain focus to the current active window and the widget doesnt close automatically as it used to since today and i didnt even change a tiny setting...

https://github.com/Aylur/dotfiles/assets/84800625/3e27c9f6-e631-405e-a22e-a95780b9d560

also i noticed this behaviour [ only for not regaining focus in the active window after closing the widget by clicking again and not for auto closing of the widget ] -> when `input:follow_mouse` is set to 2 and above in `hyprland.conf`

```hypr
input {
    follow_mouse = 0
}
```

**Comment by Aylur** [comment]
The click away functionality was based on a bug that was recently patched in Hyprland
see https://github.com/Aylur/ags/issues/63

**Comment by AhsanSarwar45** [comment]
@Aylur The App Launcher example in the wiki is no longer working properly due to this. Is there any alternative ways to achieve this behavior?

**Comment by daUnknownCoder** [comment]
https://github.com/Aylur/dotfiles/assets/84800625/ee3fa6ed-33f1-4c99-ae92-45d6cfa77449
