### ISSUE TITLE
Full system upgrade + ags update = no longer rendering widgets

### ISSUE THREAD

**Issue by TLSingh1** [Aylur/dotfiles#157]
Hi!

Forgive me as this is probably a user error.

As the title suggets, I recently did a full system upgrade and now all the widgets except the FloatingDock renders/launches.

Currently, I shamelessly stole Aylur's config and tweaked it to my liking. I'm on ags v1.7.4 and I couldn't find anywhere to install v.1.7.5 manually.

Previously, i had been launching the program and toggling all widgets w/a keybind in hyperland like so:

`AGS_SKIP_V_CHECK=true ags --toggle-window "overview"`

In addition, when running AGS with the skip_v_check, I get the following output error in terminal:

`
❯ AGS_SKIP_V_CHECK=true ags

(com.github.Aylur.ags:10887): Gjs-WARNING **: 16:04:07.094: JS ERROR: Error: No property children on Ags_Stack
_init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:59:50
_init@resource:///com/github/Aylur/ags/widgets/widget.js:91:15
Stack@resource:///com/github/Aylur/ags/widgets/stack.js:36:9
Stack@resource:///com/github/Aylur/ags/widget.js:35:33
OnScreenIndicatorhttps://github.com/file:///home/tai/.config/ags/js/osd/OSD.js:20:27
default@file:///home/tai/.config/ags/js/osd/OSD.js:52:12
forMonitors@file:///home/tai/.config/ags/js/utils.js:31:24
windows@file:///home/tai/.config/ags/js/main.js:27:5
@file:///home/tai/.config/ags/js/main.js:41:14
_init/GLib.MainLoop.prototype.runAsync/</<https://github.com/resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:10887): Gjs-CRITICAL **: 16:04:16.723: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x5dcbe569f060.
== Stack trace for context 0x5dcbe4ca7e40 ==
#0 5dcbe4d85e98 i resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (3af5b837c420 @ 139)

(com.github.Aylur.ags:10887): Gjs-CRITICAL **: 16:04:16.724: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was destroy on Ags_Box 0x5dcbe568ed80.
== Stack trace for context 0x5dcbe4ca7e40 ==
#0 5dcbe4d85e98 i resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266 (3af5b837c420 @ 139)
`

And those last two errors keep repeating quite a bit.

In addition, when trying to toggle from hyprlands keybinds, unsurprisingly I get the following error;

`
(com.github.Aylur.ags:10887): Gjs-Console-CRITICAL **: 16:06:21.731: Error: There is no window named quicksettings
getWindow@resource:///com/github/Aylur/ags/app.js:122:27
toggleWindow@resource:///com/github/Aylur/ags/app.js:97:24
ToggleWindow@resource:///com/github/Aylur/ags/app.js:245:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
`

Once again, I'm really sorry as this is almost definitely a user error who isnt doing their due diligence themselves and creating/learning the config from scratch. I'm in love with this software and has been my favorite thing about using arch and hyprland so far. I'd be super grateful for any guidance. 

Thanks again.

**Comment by Aylur** [comment]
the config uses Stack.children which was introduced in 1.7.5
you just need to update ags to the git version
