### ISSUE TITLE
How are you offsetting the position of the quicksettings/dashboard window?

### ISSUE THREAD

**Issue by musjj** [Aylur/dotfiles#159]
I tried looking at `ags --inspector`, but I'm not quite sure how it's working. It looks like that the rendered content is smaller than the actual window size.

I thought you were making the window transparent and having `.window-content` render the actual background with the right `margin`, but it looks like that you're doing something else.

**Comment by Aylur** [comment]
I am not sure what you mean, the window widgets are anchored, and are exclusive I am not offsetting them
