### ISSUE TITLE
Clock widget on desktop not centered

### ISSUE THREAD

**Issue by Azkaas** [Aylur/dotfiles#16]
![image](https://github.com/Aylur/dotfiles/assets/112915552/243669b8-7f04-4957-982b-f953ad77ed2a)

Hi, sorry for opening another issue so fast. I seem to have most things working now, but cant seem to get the clock widget and the box to match. Ive tried fiddling with the numbers in the desktop.yuck and desktop.scss files, but no luck

**Comment by thyeun** [comment]
@Azkaas you have to adjust your font, try change your font into ```Ubuntu Nerd Font```, only this font will give you exact center for all icons on the bar, especially the ```brightness icon```, you can change the font from the file ```variables.scss```.

And make sure you have a mono font too.

The media player appear on your bar? might share out your screen for your media player on the bar?

**Comment by Azkaas** [comment]
![image](https://github.com/Aylur/dotfiles/assets/112915552/1669a9c1-deb9-4242-b98d-ff30bd39fca9)
Thanks, its working but i had to change the mono_font to Ubuntu Nerd Font in order to make it work. Is this correct?

About the media player, i unfortunatly dont have those buttons no :/ I think the media buttons, and the network widget are the two things left to fiddle with. The network widget was pointing towards the bluetooth launcher on click before

**Comment by thyeun** [comment]
@Azkaas for the network on click function, you need to make the network script file to function correctly.

Not sure why the media player never appear, either own remove the block from bar-widgets or the file we have are not the latest one.

**Comment by thyeun** [comment]
Follow this step to make your network function.

1. Edit the file ```~/.config/eww/scripts/launcher```, by changing the ```if [[ $1 == 'network'        ]]; then network; fi``` to ```if [[ $1 == 'network'        ]]; then nm-connection-editor; fi```
2. Than open the file ```~/.config/eww/yuck/widgets/toggles.yuck``` and find the line ```:toggle_action "${EWW_CONFIG_DIR}/scripts/launcher bluetooth"))``` and change it to ```:toggle_action "${EWW_CONFIG_DIR}/scripts/launcher network"))```

But make sure your ```nm-connection-editor``` as same as below image. (You can copy it and run it on terminal)
![Screenshot_2023-05-11-01-12-03_18631](https://github.com/Aylur/dotfiles/assets/1939446/a4e26736-852f-43ee-adeb-3b12e2d1927a)

**Comment by Azkaas** [comment]
Thanks a ton once again!
Ive followed your steps and it works. However im not used to this applet, so im not sure how to look for the networks around me with this? It only shows the networks ive previously connected to, and if i want to connect to a new network, i have to set it up manually?

Also yeah, i will see if i can figure out the media players buttons. If i can, i will get back to you :)

**Comment by thyeun** [comment]
@Azkaas If you want to create a new network, you can press the ```+``` or you can change to the applet you use mostly.
by edit the line ```nm-connection-editor```.

Actually the ```nm-connection-editor``` have a tray icon, but if you using this eww bar, you wont see the tray icon, and to call out the tray icon run ```nm-applet``` at terminal you will see it as picture below once you right click the tray icon.

![Screenshot_2023-05-11-11-28-50_3070](https://github.com/Aylur/dotfiles/assets/1939446/315cd81a-8088-4c39-8356-8ad31d868205)

**Comment by Azkaas** [comment]
Thanks once again :)
nm-applet unfortunatly didnt work for me, as you need a systray for it. Cant seem to launch it from the terminal either.

I was however able to get it to work through rofi instead with networkmanager-dmenu. I actually like it better than nm-applet

**Comment by thyeun** [comment]
Wofi also can make it, i have one also =.=

**Comment by Azkaas** [comment]
Yeah, i was thinking o Wofi as well, but i already had my themes etc configured in Rofi :P

Btw, out of curiousity, does the bar have a delay for you when switching workspaces? For me there is like 1-2 sec delay of the bar showing that i moved to said workspace. Not a dealbreaker, but still a small annoyance

**Comment by thyeun** [comment]
Not sure for that, but i think most of the eww-wayland will have some delay
