### ISSUE TITLE
i have dart-sass installed but it gives me an error

### ISSUE THREAD

**Issue by daUnknownCoder** [Aylur/dotfiles#160]
```bash
pacman -Q dart-sass
dart-sass 1.70.0-1
```

`(com.github.Aylur.ags:27672): Gjs-Console-WARNING **: 16:20:38.288: missing dependencies: dart-sass`

idk why

and i still got those JSAPI shit...
```js
(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.223: Theme parsing error: gtk.css:63:28: The :prelight pseudo-class is deprecated. Use :hover instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.223: Theme parsing error: gtk.css:73:35: The :prelight pseudo-class is deprecated. Use :hover instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.223: Theme parsing error: gtk.css:115:31: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.223: Theme parsing error: gtk.css:116:24: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.223: Theme parsing error: gtk.css:145:27: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.224: Theme parsing error: gtk.css:146:29: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.224: Theme parsing error: gtk.css:166:34: The :insensitive pseudo-class is deprecated. Use :disabled instead.

(com.github.Aylur.ags:27672): Gtk-WARNING **: 16:20:32.224: Theme parsing error: gtk.css:187:34: The :inconsistent pseudo-class is deprecated. Use :indeterminate instead.
Another notification daemon is already running, make sure you stop Dunst or any other daemon you have running

(com.github.Aylur.ags:27672): Gjs-Console-WARNING **: 16:20:38.288: missing dependencies: dart-sass

(com.github.Aylur.ags:27672): Gjs-Console-CRITICAL **: 16:20:38.341: Error: can't assign "preferences-desktop-theme-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:40:31
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:116:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:23:14
Icon@resource:///com/github/Aylur/ags/widget.js:26:32
Header/<.center_widget<.children<@file:///tmp/ags/main.js:2505:16
Header@file:///tmp/ags/main.js:2500:30
SettingsDialog_default@file:///tmp/ags/main.js:2538:7
@file:///tmp/ags/main.js:3407:5
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:27672): Gjs-Console-CRITICAL **: 16:20:38.343: Error: can't assign "toolbars-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:40:31
_handleParamProp@resource:///com/github/Aylur/ags/widgets/widget.js:116:13
Icon@resource:///com/github/Aylur/ags/widgets/icon.js:23:14
Icon@resource:///com/github/Aylur/ags/widget.js:26:32
Header/<.center_widget<.children<@file:///tmp/ags/main.js:2505:16
Header@file:///tmp/ags/main.js:2500:30
SettingsDialog_default@file:///tmp/ags/main.js:2538:7
@file:///tmp/ags/main.js:3407:5
async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:27672): Gjs-CRITICAL **: 16:20:38.517: Attempting to call back into JSAPI during the sweeping phase of GC. This is most likely caused by not destroying a Clutter actor or Gtk+ widget with ::destroy signals connected, but can also be caused by using the destroy(), dispose(), or remove() vfuncs. Because it would crash the application, it has been blocked and the JS callback not invoked.
The offending signal was access-point-removed on NMDeviceWifi 0x55be5b72dc80.
== Stack trace for context 0x55be5af138e0 ==
```

and i cant start ags too @Aylur

**Comment by dawidduraj** [comment]
I have the same issue (just the dart-sass part)

**Comment by shyHelios** [comment]
Edit ags/style/style.ts, find "dependencies("dart-sass", "fd")" and change it to "dependencies("sass", "fd")".Hope this will help you.

**Comment by dawidduraj** [comment]
> Edit ags/style/style.ts, find "dependencies("dart-sass", "fd")" and change it to "dependencies("sass", "fd")".Hope this will help you.

Thanks you! That fixed my issue

**Comment by daUnknownCoder** [comment]
That works thanks

**Comment by Edesem** [comment]
> Edit ags/style/style.ts, find "dependencies("dart-sass", "fd")" and change it to "dependencies("sass", "fd")".Hope this will help you.

Is it just me or does that literally not appear in my config

This is my config and its just the current config of Aylur

`/* eslint-disable max-len */
import { type Opt } from "lib/option"
import options from "options"
import { bash, dependencies, sh } from "lib/utils"

const deps = [
    "font",
    "theme",
    "bar.flatButtons",
    "bar.position",
    "bar.battery.charging",
    "bar.battery.blocks",
]

const {
    dark,
    light,
    scheme,
    padding,
    spacing,
    radius,
    shadows,
    widget,
    border,
} = options.theme

const popoverPaddingMultiplier = 1.6

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const t = (dark: Opt<any> | string, light: Opt<any> | string) => scheme.value === "dark"
    ? `${dark}` : `${light}`

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const $ = (name: string, value: string | Opt<any>) => `$${name}: ${value};`

const variables = () => [
    $("bg", t(dark.bg, light.bg)),
    $("fg", t(dark.fg, light.fg)),

    $("primary-bg", t(dark.primary.bg, light.primary.bg)),
    $("primary-fg", t(dark.primary.fg, light.primary.fg)),

    $("error-bg", t(dark.error.bg, light.error.bg)),
    $("error-fg", t(dark.error.fg, light.error.fg)),

    $("scheme", scheme),
    $("padding", `${padding}pt`),
    $("spacing", `${spacing}pt`),
    $("radius", `${radius}px`),
    $("transition", `${options.transition}ms`),

    $("shadows", `${shadows}`),

    $("widget-bg", `transparentize(${t(dark.widget, light.widget)}, ${widget.opacity.value / 100})`),

    $("hover-bg", `transparentize(${t(dark.widget, light.widget)}, ${(widget.opacity.value * .9) / 100})`),
    $("hover-fg", `lighten(${t(dark.fg, light.fg)}, 8%)`),

    $("border-width", `${border.width}px`),
    $("border-color", `transparentize(${t(dark.border, light.border)}, ${border.opacity.value / 100})`),
    $("border", "$border-width solid $border-color"),

    $("active-gradient", `linear-gradient(to right, ${t(dark.primary.bg, light.primary.bg)}, darken(${t(dark.primary.bg, light.primary.bg)}, 4%))`),
    $("shadow-color", t("rgba(0,0,0,.6)", "rgba(0,0,0,.4)")),
    $("text-shadow", t("2pt 2pt 2pt $shadow-color", "none")),

    $("popover-border-color", `transparentize(${t(dark.border, light.border)}, ${Math.max(((border.opacity.value - 1) / 100), 0)})`),
    $("popover-padding", `$padding * ${popoverPaddingMultiplier}`),
    $("popover-radius", radius.value === 0 ? "0" : "$radius + $popover-padding"),

    $("font-size", `${options.font.size}pt`),
    $("font-name", options.font.name),

    // etc
    $("charging-bg", options.bar.battery.charging),
    $("bar-battery-blocks", options.bar.battery.blocks),
    $("bar-position", options.bar.position),
    $("hyprland-gaps-multiplier", options.hyprland.gaps),
]

async function resetCss() {
    if (!dependencies("dart-sass", "fd"))
        return

    const vars = `${TMP}/variables.scss`
    await Utils.writeFile(variables().join("\n"), vars)

    const fd = await sh(`fd ".scss" ${App.configDir}`)
    const files = fd.split(/\s+/).map(f => `@import '${f}';`)
    const scss = [`@import '${vars}';`, ...files].join("\n")
    const css = await bash`echo "${scss}" | sass --stdin`
    const file = `${TMP}/style.css`

    await Utils.writeFile(css, file)

    App.resetCss()
    App.applyCss(file)
}

export default function init() {
    Utils.monitorFile(App.configDir, resetCss)
    options.handler(deps, resetCss)
    resetCss()
}`

**Comment by daUnknownCoder** [comment]
I see it
> if (!dependencies("dart-sass", "fd"))

It's in the async function

**Comment by Edesem** [comment]
Ok true I missed that but even after editing it I still have the same issue alongside the icons being missing

**Comment by daUnknownCoder** [comment]
> Ok true I missed that but even after editing it I still have the same issue alongside the icons being missing

for the icons, you can turn off monochrome icons wherever they are in settings @Edesem, tho i also feel @Aylur  should go back to js, i had spent weeks training meself in js and then there's TS which i dont know a shit about

**Comment by Edesem** [comment]
But why do you think it would still say i have the dart-sass dependency missing if I changed it to sass in the style.ts?

**Comment by daUnknownCoder** [comment]
> But why do you think it would still say i have the dart-sass dependency missing if I changed it to sass in the style.ts?

did u install dart-sass, and sassc?

**Comment by daUnknownCoder** [comment]
my bar looks like 
![image](https://github.com/Aylur/dotfiles/assets/84800625/e2557108-f70d-4529-bd8b-5126180f3dbb)
while it was 
![image](https://github.com/Aylur/dotfiles/assets/84800625/ecda489e-01dd-467c-b2f1-8a166b7d3317)

**Comment by Edesem** [comment]
Yep
![image](https://github.com/Aylur/dotfiles/assets/93417266/feb04772-c4fd-48f9-b570-d16ef99b8358)

but this is what I get

![image](https://github.com/Aylur/dotfiles/assets/93417266/7860e182-c75e-4b7d-87c9-8b02dc354a53)

**Comment by daUnknownCoder** [comment]
see bro, i m going back to my js config, after aylur releases his public dots i will check coz it in WIP so...

**Comment by Edesem** [comment]
Went back to js version and it works!

**Comment by daUnknownCoder** [comment]
> Went back to js version and it works!

If u Wanna check, if u use neo I'm with telescope.nvim and ripgrep, u can open `~/.config/ags` and start live grep and search for `dart-sass` and replace with `sass`

**Comment by daUnknownCoder** [comment]
> I replaced dart-sass as sass, I didn't know other distributions don't include a `dart-sass` executable

Cool
