### ISSUE TITLE
[Hyprland] Top bar blocking clickable area in windows

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#163]
Resolution: 1280 x 1024

I can't sometimes click context menus or click tabs in Firefox.

**Edit:** Some area below the calendar seem to be an exception to this effect. AGS Inspector did not show any crossing boundaries, but I don't see how this can happen other than from AGS.

Basically all regions to the left and right, except wherever I can bring the drop down menu from are affected. I forgot to include that in the video. In the video I only showed the middle area where there is no problem.

Also, it's only a problem near the top area where the menus are, and in Firefox it's sometimes the upper half of the menu area (particularly noticeable when I'm trying to right click context menus going upwards)

https://github.com/Aylur/dotfiles/assets/28739146/551fe605-5a83-400c-a735-b0c197f4e278

**Comment by Aylur** [comment]
I have also experienced this, but I updated my system and it seems to go away, I suspect it was a Hyprland issue
If updating does not work for you, comment out `...forMonitors(ScreenCorners),` in main.js, see if that helps, that was my other suspect
