### ISSUE TITLE
installation stops...

### ISSUE THREAD

**Issue by Lxp1zero** [Aylur/dotfiles#166]
![Screenshot from 2024-02-24 17-41-04](https://github.com/Aylur/dotfiles/assets/126608444/c085ac6c-5d6c-4a7d-8546-751ade4d56a6)

logged to hyprland and run the command but it just don't do anything after that

**Comment by Lxp1zero** [comment]
using nixos

**Comment by Aylur** [comment]
are you sure you are in a Hyprland session, and running this from a terminal?

**Comment by Lxp1zero** [comment]
> are you sure you are in a Hyprland session, and running this from a terminal?

I first ran the command in hyprland it returns the same error and I wanted screenshot to issue so I returned to gnome and ran the command screen-shotted it, posted here


>First, Logged into hyprland
> Ran the command and script stops and don't do anything after that
>Logged into gnome to screenshot and issue it here

Tell me if i need to screenshot it in hyprland

**Comment by Lxp1zero** [comment]
> are you sure you are in a Hyprland session, and running this from a terminal?

Yes I'm in kitty

**Comment by Aylur** [comment]
The actual error from the Hyprland session would be preferable, yes
How are you launching Hyprland? Is the `HYPRLAND_INSTANCE_SIGNATURE` env variable being overshadowed somehow?

**Comment by Lxp1zero** [comment]
![IMG_20240227_085151](https://github.com/Aylur/dotfiles/assets/126608444/2b581142-4721-4d55-b266-4ac8f927375c)

**Comment by Aylur** [comment]
icon errors can be ignored, scroll up a bit, there should be some other error stopping it from launching
