### ISSUE TITLE
hyprland on Arch Vbox?

### ISSUE THREAD

**Issue by Th34t0m1c** [Aylur/dotfiles#171]
Hi everyone,

I recently discovered Arch Linux and started exploring desktops when I found this repository.

I've been trying to install Hyprland on Arch within a VirtualBox virtual machine but have encountered errors in all my attempts.

I'm curious if installing Hyprland on Arch in a VirtualBox machine is possible.

My system specs are an AMD Ryzen 5600 CPU and NVIDIA 2070S GPU, although I'm unsure if these specifications impact the installation process.

I'm very interested in using Aylur's Hyprland as the desktop environment on my Arch system.

Thank you in advance for your help.

**Comment by Aylur** [comment]
I don't use VirtualBox, but on qemu virtio needs to be enabled for Hyprland, I think its 3d acceleration for VirtualBox or something of that sort

**Comment by Th34t0m1c** [comment]
> I don't use VirtualBox, but on qemu virtio needs to be enabled for Hyprland, I think its 3d acceleration for VirtualBox or something of that sort

Yeah, finally I can install it without errors, and needs to enable the 3D acceleration to works "fine". I know now why all the people say "don't use in VM". The machine is a little big lagged even after increased the hardware specifications, specially the VRAM.

Thank for your response!

**Comment by keilmillerjr** [comment]
> > I don't use VirtualBox, but on qemu virtio needs to be enabled for Hyprland, I think its 3d acceleration for VirtualBox or something of that sort
> 
> Yeah, finally I can install it without errors, and needs to enable the 3D acceleration to works "fine". I know now why all the people say "don't use in VM". The machine is a little big lagged even after increased the hardware specifications, specially the VRAM.
> 
> Thank for your response!

My video card supports 3d acceleration, yet I could not get 3d acceleration to work. I have given up after asking on many forums and discord groups with only one person who even responded. I think I need a newer video card. Mine was the last video card to support analog video. Woohoo! I love CRT's! The timing of when it was released means that it was right on the cusp of changing technologies. Issues like mine is likely why people make a blanket statement of "don't use in a vm".

**Comment by Th34t0m1c** [comment]
My video card supports 3d acceleration, yet I could not get 3d acceleration to work. I have given up after asking on many forums and discord groups with only one person who even responded. I think I need a newer video card. Mine was the last video card to support analog video. Woohoo! I love CRT's! The timing of when it was released means that it was right on the cusp of changing technologies. Issues like mine is likely why people make a blanket statement of "don't use in a vm".

What model of GPU you have? I saw that it is NVIDIA it didn't works properly. I think the problem of use VM is that hyprland consume a lot of VRAM, and in VM it's limited. I finally choose to install bspwn, polybar and more stuff.

**Comment by keilmillerjr** [comment]
> What model of GPU you have? I saw that it is NVIDIA it didn't works properly. I think the problem of use VM is that hyprland consume a lot of VRAM, and in VM it's limited. I finally choose to install bspwn, polybar and more stuff.

AMD ATI Radeon R9 380

The issue is not hyprland. Enabling 3d acceleration and spice in virt-manager would yield qemu crashing before even booting the bios. Using other gui managers yields the same results. I exhausted way too much time into trying to figure out the issue. A ~3500 line log file doesn't help me.

I am on the hunt for a cheap RX 590 to see if that resolves the issue... but I am currently flat broke.
