### ISSUE TITLE
Half working

### ISSUE THREAD

**Issue by BlokCSS** [Aylur/dotfiles#174]
Hello! Your dots are amazing and love ags. I followed every step on your repo (without nixos) and half of the style its working.
The other thing its when type ags, its changes to your dots (like a said half of them hahah ) but if i close the terminal, all is gone.
Hope can you help me or guide through this cuz i really want to daily drive your dots :D

Maybe i have to do some manually work to get done, but it is confusing
Cheers!

**Comment by DarkSusan** [comment]
You just need to type:
```bash
ags & disown
```

**Comment by keilmillerjr** [comment]
Half of the style is working? Do you have a photo or log file?

**Comment by BlokCSS** [comment]
thanks for the answer! 
Now i think its working, but when i restart, it comes back to raw hyprland. I have to write again ags & disown. How can i get that to be persistent

**Comment by DarkSusan** [comment]
In your hyprland.conf you need to add
```
exec-once = ags
```
