### ISSUE TITLE
Scrip failures

### ISSUE THREAD

**Issue by BlokCSS** [Aylur/dotfiles#175]
Ive tried to use the script in different ways, but nothing works as expected:

I run the first scritp to instal Nix and doesnt work, so i installed NixOS KDE and run the second script and seems not working. It reads the following:

_****[v0iddd@nixos:~]$ nix profile install github:Aylur/dotfiles
error: builder for '/nix/store/8d866vqf2zapfgs6q7w76c4j85n5y6an-asztal.drv' failed with exit code 132;
       last 9 log lines:
       > Running phase: unpackPhase
       > unpacking source archive /nix/store/jvwpjwbp41854wbfqsw01lgnmvwzvzha-ags
       > source root is ags
       > Running phase: patchPhase
       > Running phase: updateAutotoolsGnuConfigScriptsPhase
       > Running phase: configurePhase
       > no configure script, doing nothing
       > Running phase: buildPhase
       > /nix/store/3qnm3nwjajgqa771dmi2dnwxrw0kzq5m-stdenv-linux/setup: line 1581:    35 Illegal instruction     (core dumped) /nix/store/jk432rp4sfm9y912yy071cxdx30bbhvm-bun-1.0.29/bin/bun build ./main.ts --outfile main.js --external "resource://*" --external "gi://*"
       For full logs, run 'nix-store -l /nix/store/8d866vqf2zapfgs6q7w76c4j85n5y6an-asztal.drv'.
error: 1 dependencies of derivation '/nix/store/k77vwhpdk6735z0jycam64rpnb6p4wra-asztal.drv' failed to build****_

I have to do some previous steps? I cant understand

**Comment by Aylur** [comment]
that's a weird one, it seems like `bun` is failing on you, which shouldn't happen with flakes

**Comment by BlokCSS** [comment]
ill try to use on hyprland with arch instead, ill be msg you for tips :D
(your work is amazing)

**Comment by Aylur** [comment]
does it work with esbuild?
[esbuild.patch.txt](https://github.com/Aylur/dotfiles/files/14623566/esbuild.patch.txt)
