### ISSUE TITLE
Greeter issues.

### ISSUE THREAD

**Issue by wenjinnn** [Aylur/dotfiles#179]
Thanks for the great work.

I'm follow your dotfiles for a while, and I find some issue with the greeter.

Greeter widgets are too small in hidpi (e. g. my 4k screen display), because cage didn't set a correct scale value. Here's my solution with wlr-randr, set a correct scale for particular output:

https://github.com/wenjinnn/config/blob/958b8e172a6778ebd30397e60883abe50bdc494a/overlays/ags-greeter/default.nix#L59

Also before greeter initialization, background color will turn to black from white (guess the background color is default to #FFFFFF), which present like a short flash light. it could fix by preset a background color before initialization finished:

https://github.com/wenjinnn/config/blob/958b8e172a6778ebd30397e60883abe50bdc494a/xdg/config/ags/greeter/greeter.ts#L35C1-L39C3

Hope it help.

**Comment by Aylur** [comment]
I fixed the flashbang issue, but the hidpi is a personal issue, so thats on others to fix
