### ISSUE TITLE
error while run "asztal"

### ISSUE THREAD

**Issue by Alaa2472** [Aylur/dotfiles#180]
[qayselsamouly@nixos:~]$ asztal

(com.github.Aylur.ags:11902): Gjs-Console-CRITICAL **: 13:31:40.820: swww img --transition-type grow --transition-pos 92,498 /home/qayselsamouly/.config/background Error: "failed to open image: No such file or directory (os error 2)"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
^[[A^[[B^[[Bno icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:11902): Gtk-WARNING **: 13:32:05.809: Failed to fetch network locations: Timeout was reached

(com.github.Aylur.ags:11902): Gtk-WARNING **: 13:32:05.809: Failed to fetch network locations: Timeout was reached
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

>>>>> i maked new Nixos install and hyprland install with configuration.nix file
i only installed the repo Aylur:dotfiles and enter hyprland and this problem is shown when i write "asztal" and didnt make any change

this is my discord account if any one need long talk >>>> q1ys

**Comment by Aylur** [comment]
swww looks for ./confg/background for the initial image, it can be ignored
the network one can be ignored probably too, haven't seen that warning yet though
the rest is just warnings about missing icons, can be ignored
