### ISSUE TITLE
Dependency on bun doesn't make it work on musl libc

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#181]
New dotfiles don't work, old one doesn't work with updated ags.

I have no bar now :(

**Comment by Aylur** [comment]
does `esbuild` work on musl?

**Comment by blacklightpy** [comment]
> does `esbuild` work on musl?

yea

**Comment by Aylur** [comment]
run with `AGS_BUNDLER=esbuild ags`

**Comment by blacklightpy** [comment]
> run with `AGS_BUNDLER=esbuild ags`

That works, but it has a lot of problems.

Images:
![2024-03-16_19-04-28](https://github.com/Aylur/dotfiles/assets/28739146/c1dcbc7b-73d6-4a2f-b8f4-46b1873b2bfa)
![2024-03-16_19-04-57](https://github.com/Aylur/dotfiles/assets/28739146/4d7d877b-98f8-446a-8367-4d40cfdab9a4)


- Icons aren't rendered
- Dock isn't active
- Right click on desktop doesn't work
- Clicking Workspace switcher takes me to the Workspaces view
- The Linux icon on top left is a rotating pin (like the one used to eject SIM card slots)
- Clicking on active apps switch workspace, but place the mouse pointer at the center of the window
- The windows take up the entirety of the screen excluding the top bar
- Fonts are not as sleek as they used to be before
- No profiles to choose from, and it is marked as undefined.

Edit: I think the problem is partly that the profiles aren't recognized. When I clicked this "Gaps When Only" feature, my windows got borders.

![image](https://github.com/Aylur/dotfiles/assets/28739146/eb707d48-bc9f-447f-9dc3-8772dce6a593)

```
jyothish@void ~/.config> AGS_BUNDLER=esbuild ags
no icon substitute "void" for "void", fallback: "system-search-symbolic"

(com.github.Aylur.ags:15312): Gjs-Console-CRITICAL **: 19:01:35.591: swww img --transition-type grow --transition-pos 629,662 /home/jyothish/.config/background Error: "failed to open image: No such file or directory (os error 2)"

(com.github.Aylur.ags:15312): Gjs-Console-CRITICAL **: 19:01:37.139: nix search nixpkgs/nixos-unstable --json error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

(com.github.Aylur.ags:15312): Gjs-WARNING **: 19:01:37.139: Unhandled promise rejection. To suppress this warning, add an error handler to your promise chain with .catch() or a try-catch block around your await expression. Stack trace of the failed promise:
  #updateList@file:///tmp/ags/main.js:1095:23
  Nix@file:///tmp/ags/main.js:1063:21
  @file:///tmp/ags/main.js:1110:11
  async*_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:15312): Gjs-Console-CRITICAL **: 19:01:37.191: net.hadess.PowerProfiles is not available
no icon substitute "picom" for "picom", fallback: "application-x-executable-symbolic"
no icon substitute "picom" for "picom", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:15312): Gjs-Console-WARNING **: 19:01:39.425: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:50:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:15312): Gjs-Console-WARNING **: 19:01:39.427: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:50:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:15312): Gjs-CRITICAL **: 19:01:39.431: JS ERROR: TypeError: audio2.microphone.stream is null
MicrophoneMute/</<@file:///tmp/ags/main.js:2589:7
idle/<@resource:///com/github/Aylur/ags/utils/timeout.js:20:9
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:15312): Gjs-Console-WARNING **: 19:01:39.500: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:50:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:15312): Gjs-CRITICAL **: 19:01:39.500: JS ERROR: Error: Wrong type undefined; string expected
_size@resource:///com/github/Aylur/ags/widgets/icon.js:67:13
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:52:14
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:15312): Gjs-CRITICAL **: 19:01:39.501: JS ERROR: TypeError: audio.microphone.stream is null
MicrophoneIndicator/<@file:///tmp/ags/main.js:1352:15
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:15312): Gjs-CRITICAL **: 19:01:46.558: JS ERROR: Error: Wrong type undefined; string expected
_size@resource:///com/github/Aylur/ags/widgets/icon.js:67:13
vfunc_draw@resource:///com/github/Aylur/ags/widgets/icon.js:82:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "QOwnNotes-symbolic" for "QOwnNotes-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "firefox-symbolic" for "firefox-symbolic", fallback: "application-x-executable-symbolic"
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"
```

**Comment by Aylur** [comment]
>Icons aren't rendered

your icon pack misses them, so either substitute in `lib/icons.ts` or add one in `assets`

>Dock isn't active
>Right click on desktop doesn't work
>Clicking Workspace switcher takes me to the Workspaces view

intended, these were removed/changed

>The Linux icon on top left is a rotating pin (like the one used to eject SIM card slots)

its an indicator that the nix database is being searched, do you have `nix` installed?

>Clicking on active apps switch workspace, but place the mouse pointer at the center of the window

its hyprland setting, don't remember which one though

>The windows take up the entirety of the screen excluding the top bar

gaps when only option
 
>Fonts are not as sleek as they used to be before

not sure what you mean, you can change the fonts, I use Ubuntu

>No profiles to choose from, and it is marked as undefined.

you don't have the powerprofiles dameon installed/running

**Comment by blacklightpy** [comment]
Ahh I see, at first I though I preferred the pre-TypeScript dotfiles. But after trying out the new settings manager a little, I think this is much better.

Yes, I have Nix installed, and I don't use ASUS laptops to have power profiles.

Also I noticed that the icons appear if I disable the monochrome switcher. But the icon sizes don't seem to change. Seems like I'm lacking monochrome icons specifically. Any ideas on how I can add them?

For the fonts, it was set to None by default, which used some random font. But when I set it to Ubuntu, it looks like how it was before. Perhaps some configuration bug?

Actually, playing around with the new settings menu helped clear up most of my doubts. The biggest difference the leaf theme had before was the rounding, which is easy to adjust here. I miss the default presets though, how the blur setting was set for the space theme, etc. It shouldn't be a problem to have them, right? It feels relaxing to switch up the personality with a simple click.

The previous version was a bit manual with having to create the JSON files ourselves, but it was still good. I wonder why it couldn't paste the files programmatically?

Aside from the Hyprland setting, which I need to figure out, and the new workspace switcher bringing up the overview feature which I need some getting used to, everything else is looking great!

About the workspace switcher.. shortcuts are fine, but sometimes I'm sitting in a dark room and there's no way for me to quickly switch workspaces now. Earlier, I could just click the logo. But I'm glad that now the logo functions more like the Start menu.

**Comment by blacklightpy** [comment]
> its hyprland setting, don't remember which one though

Found it: `no_cursor_warps = true`

**Comment by michael-pfister** [comment]
If anybody's wondering how to get rid of the `net.hadess.PowerProfiles is not available` critical error message. You can fix it by removing `service/asusctl.ts`. After which it will throw an error inside `widget/bar/buttons/SystemIndicators.ts` on launch so make sure to remove the imports there.

**Comment by blacklightpy** [comment]
> If anybody's wondering how to get rid of the `net.hadess.PowerProfiles is not available` critical error message. You can fix it by removing `service/asusctl.ts`. After which it will throw an error inside `widget/bar/buttons/SystemIndicators.ts` on launch so make sure to remove the imports there.

Or you could just install `power-profiles-daemon`..

**Comment by michael-pfister** [comment]
> > If anybody's wondering how to get rid of the `net.hadess.PowerProfiles is not available` critical error message. You can fix it by removing `service/asusctl.ts`. After which it will throw an error inside `widget/bar/buttons/SystemIndicators.ts` on launch so make sure to remove the imports there.
> 
> @michael-pfister Or you could just install `power-profiles-daemon`..
> 
> Also why did you mention it in this unrelated issue?

I didn't want to install a utility for managing power profiles on a Desktop PC that doesn't need power profiles. It wouldn't make sense. Moreover the 'asusctl' service seemed useless to me since I don't have an ASUS machine.

I added a solution as a comment to this closed issue because it's the only one that showed up when I searched for the error.

It was too much effort writing a whole new issue explaining the problem so I figured if anybody else searched for it they'd land here. Title-wise it's unrelated but the OC mentioned a solution to the exact problem above.

**Comment by blacklightpy** [comment]
@michael-pfister I see. #201 would've been a more related issue. There I tried to rewrite it using `powerprofilesctl` from `power-profiles-daemon`, but turns out he already had an implementation using `power-profiles-daemon` for non ASUS laptops.

But sure, you could remove `asusctl.ts` and fix it.
