### ISSUE TITLE
icon error

### ISSUE THREAD

**Issue by tang-rrrrrrrrggggbbbbbb** [Aylur/dotfiles#183]
Hello, I installed your dotfiles in the README file without nix. When I started AGS, it encountered the following error

**`no icon substitute "arch" for "arch", fallback: "system-search-symbolic"`**

How to solve it?

Thank!

**Comment by Aylur** [comment]
you have an application that request a named icon `arch`
either substitute it in `lib/icons.ts`
or add an `arch.svg` icon to `assets`
