### ISSUE TITLE
something ags error

### ISSUE THREAD

**Issue by tang-rrrrrrrrggggbbbbbb** [Aylur/dotfiles#184]
(com.github.Aylur.ags:26380): Gjs-Console-CRITICAL **: 17:59:32.056: swww img --transition-type grow --transition-pos 682,383 /home/wen/.config/background Error: "failed to open image: No such file or directory (os error 2)"

(com.github.Aylur.ags:26380): Gjs-Console-CRITICAL **: 17:59:32.452: Error: Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://GnomeBluetooth/?version=3.0:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

how to solve it

**Comment by K4R7IK** [comment]
`(com.github.Aylur.ags:26380): Gjs-Console-CRITICAL **: 17:59:32.056: swww img --transition-type grow --transition-pos 682,383 /home/wen/.config/background Error: "failed to open image: No such file or directory (os error 2)"`

swww isn't able to find the image at the specified directory as seen via this line **"failed to open image: No such file or directory (os error 2)"**

Also for the next line, ensure that gnome-bluetooth is at the latest version.
**Requiring GnomeBluetooth, version 3.0: Typelib file for namespace 'GnomeBluetooth', version '3.0' not found**

**Comment by Aylur** [comment]
1. set a wallpaper, either through gui or `options.ts`
2. install gnome-bluetooth-3.0
