### ISSUE TITLE
[Enhancement][Bug] Calendar and Quick Settings don't close unless I move the mouse first

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#185]
If I click the Calendar or Quick Settings to make them drop down, clicking again won't close it. I'll have to move the mouse a little to refocus and then it'll close. That's bad for UX. This isn't a problem with other buttons, including the media indicator.

Also, clicking somewhere on the bar won't close either of those dropdowns. It also means that when you have the Calendar open, opening Quick Settings won't close it and vice versa.

Even if that's a design choice, I think clicking other areas of the bar should close it, shouldn't it?

**Comment by Aylur** [comment]
its not a design choice, but a limitation of my solution to do popup windows, I could solve it, but it doesn't bother me so I just left it as it is
