### ISSUE TITLE
[Enhancement][Feature Request] Separate the roundedness of corners, all other widgets and the profile picture widget

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#186]
I may want to have a reduced corner rounding, but a larger rounding for all the other elements. That is because increased corner rounding may overlap the window elements a bit too much. I don't really want to turn it 

Also, when rounding is increased, the profile picture looks like a rhombus more than a rounded rectangle. The album art and profile picture aren't rounded uniformity either.

If I set the rounding factor too large, the album art becomes rounded, while the profile picture caps off at a maximum rounding. At the same time, the corner rounding can turn into a monstrosity at higher rounding levels. Many widget elements also fall out of place. 

![image](https://github.com/Aylur/dotfiles/assets/28739146/22478279-b038-46e1-9a51-bb4be8e9fe7d)

**Comment by Aylur** [comment]
I usually set it around 7-13 which works for me
there are hardcoded multipiers for stuff like the avatar, and album art, you could move them into an option
