### ISSUE TITLE
[Bug] KDEConnect Indicator not appearing on tray

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#187]
I can see Hyprpicker, and Steam tray icon also works. But KDEConnect Indicator does not appear. It was working well before I updated the dotfiles.

Terminal does not show any log either.

**Comment by Aylur** [comment]
https://github.com/Aylur/dotfiles/blob/ffd0a66743affabe0083cb6ac14ce10b7f549039/ags/options.ts#L125

**Comment by blacklightpy** [comment]
Why did you disable it though? Isn't it something you manually start?

**Comment by Aylur** [comment]
It'll start automatically for me, I don't need the tray icon
