### ISSUE TITLE
How to make the now playing label crop from the right when slide direction is set to right?

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#188]
Now I have my now playing track label like this:
![image](https://github.com/Aylur/dotfiles/assets/28739146/17dc1cc9-d54a-418b-9e0b-0257bc1490a6)

I could limit the label length or reduce font size, but the tray icons can still reduce the room for the label, again creating the overlap effect.

Instead, if I increase the label length, the last parts of the label remains visible, like this:
![image](https://github.com/Aylur/dotfiles/assets/28739146/ae74e759-eec5-4109-a36d-629eb1f98ef2)

I can set the Slide Direction to the left, but that moves the player icon to the right too, which I don't want.
![image](https://github.com/Aylur/dotfiles/assets/28739146/8213a2ab-5b9e-42ac-8a88-58b5aeaa4672)

Also, is it possible to make the label keep scrolling like the old HTML marquee element? That way, the whole title could be made useful.

It could also be preferable to set the label manually, like we set the date and time. For example, as `%artist - %track`, `%track - %artist` or `%track by %artist`. Still easy to edit from the code though.

**Comment by Aylur** [comment]
Im not sure what you mean, its cropping from the left already no?

> Also, is it possible to make the label keep scrolling like the old HTML marquee element? That way, the whole title could be made useful.

maybe, but too much work, and I prefer it this way

> It could also be preferable to set the label manually, like we set the date and time. For example, as %artist - %track, %track - %artist or %track by %artist. Still easy to edit from the code though.

good idea, I'll implement it later

**Comment by blacklightpy** [comment]
The label here is Propulsion Gel - How a Straight Line Through Space is the Longest Path Through Space Time.

When it is set to scroll towards right

If I set the label length to 40 (default), I get "Propulsion Gel - How a Straight Line..." as the label

But it renders as "pulsion Gel - How a Straight Line..." because it got cropped on the left side.

If I set the label length to 1000, I get "Longest Path Through Space Time"

What I want instead is, "Propulsion Gel - How a Straight L..." or something that sort.

I get that when I set scroll towards left, but then the player icon goes to the right when it expands, which I don't want.

**Comment by Aylur** [comment]
ah, yeah I get it, this is just how the label gets cropped with gtk
does it not do that if you just lower it further to 30-35?

**Comment by blacklightpy** [comment]
Yes, but then if the tray icons get populated (or if the app icons on the left get populated) the label still gets cropped. So that's not a solution.

**Comment by Aylur** [comment]
your solution here would probably be to bind the number of systray items as a max length instead of using the max length option

**Comment by blacklightpy** [comment]
Yes, that would do. How would I do that?

**Comment by Aylur** [comment]
```js
// Media.ts
const systemtray = await Service.import("systemtray")
const Content = () => {
  //
    max_width_chars: systemtray.bind("items").as(n => n * WHATEVER_YOU_NEED),
  //
```

**Comment by blacklightpy** [comment]
Now it just shows up as "...", and I only have 2 items on the tray.

```ts
const systemtray = await Service.import("systemtray")

const Content = (player: MprisPlayer) => {
    const revealer = Widget.Revealer({
        click_through: true,
        visible: length.bind().as(l => l > 0),
        transition: direction.bind().as(d => `slide_${d}` as const),
        setup: self => {
            let current = ""
            self.hook(player, () => {
                if (current === player.track_title)
                    return

                current = player.track_title
                self.reveal_child = true
                Utils.timeout(3000, () => {
                    !self.is_destroyed && (self.reveal_child = false)
                })
            })
        },
        child: Widget.Label({
            truncate: "end",
            max_width_chars: systemtray.bind("items").as(n => 40-n*2),// length.bind(),
            label: player.bind("track_title").as(() =>
                `${player.track_artists.join(", ")} - ${player.track_title}`),
        }),
    })
```

I'd also need the number of app icons, as I get this:

![image](https://github.com/Aylur/dotfiles/assets/28739146/c5e84b14-2fa7-455e-bbf8-f192b3badffd)
