### ISSUE TITLE
Teams-for-linux notification

### ISSUE THREAD

**Issue by Julien76** [Aylur/dotfiles#191]
Hi,

It is more a question than an issue but I am using a very similar setup than you (thanks by the way for the AGS and the inspiration from your dotfiles):
- nixos / home-manager
- hyprland from git
- ags (as per your dotfiles)

Everything works great except I cannot get notifications from teams-for-linux. 
Before migrating to nixos, it was working using arch + ags.

My question is: do you get notification from team-for-linux? If so did you do something special? (looking at your dotfiles I cannot spot anything obvious).

**Comment by Aylur** [comment]
I rarely use teams-for-linux, but now that you mention it, I don't remember ever getting a notification from the application
it sounds more like a packaging issue from nix, you could try the flatpak one maybe

**Comment by Julien76** [comment]
I tried with the lastest flatpak and it worked.
Afterwards I tried with the lastest in nixpkgs-unstable, version 1.4.14 and it also work now. Maybe the latest update fixes the issue.

**Comment by Julien76** [comment]
Well I might have spoke too soon, the nixos version does not always display the notifications while the flatpak one does. I will create an issue on the nix pkgs repo.
