### ISSUE TITLE
[Doubt] How to make icon packs recognized by ags?

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#192]
I have Breeze icon pack, which supplies icons like void-logo and preferences-system-linux-symbolic.

But it doesn't have firefox-symbolic.

I found that only Adwaita Plus and Yaru Plus had it. But even though I installed them and restarted ags, ags won't recognize their existence, unless I paste the complete path.

How can I get it to recognize the installed icon set?

**Comment by Aylur** [comment]
gtk will only search from one icon pack at a time
just copy a `firefox-symbolic.svg` file into the `assets` directory

**Comment by blacklightpy** [comment]
I guess colour icons would be the way to go here unless I plan on copying symbolic icons for every app I use.

**Comment by blacklightpy** [comment]
I figured it out. If you want symbolic icons for 3rd party apps, after installing the icon pack, you also have to set it, by using something like nwg-look.

Basically it just edits the default index.theme to inherit from the specified icon pack, which is also referred to as the icon theme.
