### ISSUE TITLE
ReferenceError, App not defined

### ISSUE THREAD

**Issue by e-v-o-l-v-e** [Aylur/dotfiles#194]
Hey, beginner here, sorry if this is dumb

When i try to start ags i get this :
```
$ ags

(com.github.Aylur.ags:32773): Gtk-WARNING **: 17:05:45.368: Theme parsing error: gtk.css:6691:68: Invalid name of pseudo-class

(com.github.Aylur.ags:32773): Gjs-Console-CRITICAL **: 17:05:45.430: ReferenceError: App is not defined
@file:///home/jack/.config/ags/config.js:4:18
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
 ```
 
 I tried to set it manually, it didn't work (or didn't do it right), 
 I replaced
 ```
 const entry = `${App.configDir}/main.ts`
 ```
on line 4 of the config.js file by
 ```
 const entry = `~/.config/ags/main.ts`
 ```
 but it also didn't work.
 
 So i come asking for help, thank you in advance, kind stranger.

**Comment by blacklightpy** [comment]
App is defined in `src/app.ts` of ags (not the dotfiles).

Did you install the latest version of ags?

**Comment by e-v-o-l-v-e** [comment]
Okay, i was, but inspired by your answer want and deleted _everything_ related to ags from my computer, then recleanbuilt everything and finaly made it works, thank you for your help ^^
