### ISSUE TITLE
[Suggestion] Set fallback icons for monochrome mode as the coloured versions of apps

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#195]
That, or at least provide an option for it.

From my current perspective, when using Adwaita Plus, only Firefox and QOwnNotes have symbolic icons. Yaru Plus adds them for Alacritty too.

Both themes don't have icons for Obsidian and nwg-look. But when I was using Yaru Plus or Adwaita Plus, which keeps app icons grey if they are size 16 or 24, I noticed it was better for the other apps to be represented as coloured while the supported apps are shown in monochrome.

**Here's how it looks for me now:**
Yaru++ (Monochrome mode, icons are white, not grey)
![image](https://github.com/Aylur/dotfiles/assets/28739146/0dafc291-e60c-4d38-9522-42d259560f35)
Yaru++ (Colour mode, icons are grey)
![image](https://github.com/Aylur/dotfiles/assets/28739146/18c3338a-808a-4242-a52d-711d21ac9d1f)
Adwaita++ Dark (Colour mode)
![image](https://github.com/Aylur/dotfiles/assets/28739146/17601633-2b94-448a-9d34-f1bebe9fa3f4)

**with default config:**
Adwaita++ (Monochrome Mode, Alacritty and Obsidian are fallback executable)
![image](https://github.com/Aylur/dotfiles/assets/28739146/7f79e9b6-b7a3-4ee8-a329-989e6be21422)
Yaru++ (Monochrome Mode, only Obsidian is fallback executable)
![image](https://github.com/Aylur/dotfiles/assets/28739146/1f514e3f-a277-46b8-b898-c5363c542f87)

As you can see, the apps are indistinguishable, unless I create alternate monochrome icons for them.

**Comment by Aylur** [comment]
I don't like to mix monochrome and colored Icons and this is not an issue with MoreWaita, the Icon pack I use
Your solution here is to setup `substitutes` in `lib/icons.ts` to your liking
