### ISSUE TITLE
Will this be possible to run on BSDs?

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#197]
I'm considering switching to FreeBSD, and having this would be nice.

As far as I think, AGS only depends on FreeBSD, and the dotfiles also only depend on utilities either have ports or can be built for the BSDs. Even inotify-tools has a FreeBSD port.

Just wanted to make sure it doesn't directly use any kernel specific feature.

**Comment by Aylur** [comment]
the widget system works on bsd afaik, since gtk, and wayland works the same
but some of the services are linux specific, so my setup is probably not compatible

**Comment by blacklightpy** [comment]
Oh, I thought none of the dependencies were. What are the services that are linux specific?

I haven't had the time to check everything, but if for power profiles, if you rely on upower, it is available for BSD.

Same goes for PipeWire.

Brightnessctl, swww, NetworkManager, Hyprpicker, Matugen and inotifywait have ports for FreeBSD.

I don't need use asusctl/supergfxctl as I don't have ROG/TUF. Although I'm trying to change it to powerprofilesctl.
