### ISSUE TITLE
Doesn't auto-generate  color scheme when changing wallpaper.

### ISSUE THREAD

**Issue by mohammedbilalns** [Aylur/dotfiles#198]
When changing the wallpaper, a notification shows `missing dependencies:ma...` . To adjust gaps without affecting widgets, I modified the file at [hyprland.ts](https://github.com/Aylur/dotfiles/blob/main/ags/lib/hyprland.ts) to:   

```
async function setupHyprland() {
    const wm_gaps = Math.floor(hyprland.gaps.value * spacing.value);
    const gaps_custom = 1;
    sendBatch([
        `general:border_size ${width}`,
        `general:gaps_out ${gaps_custom}`,
        `general:gaps_in ${Math.floor(gaps_custom)}`,
        `general:col.active_border rgba(${activeBorder()}ff)`,
        `general:col.inactive_border rgba(${hyprland.inactiveBorder.value})`,
        `decoration:rounding ${radius}`,
        `decoration:drop_shadow ${shadows.value ? "yes" : "no"}`,
        `dwindle:no_gaps_when_only ${hyprland.gapsWhenOnly.value ? 0 : 1}`,
        `master:no_gaps_when_only ${hyprland.gapsWhenOnly.value ? 0 : 1}`,
    ]);
}
```
Is that the cause of the issue?

**Comment by Aylur** [comment]
you have the `autotheme` option set to true, without having its dependency installed (`matugen`)

**Comment by mohammedbilalns** [comment]
Matugen is already  installed  
![2024-03-21_10-07-10](https://github.com/Aylur/dotfiles/assets/70318383/c8f36255-df90-45a6-86f6-9011a3d09174)

**Comment by 0x4d6165** [comment]
Having this same issue as well, matugen is installed
