### ISSUE TITLE
Fresh install of nix running first command

### ISSUE THREAD

**Issue by HinaHyugaHime** [Aylur/dotfiles#199]
![image](https://github.com/Aylur/dotfiles/assets/102651522/e083166a-d4d5-4dce-a1a9-ba1d9d01c436)

**Comment by HinaHyugaHime** [comment]
so if I already installed dotfiles why isnt the hyprland showing on login screen?

**Comment by Aylur** [comment]
You don't need to install nix yourself on nixos lmao.
The nix install command doesn't include Hyprland, you have to install it yourself

**Comment by HinaHyugaHime** [comment]
> You don't need to install nix yourself on nixos lmao. The nix install command doesn't include Hyprland, you have to install it yourself

same error after installing arch and trying there, I didnt know could do on arch but was told I coulde cause nix difficult

**Comment by HinaHyugaHime** [comment]
also this
``` ╰─λ sudo sh <(curl -L https://nixos.org/nix/install)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  4052  100  4052    0     0   8388      0 --:--:-- --:--:-- --:--:--  8388
fish: Invalid redirection target: 
sudo sh <(curl -L https://nixos.org/nix/install)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^```

**Comment by HinaHyugaHime** [comment]
fixed nvm
