### ISSUE TITLE
[Bug] Default Power Profiles not working

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#201]
You seem to have added both asusctl and the upower power profiles in the PowerProfile.ts

However, only the `asusctl` version seems to be working.

I edited it to use powerprofilesctl (from upower's power-profiles-daemon). You might want to do the same thing.

**Comment by Aylur** [comment]
I've been using the powerprofile service for a while now, and it seems to be working as expected for me
what issue exactly do you have?

**Comment by blacklightpy** [comment]
For me it was just an empty widget, the dropdown would be empty too.

**Comment by Aylur** [comment]
are you sure the daemon is running?

**Comment by blacklightpy** [comment]
Now that you mentioned it, it may have been that I didn't enable the daemon until after I made the changes to use powerprofilesctl. Let me see.

**Comment by blacklightpy** [comment]
You're right, I needlessly edited asusctl out.

But there's an aesthetic problem. Performance mode is at the bottom and Power Saving Mode is at the top.

Also is the toggle intended to only move between Power Saving and Balanced, or is it supposed to cycle? As far as I can see, it only switches between the two.

**Comment by Aylur** [comment]
thats just how I prefer it, I rarely set it to performance explicity

**Comment by blacklightpy** [comment]
Ok, now the only difference is that in power profiles, unlike ASUS power profiles, Performance is at the bottom and Power Saving is at the top. It looks weird, especially with the speedometer icons.
