### ISSUE TITLE
ags is not working (on nixos but only copied the ags Files into .config and installed it)

### ISSUE THREAD

**Issue by winder2412** [Aylur/dotfiles#202]
hi i'm running nixos and i wanted the install the ags From your dots so it installed it (imported it in the Flakes and enabled it via home-manager) and rebuilt the system and tried to run ags but it only prints this and closes it 

`(com.github.Aylur.ags:21777): Gjs-Console-CRITICAL **: 03:39:55.882:`

i did not install asztal because i thought its wasn't necessary as i just want the ags so maybe that's what causing the issue

i did run ags --init 
and the error that is provided is the only error that is showing up there is nothing else in the output

**Comment by Aylur** [comment]
are you sure its just that single line of empty error log?
have you installed the dependencies listed in the readme?

**Comment by winder2412** [comment]
the dependencies are all installed it runs when i run the example config From the wiki but it only shows the error i mentioned 
i copied all the inputs From your Flake in my Flake (except the FireFox one), the outputs are i little diFFrent because i'm importing home-manager in the conFiguration.nix File and i commented the configDir in the ags.nix File temperorly cause i was copying the ags in my .conFig directory and commented asztal pkg import because it was saying it cant Find the package when in i rebuild the system 

(sorry For the capital "F"s For some reason its not typing lowercase F in the browser right now )

**Comment by winder2412** [comment]
so it worked and the problem i think was that asztal was not installed i managed to install it and now its works by running asztal 

but i had one question 
is it possible to run it directly using ags

(i'll close the issue sence its solved)
