### ISSUE TITLE
Hyprland doesn't start

### ISSUE THREAD

**Issue by yashranjan1** [Aylur/dotfiles#203]
Hi I'm new to NixOS, so if I apologise if i missed something obvious. After a fresh install on a VM, I followed your readme and installed your profile, but it wouldn't start hyprland

**Comment by yashranjan1** [comment]
Hyprland doesnt start on a fresh install of NixOs on virtual box either, the screen legit goes black when I start Hyprland so I'm guessing this is an issue with the VM, I'll try a different one ig.

**Comment by Aylur** [comment]
https://wiki.hyprland.org/Getting-Started/Master-Tutorial/#vm
