### ISSUE TITLE
UI Not working

### ISSUE THREAD

**Issue by AXWTV** [Aylur/dotfiles#206]
![image](https://github.com/Aylur/dotfiles/assets/88997488/68e377be-f71a-47b8-9fd6-603d946ee545)

Is this normal, and if not how do I fix this?

**Comment by Aylur** [comment]
its just a guess that its the bluetooth icon, would you confirm that its fixed?
if its not, open up the inspector with `ags -i` and check which widget it is

**Comment by hjrabi** [comment]
i think this might be the profile i have the same issue and it's the only icon that doesn't appear
![image](https://github.com/Aylur/dotfiles/assets/143265590/3737c6e4-0059-47d1-9afe-036dd6a20074)

**Comment by AXWTV** [comment]
> i think this might be the profile i have the same issue and it's the only icon that doesn't appear
> ![image](https://github.com/Aylur/dotfiles/assets/143265590/3737c6e4-0059-47d1-9afe-036dd6a20074)
> 

Get the new dots from Aylur's repo.
It has been fixed.

**Comment by 3l0w** [comment]
Still an issue if `power-profiles-daemon` is not running
