### ISSUE TITLE
Greeter not showing up

### ISSUE THREAD

**Issue by Sitolam** [Aylur/dotfiles#215]
When I boot the dotfiles my screen just goes black and I need to go to the tty to active hyprland, how can I fix this? I'm also getting these errors when I'm building the flake maybe it can help:
```bash
cp: cannot stat '$HOME/.config/background': No such file or directory
chown: cannot access '/var/cache/greeter/background': No such file or directory
```

**Comment by Sitolam** [comment]
This is the output when I run `journalctl --unit greetd`:
```bash
-- Boot 9a93ff7c83734adbbcef31fe1296c46a --
Apr 08 13:44:05 nixotic systemd[1]: Started greetd.service.
Apr 08 13:44:06 nixotic greetd[1841]: pam_unix(greetd:session): session opened for user greeter(ui>
Apr 08 13:44:06 nixotic greetd[1841]: gkr-pam: gnome-keyring-daemon started properly
Apr 08 14:34:32 nixotic greetd[1757]: error: check_children: greeter exited without creating a ses>
Apr 08 14:34:32 nixotic systemd[1]: greetd.service: Deactivated successfully.
Apr 08 14:34:32 nixotic systemd[1]: greetd.service: Scheduled restart job, restart counter is at 1.
Apr 08 14:34:32 nixotic systemd[1]: Started greetd.service.
-- Boot 9067141af4ac4c0da9b678febf3e6c85 --
Apr 08 14:35:54 nixotic systemd[1]: Started greetd.service.
Apr 08 14:35:54 nixotic greetd[1836]: pam_unix(greetd:session): session opened for user greeter(ui>
Apr 08 14:35:55 nixotic greetd[1836]: gkr-pam: gnome-keyring-daemon started properly
```

Can't really figure things out with that, but how can I run the `greeter.js` config and what do I need to edit in the `greetd/session.ts` file?

**Comment by Sitolam** [comment]
This is the error that I get when I run `ags -t greeter`: 
```bash
(com.github.Aylur.ags:4142): Gjs-Console-CRITICAL **: 17:57:23.349: SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data
@file:///tmp/ags/main.js:513:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:4142): Gjs-Console-CRITICAL **: 17:57:23.350: Error: There is no window named greeter
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
toggleWindow@resource:///com/github/Aylur/ags/app.js:115:24
ToggleWindow@resource:///com/github/Aylur/ags/app.js:283:14
main/<@resource:///com/github/Aylur/ags/main.js:123:21
_load@resource:///com/github/Aylur/ags/app.js:203:29
async*vfunc_activate@resource:///com/github/Aylur/ags/app.js:109:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:4142): Gjs-Console-CRITICAL **: 17:57:23.350: Error: There is no window named greeter
getWindow@resource:///com/github/Aylur/ags/app.js:140:27
ToggleWindow@resource:///com/github/Aylur/ags/app.js:284:24
main/<@resource:///com/github/Aylur/ags/main.js:123:21
_load@resource:///com/github/Aylur/ags/app.js:203:29
async*vfunc_activate@resource:///com/github/Aylur/ags/app.js:109:14
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Sitolam** [comment]
Do these dotfiles even work on nixos?

**Comment by Aylur** [comment]
> (com.github.Aylur.ags:4142): Gjs-Console-CRITICAL **: 17:57:23.349: SyntaxError: JSON.parse: unexpected end of data at line > 1 column 1 of the JSON data
> @file:///tmp/ags/main.js:513:21
> _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

you are still stuck on #214

> Do these dotfiles even work on nixos?

yes, I'm on nixos-unstable [4cba8b5](https://github.com/NixOS/nixpkgs/tree/4c00536dff18e009b94926b4dc220836aae1b708)

**Comment by Sitolam** [comment]
> > (com.github.Aylur.ags:4142): Gjs-Console-CRITICAL **: 17:57:23.349: SyntaxError: JSON.parse: unexpected end of data at line > 1 column 1 of the JSON data
> > @file:///tmp/ags/main.js:513:21
> > _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
> 
> you are still stuck on #214
> 
> > Do these dotfiles even work on nixos?
> 
> yes, I'm on nixos-unstable [4cba8b5](https://github.com/NixOS/nixpkgs/tree/4c00536dff18e009b94926b4dc220836aae1b708)

How did you install your config on nixos?

**Comment by Sitolam** [comment]
I was able to solve the issue. I had forked your repository right before you did a commit with some fixes, I merged the commits and that solved the problem! Thank you for your help and the wonderful project!
