### ISSUE TITLE
Launcher integration with hyprland?

### ISSUE THREAD

**Issue by gro-david** [Aylur/dotfiles#216]
Is there any way to use the Application launcher with the hyprland shortcut?
Or can I just set a Shortcut for it somewhere outside?

**Comment by nine7nine** [comment]
If you are referring to the built-in launcher, that is mentioned on the main Github page:

```
bind=SUPER, R,       exec, ags -t launcher
```

or you can use some other binding... 

If you mean suing some other launcher -- you can set whatever app / binding you want: that's a hyprland.conf thing, not really an AGS thing.

**Comment by gro-david** [comment]
Thank you, I was referring to that but somehow missed it.
