### ISSUE TITLE
[Feature Request] A lock screen

### ISSUE THREAD

**Issue by Sitolam** [Aylur/dotfiles#217]
A lock screen would be amazing, you could also add an idle inhibitor to prevent you from locking your computer accidentally.

**Comment by Aylur** [comment]
I will eventually implement a lock screen once I released ags v2, but its gonna be a long wait
you can do so yourself in the meantime using https://github.com/Cu3PO42/gtk-session-lock

**Comment by nine7nine** [comment]
Depending on ones needs, Hyprlock is also a good option -- I've been using Hyprlock with my Shell for a bit now (added a lockscreen button in Quicksettings too).

@Sitolam - if you are inclined/able to; I do have a patch that shows how to add lockscreen to powermenu / quick settings... But! my Shell has diverged from Aylur's somewhat, so you likely couldn't apply the patch, would need to adapt it to your own needs.

My Hyprlock.conf file also stylizes Hyprlock somewhat do better match the shell/AGS (well, Mine anyway. easy to tweak though)

**Comment by Sitolam** [comment]
> Depending on ones needs, Hyprlock is also a good option -- I've been using Hyprlock with my Shell for a bit now (added a lockscreen button in Quicksettings too).
> 
> @Sitolam - if you are inclined/able to; I do have a patch that shows how to add lockscreen to powermenu / quick settings... But! my Shell has diverged from Aylur's somewhat, so you likely couldn't apply the patch, would need to adapt it to your own needs.
> 
> My Hyprlock.conf file also stylizes Hyprlock somewhat do better match the shell/AGS (well, Mine anyway. easy to tweak though)
> 

Thank you, I will take a look at it!

**Comment by Sitolam** [comment]
> I will eventually implement a lock screen once I released ags v2, but its gonna be a long wait
> you can do so yourself in the meantime using https://github.com/Cu3PO42/gtk-session-lock

I'm looking forward to ags v2!!!
