### ISSUE TITLE
On Arch installation with nix binary

### ISSUE THREAD

**Issue by qbnil** [Aylur/dotfiles#222]
Is there any way i can log in to my hyprland if i installed the nix profile using the nix binary?

**Comment by keilmillerjr** [comment]
You can [launch `Hyprland` from a TTY](https://wiki.hyprland.org/0.18.0beta/Getting-Started/Quick-start/) or use a login manager. I use the arch greetd-tuigreet package.

I do not use nix. I did find [this line referencing gdm](greetd-tuigreet). Maybe  you need to [enable `gdm.service`](https://wiki.archlinux.org/title/GDM)?

**Comment by Aylur** [comment]
launch from a tty, or a login manager, the `asztal` package only contains the ags config and most of its dependencies
