### ISSUE TITLE
Steam Icon

### ISSUE THREAD

**Issue by Draculagibus** [Aylur/dotfiles#224]
I don't know why, the steam icon on the tray icons is working properly, but not on the open applications icon side

And when I put the mouse over a steam menu, it spawn another icon (still not the steam icon)

I launched asztal from the terminal to see what's going on : 
no icon substitute "steam_icon_291550-symbolic" for "steam_icon_291550-symbolic", fallback: "application-x-executable-symbolic"

I'm using nix, and used this to install the ags config
nix profile install github:Aylur/dotfiles

I'm not sure how I should be able to fix this ?

![2024-05-01-122415_hyprshot](https://github.com/Aylur/dotfiles/assets/146088933/3db8b9cd-7eac-4f38-aa1d-370ab6727830)

**Comment by Aylur** [comment]
not sure why it has a number in its class, you can solve this by replacing it in `lib/icons.ts`
