### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by AXWTV** [Aylur/dotfiles#226]
![image](https://github.com/Aylur/dotfiles/assets/88997488/e5c24baa-a116-4318-abf3-8dacf9639b75)
The Vivaldi icon, Vesktop icon and many others aren't loading.
I using Fedora and have NFs and Fonts Awesome.
what should I do?

**Comment by sayhilel** [comment]
Is this an issue only for mono-chrome icons?

**Comment by Aylur** [comment]
these icons come from your icon pack
to change it, you can figure out the class of the client with `hyprctl clients` then replace it in `lib/icons.ts`

**Comment by jabuxas** [comment]
how do i do it if i install with nix?

**Comment by AXWTV** [comment]
> these icons come from your icon pack to change it, you can figure out the class of the client with `hyprctl clients` then replace it in `lib/icons.ts`

![image](https://github.com/Aylur/dotfiles/assets/88997488/8b8d133a-d258-45c3-a075-4145ad18faba)
I still get these paper clips ever after a restart.
What should I do?
