### ISSUE TITLE
Seperate top bar background color

### ISSUE THREAD

**Issue by keilmillerjr** [Aylur/dotfiles#229]
Please separate the top bar background from pop up menus and the settings window. I would like to have my top bar colored black and the rest share a unified theme with my gtk theme.

**Comment by nine7nine** [comment]
Isn't this something you could simply change yourself?

I mean it's one line of code in bar.scss. that's it!

```
.bar {
    background-color: transparentize($bg, 0.1);
 ```
 
 As you can see, in mine: I control tranparency for the background-color... IIRC, Aylur just sets
 
 ```
 .bar {
    background-color: $bg;
 ```
 
 So you could modify that to black( eg: background-color:  #0000000;) 
 
 It seems like an odd request to want someone to change their personal dotfiles for your specific desire / use-case, when this stuff is super simple to modify yourself. no?

**Comment by keilmillerjr** [comment]
It is a public repository. I made a suggestion. It is awesome that people can create their own desktop shell using ags. It is also awesome that the author has made a very clean and operational example that we can use on a day to day basis.

**Comment by keilmillerjr** [comment]
i
