### ISSUE TITLE
how to increse no of work space icons on bar

### ISSUE THREAD

**Issue by vs66388** [Aylur/dotfiles#23]

**Comment by Aylur** [comment]
in `~/.config/eww/scripts/hyprland` there is `NUMBER_OF_WORKSPACES`

**Comment by vs66388** [comment]
> in `~/.config/eww/scripts/hyprland` there is `NUMBER_OF_WORKSPACES`

tnx bro

**Comment by vs66388** [comment]
[screenshot](https://drive.google.com/file/d/1LieVofVSdlOAbqoU8qDbfW485V5uwHip/view?usp=share_link) please tell how to reduce floating gaps if we cannot its fine too

**Comment by Aylur** [comment]
Are you looking for `~/.config/eww/scss/variables.scss` `$wm_gaps`?
