### ISSUE TITLE
QuickSettings: Network-Settings does not work.

### ISSUE THREAD

**Issue by sayhilel** [Aylur/dotfiles#231]
Hey I am unable to fix this (I did try for hours, I swear) but the network settings options in the quick settings just doesn't seem to work.

Error:
```com.github.Aylur.ags:3410): Gjs-Console-CRITICAL **: 19:22:56.361: gtk-launch gnome-control-center gtk-launch: no such application gnome-control-center```

**What I tried**
This seemed pretty straight forward, I just had to install gnome-control-center but here is the catch, the control center only works with gnome
So I though I could just install that and change the env variable but that didn't work.

After digging some more I found the code responsible for this menu

``` Widget.Button({
            on_clicked: () => sh(options.quicksettings.networkSettings.value),
            child: Widget.Box({
                children: [
                    Widget.Icon(icons.ui.settings),
                    Widget.Label("Network"),
                ],
            }),
        }),
```
and this led me to to
 ``` networkSettings: opt("gtk-launch gnome-control-center"),```
where at that point I am out of ideas how and what to change.

**Comment by sayhilel** [comment]
Okay I believe I solved/worked around it. I have no idea what it was supposed to pop up but I saw that gnome-control-center didn't have a .desktop file (makes sens I can't use it on non gnome DEs anyway)

So I just switched that one line to 
``` networkSettings: opt("gtk-launch nm-connection-editor"),```

which I thing makes sense to have there.

**Comment by Aylur** [comment]
thats exactly why thats an option
gnome settings needs `XDG_CURRENT_DESKTOP=gnome` which I set in my hyprland config https://github.com/Aylur/dotfiles/blob/934d3dcc18badbd0030d05f9f09355f62e447280/home-manager/hyprland.nix#L22
