### ISSUE TITLE
failed to build matugen because of material-colors

### ISSUE THREAD

**Issue by Mythic4l** [Aylur/dotfiles#233]
faced the error below when trying to install the dotfiles nix method while i was able to install matugen by my self 
error logs: 
`error: builder for '/nix/store/77hbn36ndcj4kx5bnwp9zjcvk9wlz8w3-matugen-2.2.0.drv' failed with exit code 101;
       last 25 log lines:
       >    Compiling reqwest v0.11.23
       >    Compiling upon v0.8.0
       >    Compiling paris-log v1.0.2
       >    Compiling update-informer v1.1.0
       >    Compiling clap v4.4.11
       >    Compiling material-colors v0.3.2
       > error[E0659]: `core` is ambiguous
       >  --> /build/cargo-vendor-dir/material-colors-0.3.2/src/palette/mod.rs:1:9
       >   |
       > 1 | pub use core::CorePalette;
       >   |         ^^^^ ambiguous name
       >   |
       >   = note: ambiguous because of multiple potential import sources
       >   = note: `core` could refer to a built-in crate
       >   = help: use `::core` to refer to this crate unambiguously
       > note: `core` could also refer to the module defined here
       >  --> /build/cargo-vendor-dir/material-colors-0.3.2/src/palette/mod.rs:4:1
       >   |
       > 4 | mod core;
       >   | ^^^^^^^^^
       >   = help: use `self::core` to refer to this module unambiguously
       >
       > For more information about this error, try `rustc --explain E0659`.
       > error: could not compile `material-colors` (lib) due to previous error
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run 'nix log /nix/store/77hbn36ndcj4kx5bnwp9zjcvk9wlz8w3-matugen-2.2.0.drv'.
error: 1 dependencies of derivation '/nix/store/na9mh10pp2mgh36ly6c8nzf94ilw2x80-asztal.drv' failed to build
error: 1 dependencies of derivation '/nix/store/dr60ap5xv971s7dbrdazzkx878jlcjyx-asztal.drv' failed to build

`

**Comment by EQuioMaX** [comment]
You can clone the repo locally and pin the version for matugen to v2.2.0:
```nix
# in flake.nix
- matugen.url = "github:InioX/matugen";
+ matugen.url = "github:InioX/matugen?ref=v2.2.0";
```

**Comment by Aylur** [comment]
it is/was an issue with matugen, just pin your version if needed
