### ISSUE TITLE
[Bug] Duplicate media controllers when playing in browser after installing plasma-browser-integration

### ISSUE THREAD

**Issue by jin-li** [Aylur/dotfiles#235]
When I play music in the browser (Firefox), there are two media controller in the quick settings window:
![2024-06-14_01-41-09](https://github.com/Aylur/dotfiles/assets/26253144/89a9fd8c-45e6-4a15-85cf-0500f1b1081b)

This happened after I installed the [`plasma-browser-integration`](https://community.kde.org/Plasma/Browser_Integration)(both the browser extension and the pacman package). I installed it because without it, the position slider (including the position and song length) in the media controller will not show.

After I installed `plasma-browser-integration`, two media controllers show up, one with the position slider and the other without.

It seems like the mpris detects the playing media twice but I am not sure. Can anyone help me get rid of the one without position slider?

Here is my system info from `neofetch`:
![2024-06-14_01-32-30](https://github.com/Aylur/dotfiles/assets/26253144/fdcde35f-23a3-4f48-9557-f46ddcb00a6d)

**Comment by Aylur** [comment]
you can get a list of mpris players with something like
```bash
ags -r 'Service.import("mpris").then(({ players }) => players.map(p => p.busName))'
```

then you would need to filter it out in code here https://github.com/Aylur/dotfiles/blob/8e25c14b9f14a8fa7d4160da51b397959a0e4b66/ags/widget/quicksettings/widgets/Media.ts#L152

**Comment by jin-li** [comment]
> you can get a list of mpris players with something like
> 
> ```shell
> ags -r 'Service.import("mpris").then(({ players }) => players.map(p => p.busName))'
> ```
> 
> then you would need to filter it out in code here
> 
> https://github.com/Aylur/dotfiles/blob/8e25c14b9f14a8fa7d4160da51b397959a0e4b66/ags/widget/quicksettings/widgets/Media.ts#L152

Thanks! It works! I can filter out the duplicated player with following code (I use Firefox browser):
```typescript
    children: players.as(p => {
        if (p.some(player => player.busName.includes("plasma-browser-integration"))) {
            return p.filter(player => !player.busName.includes("firefox")).map(Player);
        } else {
            return p.map(Player);
        }
    }),
```
