### ISSUE TITLE
Gnome Control Center Bluetooth Page

### ISSUE THREAD

**Issue by tLJack** [Aylur/dotfiles#237]
I've been working on my own setup based off of your widgest ontop of hyprland.  The bluetooth widget is working for me, but I noticed the blue tooth page in the gnome control center doe not work.  It is just disabled and says "no bluetooth found".  I am just wondering if that page is working for you?

**Comment by jin-li** [comment]
I have the same issue with bluetooth.

**Comment by Aylur** [comment]
it does not, it may need some gnome backend to be enabled I am not sure
I can suggest using cinnamon's blueberry instead
