### ISSUE TITLE
Prevent ags from changing hyprland config values

### ISSUE THREAD

**Issue by xhos** [Aylur/dotfiles#238]
Hi, couldn't find any duplicate issues on this topics, but is there a way to prevent ags from setting it's own window border colors, spacing etc.? I only copied the ags/ folder and got it working within my config, but I am not really experienced with JS so I have no clue where it modifies those values. I manage hyprland with home-manager and have own color schemes defined so it's annoying that ags does that :(

Thanks in advance!

**Comment by nine7nine** [comment]
take a look at: https://github.com/Aylur/dotfiles/blob/main/ags/lib/hyprland.ts

Specifically, you are interested in the function sendBatch() - as that is where all of that stuff is being set when ags starts.

You can just remove anything that you don't want to be set. I did that in my fork/Shell, as I prefer to let Hyprland manage it's own settings / having a clear separation of concerns between hyprland && ags.

**Comment by xhos** [comment]
> take a look at: [`main`/ags/lib/hyprland.ts](https://github.com/Aylur/dotfiles/blob/main/ags/lib/hyprland.ts?rgh-link-date=2024-06-20T21%3A12%3A08Z)
> 
> Specifically, you are interested in the function sendBatch() - as that is where all of that stuff is being set when ags starts.
> 
> You can just remove anything that you don't want to be set. I did that in my fork/Shell, as I prefer to let Hyprland manage it's own settings / having a clear separation of concerns between hyprland && ags.

Exactly what I needed, thank you!
