### ISSUE TITLE
Enable/Disable greetd

### ISSUE THREAD

**Issue by Chemchu** [Aylur/dotfiles#239]
Hello! 

I've been playing around with this config and I really like how beautiful and functional it is. I've been messing with the configuration and I would like to disable the greetd service. I tried everything I could but every time I rebuild and reboot, lightdm appears to greet me again.

Any idea what I can do? I just want to disable the display manager, boot directly into my tty and launch Hyprland manually.

Thanks!

**Comment by Aylur** [comment]
I set greeters here
https://github.com/Aylur/dotfiles/blob/8e25c14b9f14a8fa7d4160da51b397959a0e4b66/nixos/hyprland.nix#L97-L130
