### ISSUE TITLE
"SUPER + j" does two things in hypr/binds.conf

### ISSUE THREAD

**Issue by MZH-Amr** [Aylur/dotfiles#24]
Hi, this is the first time for me to make an issue on GitHub, so if there is anything I need to do differently, please tell me.

In `.config/hypr/binds.conf`, there are these two lines
`bind = SUPER, J, togglesplit`
and
`bind = SUPER, j, movefocus, d`
both lines have the same bind but do different things, thanks

Can you help with a problem I'm facing with fonts in Eww? Even though I have set `font-family` to `'Hack Nerd Font'` and `$mono_font` to `'Hack Nerd Font Mono'` in `.config/eww/scss/variables.scss` (fc-match recognizes both fonts), some icons are being displayed as `null`, sorry if this is not the right place to ask this question and thanks again. Have a good day.

**Comment by thyeun** [comment]
@MZH-Amr You might miss out some of the dependency and you can check out the error by using ```gjs -m ~/.config/eww/scripts/myshell/./myshell --eww --file``` in the terminal. Will list out some of your error.

**Comment by Aylur** [comment]
The null means that some scripts haven't run yet. If restarting with `~/.config/eww/scripts/init` doesn't help that means you have some dependency missing.

**Comment by Aylur** [comment]
Also thanks for letting me know the hyprland config issue. I rarely use that keybinding and have not noticed yet.
