### ISSUE TITLE
Taskbar fix

### ISSUE THREAD

**Issue by dzuberi** [Aylur/dotfiles#240]
I tried out your config and noticed your taskbar doesn't change when windows are closed/opened in hyprland. I've changed  line 75 of Taskbar.ts to 

```ts
    children: hyprland.bind("clients").as(clients => sortItems(clients.map(c => AppItem(c.address)))),
```

**Comment by dianaw353** [comment]
I do have that issue where sometimes the taskbar dosent change windows and this appears to fix it, thank you
