### ISSUE TITLE
Current workspace indicator sometimes shows incorrect workspace

### ISSUE THREAD

**Issue by mechakotik** [Aylur/dotfiles#241]
When changing workspace, current workspace indicator not always shifts to new workspace. It only happens when you switch from / to occupied workspace, it always works when switching between two empty workspaces. Hyprland 0.39.1 (also tested with 0.41.1), AGS 1.8.2.

**Comment by lucasile** [comment]
Had this issue for a while rocking Fedora. Checked out their discord and asked for help and found out its likely a Fedora-Hyprland issue. Share any errors you get when this happens.

**Comment by lucasile** [comment]
Yup same exact issue. 

This is the conclusion that we found out.
<img width="765" alt="image" src="https://github.com/Aylur/dotfiles/assets/24704654/fe2a2586-8999-418c-baa7-29d3e2de0c48">

I wasn't able to find a fix to it after a lot of debugging, but I was able to apply a disgusting solution where I try updating all the workspaces on every Hyprland event... that way there's a very small chance that this issue occurs. If you find a solution please let me know :)

Something like this in Workspaces.ts
```Typescript
setup: (box) => {
      // this is very bad but it works around this stupid resource temporarily unavailable bug
      box.hook(Hyprland, () => {
        const activeId = JSON.parse(Hyprland.message("j/monitors"))[0]
          .activeWorkspace.id;

        box.children.map((btn) => {
          btn.toggleClassName("active", btn.attribute === activeId);

          if (ws === 0) {
            btn.visible = Hyprland.workspaces.some(
              (ws) => ws.id === btn.attribute,
            );
          }
        });
      });
    },
```
