### ISSUE TITLE
How to resize a PopupWindow to the screen it is toggled on?

### ISSUE THREAD

**Issue by saipavanc** [Aylur/dotfiles#245]
I am using the `PopupWindow` as defined in your dotfiles, and when I open the window on two monitors the size of the window remains the same as the first monitor on which it was launched. Is it possible to automatically resize it according to the monitor on which it is called?

**Comment by Aylur** [comment]
There are multiple factors that will decide its a widgets size
you could add a className to depending on monitor, then target it with css and set sizes, font-sizes, anything you need
