### ISSUE TITLE
Icons missing in the status bar

### ISSUE THREAD

**Issue by miyoku157** [Aylur/dotfiles#247]
Hi,
I try to make the bar work. And for the most of it, it is. But i don't understand how the icons are handle in Ags. ags always throw errors:
`Error: can't assign "application-x-executable-symbolic" as icon, it is not a file nor a named icon`
And as i am on nixos with Hyprland, i don't have any x server enabled (other than Xwayland). Maybe it impact this?
Do i have to put every icon i need in the asset folder and use them as substitute?

Some other icons are missing like bluetooth, wifi?

That's what i have:
![2024-07-21_16-04-13](https://github.com/user-attachments/assets/ccb38107-d420-46ef-986b-657dd64df14c)

Your bar is really awesome, i just don't understand what i have to do to configure the icons.

**Comment by Aylur** [comment]
Icon themes are independent of xorg and wayland
You seem to have no icon themes installed on your system, I can recommend adwaita
