### ISSUE TITLE
bun: error while loading shared libraries

### ISSUE THREAD

**Issue by NotJoeMama727** [Aylur/dotfiles#248]
Hi all, love how this looks, but whenever I go to do the `ags` command, I get `bun: error while loading shared libraries: /home/me/.cache/yay/bun/src/bun/build/bun-deps/libtcc.a: cannot open shared object file: No such file or directory`
did I do something wrong? Help would be enormously appreciated

**Comment by Aylur** [comment]
install esbuild and try running with `AGS_BUNDLER=esbuild ags`

**Comment by NotJoeMama727** [comment]
nevermind, I solved it
