### ISSUE TITLE
ERROR AGS

### ISSUE THREAD

**Issue by dyba404** [Aylur/dotfiles#249]
error loading ags

[faraday@hack4u ~]$ ags

(com.github.Aylur.ags:10595): Gjs-Console-CRITICAL **: 19:26:04.834: net.hadess.PowerProfiles is not available
no icon substitute "search" for "search", fallback: "application-x-executable"
no icon substitute "search" for "search", fallback: "application-x-executable"

(com.github.Aylur.ags:10595): Gjs-Console-WARNING **: 19:26:05.204: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:10595): Gjs-Console-WARNING **: 19:26:05.204: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:10595): Gjs-Console-WARNING **: 19:26:05.205: Error: can't assign "org.gnome.Settings-notifications-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:10595): Gjs-Console-WARNING **: 19:26:05.225: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:10595): Gjs-CRITICAL **: 19:26:05.225: JS ERROR: Error: Wrong type undefined; string expected
_size@resource:///com/github/Aylur/ags/widgets/icon.js:70:13
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:55:14
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

**Comment by Aylur** [comment]
> (com.github.Aylur.ags:10595): Gjs-Console-CRITICAL **: 19:26:04.834: net.hadess.PowerProfiles is not available

missing upowerd

missing pixbufs are usually from tray items
you can set substitutes for the named icons in `lib/icons.ts`
