### ISSUE TITLE
systray 

### ISSUE THREAD

**Issue by vs66388** [Aylur/dotfiles#25]
cn you please add a systemtray like i mean for background running app tiny icon tray its a featur req but i didnt know how to get it that way

**Comment by Aylur** [comment]
There is a PR for Eww that I am waiting for. I don't want to implement this myself

**Comment by vs66388** [comment]
> There is a PR for Eww that I am waiting for. I don't want to implement this myself

ok is thier any other and and 1more issue how to get weather working in calaneder bottom

**Comment by Aylur** [comment]
You need an API key for [OpenWeather](https://openweathermap.org)

**Comment by vs66388** [comment]
i got api key how to add it
