### ISSUE TITLE
Wi-Fi selector list on waybar menu not responding to clicks

### ISSUE THREAD

**Issue by caniko** [Aylur/dotfiles#250]
When I want to connect to a wireless network using the waybar menu, selecting SSID is non-responsive. Meaning, the UI component right before prompting for router security password is faulty.

I am on the Asus G14 GA402XY.

**Comment by Aylur** [comment]
There is no waybar nor waybar menu, I assume you mean the network toggle in the quicksettings, which currently only supports connecting to networks that you are already authorized with, if you need to give password use another tool tile nmcli

**Comment by caniko** [comment]
I have seen the code, this is the intended workflow. How about adding Zenity support?

Also, did you write all this yourself? Very impressive 😄

**Comment by Aylur** [comment]
> How about adding Zenity support?

There is no need for zenity, the ui would be made with same thing as the rest of the shell. The issue is that the networkmanager code does not handle passwords yet.

> Also, did you write all this yourself?

got interested in it, then coding went brr
