### ISSUE TITLE
Is the ags setting widget draggable?

### ISSUE THREAD

**Issue by ItsTerm1n4l** [Aylur/dotfiles#251]
Is the ags setting widget draggable - movable with the mouse not stuck in a fixed position? and if not is there any way to do this with ags?

**Comment by Daemonical** [comment]
In the hyprland config you can set a toggle floating key bind
`bind = SUPER, F, togglefloating`
or you can target the settings window with a window rule if you want this as default
`windowrulev2 = float, class:(com.github.Aylur.ags), title:(Settings)`

**Comment by ItsTerm1n4l** [comment]
Thank you, I have installed Aylur's dotfiles and I can see how it works now, now I just have to figure out how to use it to create my own window
Thanks!
