### ISSUE TITLE
Theme selector not showing.

### ISSUE THREAD

**Issue by plasmoduck** [Aylur/dotfiles#253]
How do I get the theme selector button and menu to change themes like you showcased in your first original r/unixporn post? 
Mine just looks like this.
![2024-08-06_03-21-20](https://github.com/user-attachments/assets/240938fc-9ddb-4b4a-ba87-4450a48695e1)

**Comment by Aylur** [comment]
that post showcased [this config](https://github.com/Aylur/dotfiles/tree/ags-pre-ts)

**Comment by plasmoduck** [comment]
Thanks for getting back to me so fast. How can I just add the theme selector to the latest config?

**Comment by Aylur** [comment]
you would have to implement it yourself, when I ported over to ts, I didn't port this feature as I never used it
