### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by Jxulian1** [Aylur/dotfiles#254]
hi I'm new to using linux so please forgive me for any stupid questions. when I run ags I get this error I have install of the packages can anyone help thanks

(com.github.Aylur.ags:2647): Gjs-Console-CRITICAL **: 06:54:34.238: net.hadess.PowerProfiles is not available

(com.github.Aylur.ags:2647): Gjs-Console-CRITICAL **: 06:54:34.659: asusctl profile -p thread 'main' panicked at asusctl/src/main.rs:62:54:
called `Result::unwrap()` on an `Err` value: MethodError(OwnedErrorName("org.freedesktop.DBus.Error.ServiceUnknown"), Some("The name is not activatable"), Msg { type: Error, serial: 4294967295, sender: UniqueName("org.freedesktop.DBus"), reply-serial: 5, body: Signature("s"), fds: [] })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

(com.github.Aylur.ags:2647): Gjs-Console-WARNING **: 06:54:34.753: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:2647): Gjs-CRITICAL **: 06:54:34.753: JS ERROR: Error: Wrong type undefined; string expected
set label@resource:///com/github/Aylur/ags/widgets/label.js:51:9
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

(com.github.Aylur.ags:2647): Gjs-Console-WARNING **: 06:54:34.753: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:2647): Gjs-Console-WARNING **: 06:54:34.754: Error: can't assign "org.gnome.Settings-notifications-symbolic" as icon, it is not a file nor a named icon
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:45:30
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  
no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

(com.github.Aylur.ags:2647): Gjs-Console-WARNING **: 06:54:34.770: Error: expected Pixbuf or string for icon, but got undefined
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:53:26
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:2647): Gjs-CRITICAL **: 06:54:34.771: JS ERROR: Error: Wrong type undefined; string expected
_size@resource:///com/github/Aylur/ags/widgets/icon.js:70:13
set icon@resource:///com/github/Aylur/ags/widgets/icon.js:55:14
bind/callback<@resource:///com/github/Aylur/ags/widgets/widget.js:53:30
hook/<@resource:///com/github/Aylur/ags/widgets/widget.js:43:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

no icon substitute "kitty-symbolic" for "kitty-symbolic", fallback: "application-x-executable-symbolic"

**Comment by Aylur** [comment]
error about missing upowerd/asusd install either of them, or disable widgets that use these

and warnings about missing icons, either add icons in the assets directory, or specify a substitute in `lib/icons.ts`
