### ISSUE TITLE
Theme Parsing error

### ISSUE THREAD

**Issue by EliasTheGrandMasterOfMistakes** [Aylur/dotfiles#255]
(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:102:44: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:104:60: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:105:62: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:108:45: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:109:55: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:111:55: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:112:57: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:113:56: Expected a valid selector

(com.github.Aylur.ags:51118): Gtk-WARNING **: 00:55:46.517: Theme parsing error: gtk.css:114:58: Expected a valid selector

**Comment by Aylur** [comment]
Its from your gtk theme
either ignore those, or make sure adwaita is installed and specify `gtkTheme` in main.ts like this
```js
App.config({
    gtkTheme: "Adwaita",
    // ...
})

```
