### ISSUE TITLE
After installing with Nix, what to do with old hyprland dotfiles

### ISSUE THREAD

**Issue by ShubhankarBalel** [Aylur/dotfiles#256]
I followed the guide with Nix and everything works now but it's running on top of my old configuration. Like my old hyprland configs and waybar and stuff. What do I replace those dotfiles with?

**Comment by Aylur** [comment]
I am unsure what you are asking here, just don't run waybar?

**Comment by ShubhankarBalel** [comment]
Should I have anything except for the keybinds in my hyprland.conf file?

**Comment by Aylur** [comment]
and whatever else you want
ags will override some values you can find in `lib/hyprland.ts`, you can remove any of those if you don't want it to override them
