### ISSUE TITLE
Powermenu icons not showing up?

### ISSUE THREAD

**Issue by JustEvanB** [Aylur/dotfiles#26]
as said above, it just doesn't show, i tried changing some code around to give the absolute path to the images but it just doesn't load, even before I changed anything. I reinstalled it again just now and it still wont show.

![2023-06-06-091438_hyprshot](https://github.com/Aylur/dotfiles/assets/118784142/ea2bf26c-9d89-4632-9352-6d6db089ee3c)

**Comment by thyeun** [comment]
@JustEvanB If others are showing up, it should work fine for the powermenu. Try investigate what goes wrong.

**Comment by Aylur** [comment]
are there any errors on `eww logs`?
