### ISSUE TITLE
Disable the taskbar

### ISSUE THREAD

**Issue by plasmoduck** [Aylur/dotfiles#262]
How can I disable the taskbar all together?

**Comment by plasmoduck** [comment]
Please it is talking over my bar with so many icons and I don't even use it.

![2024-08-26_22-56-15](https://github.com/user-attachments/assets/f3c95299-d003-4c5a-a61b-99ef23821768)

**Comment by Aylur** [comment]
remove it https://github.com/Aylur/dotfiles/blob/18b83b2d2c6ef2b9045edefe49a66959f93b358a/ags/options.ts#L74
