### ISSUE TITLE
second window opened by app launcher does not get focused

### ISSUE THREAD

**Issue by BluewyDiamond** [Aylur/dotfiles#264]
When opening a second application using the app launcher for some reason the second application won't get focused.

I tried using the bash function in utils when clicking on a button widget to manually open a window/app and it seems by doing it like this the new window/app will get focused correctly, so im not sure what the launcher is doing differently.

**Comment by Aylur** [comment]
I think this is a compositor settings issue

**Comment by Aylur** [comment]
what version of hyprland are you on? iirc this was a bug in hyprland

**Comment by BluewyDiamond** [comment]
im on latest commit of hyprland-git
