### ISSUE TITLE
System monitor

### ISSUE THREAD

**Issue by plasmoduck** [Aylur/dotfiles#265]
How do I get system info widgets like load, temperature and drive below the calendar like I seen in some of your older configs like [this](https://private-user-images.githubusercontent.com/113519679/290872784-577bc981-6a1a-4fd3-acad-e8132aa36b24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MzE4NjEsIm5iZiI6MTcyNDkzMTU2MSwicGF0aCI6Ii8xMTM1MTk2NzkvMjkwODcyNzg0LTU3N2JjOTgxLTZhMWEtNGZkMy1hY2FkLWU4MTMyYWEzNmIyNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQxMTM5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hN2FlYzVkZjY3MDA1ODYyOTQ2Y2ZlNmJmN2U4YTNhYzQ0MzhlNWE1ZjVjYjJmYjlmMDY0YTU1ODc0YjQ1OTBhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pzwnv5utViIwMEGpT7G9VvumYuo9DsZZcG3Lbue2_Nk)

P.S -
A patch would  be very handy and much appreciated :)

**Comment by Aylur** [comment]
You could just look for it and copy it you know

https://github.com/Aylur/dotfiles/blob/7c4d6a708d426cb1a35a0f1776c4edc52ae1841c/ags/js/dashboard/DateColumn.js#L7-L25
https://github.com/Aylur/dotfiles/blob/7c4d6a708d426cb1a35a0f1776c4edc52ae1841c/ags/js/variables.js#L38-L59

someone mentioned on discord that this is not actually the correct way to read cpu, you might have to fix that

**Comment by plasmoduck** [comment]
Sorry I didn't know what lineś to copy and where to put it.
