### ISSUE TITLE
[Question] Gnome or hyprland

### ISSUE THREAD

**Issue by noahfraiture** [Aylur/dotfiles#272]
Hello,

I see that there's a lot of gnome configuration despite you are using hyprland. Is it simply that they don't do anything, or are still meaning full ? For instance dconf is very big, I understand that there's some gnome application even for hyprland but there seem to be more than that, like configuration for the desktop. 
I'm trying to use part of your dotfiles but I'm afraid of having lot of troubles if I start to mess with these without fully understand what is happening

**Comment by Aylur** [comment]
I have a gnome configuration I use in some rare cases which is in the form of a specialisation. Gnome related configs such as dconf are not used in the hyprland setup
