### ISSUE TITLE
How to Autostart ags and How to Use Workspace switcher

### ISSUE THREAD

**Issue by demonspork** [Aylur/dotfiles#274]
I have everything working, great work! How do you autostart it? The only way I can get it working is to run `ags` in a terminal after starting Hyprland. 

So far I have tried exec-once in the hyprland config with both ags directly and by executing a shell script that prefixes it with "sleep 5" in case the issue was it trying to start too quickly. But nothing happens until I interactively launch ags from a shell.

Second: The workspace switcher, am I missing something or is it just a button, is there any way to use it? Like maybe mouse-wheel scrolling while hovering to switch workspaces would be pretty slick.

**Comment by demonspork** [comment]
Ok, further information. I was starting hyprland with sddm. If I start it from a tty the exec-once = ags works correctly to load that. Anyone have any ideas what to change to get it to load properly when hyprland is launched from sddm?

**Comment by YoungSusanoo** [comment]
If you mean how to switch workspaces check hyprland wiki. It's keybinding issue not ags. 
And about first: it's hard to know that is problem without seeing your config file

**Comment by blacklightpy** [comment]
> Second: The workspace switcher, am I missing something or is it just a button, is there any way to use it? Like maybe mouse-wheel scrolling while hovering to switch workspaces would be pretty slick.

This set of keybinds will add it. It is also available in the sample configuration at `/usr/share/hyprland.conf`.

If you don't know, you have to move the config files to `/etc/hypr/hyprland.conf` for system-wide configuration and/or to `~/.config/hypr/hyprland.conf` for user-specific configurations.

```
# Move focus with mainMod + arrow keys
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# Scroll through existing workspaces with mainMod + scroll
bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1
```

**Comment by etgcloudvoicesupport** [comment]
Yeah, I have keybinds, but I'm mostly referring to the switcher on the bar. It doesn't seem to do anything but display some dots that hilights the current workspace/live workspaces and when clicked, brings up a visual workspace switcher. Useful features would be things like scrolling the mouse wheel over it would switch workspaces, re-binding of which switcher comes up (may be able to figure that out with some digging).

My biggest issue is still that ags won't start via exec-once if I started Hyprland via sddm. The only way ags will auto start is if I start up multi-user instead of graphical, and launch Hyprland after logging in, like there is somethign missing from the environment but my Hyprland environment seems pretty complete.

**Comment by demonspork** [comment]
Yeah, I have keybinds, but I'm mostly referring to the switcher on the bar. It doesn't seem to do anything but display some dots that hilights the current workspace/live workspaces and when clicked, brings up a visual workspace switcher. Useful features would be things like scrolling the mouse wheel over it would switch workspaces, re-binding of which switcher comes up (may be able to figure that out with some digging).

My biggest issue is still that ags won't start via exec-once if I started Hyprland via sddm. The only way ags will auto start is if I start up multi-user instead of graphical, and launch Hyprland after logging in, like there is somethign missing from the environment but my Hyprland environment seems pretty complete.

**Comment by blacklightpy** [comment]
> Useful features would be things like scrolling the mouse wheel over it would switch workspaces, re-binding of which switcher comes up (may be able to figure that out with some digging).

That doesn't exist, but you can use tab. I don't know what's wrong with SDDM. For me it works both ways, and I had to append the `dbus-run-session` to the `Exec` key in `/usr/share/wayland-sessions/Hyprland.desktop` so that apps launched from it have access to the D-Bus session. But AGS would start regardless of that.

**Comment by demonspork** [comment]
Yeah, it is very strange. if hyprland is started by sddm ags can't be started by Hyperland. even if i do hyprctl dispatch exec ags

I'll get some logs soon. On Fedora 41 if that matters.
