### ISSUE TITLE
Sending messages to hyprland slows down it

### ISSUE THREAD

**Issue by YoungSusanoo** [Aylur/dotfiles#276]
Finded out that
` return messageAsync(`[[BATCH]]/${cmd}`)`
_in /lib/hyprland.ts/_
drops framerate. But when I exec directly `hyprctl <args> ` using `Utils.execAsync` it works fine
I'm not sure but I think I have seen similar behaviour with another ags configs. But I don't know what function slowed them

**Comment by viraj-s15** [comment]
Can confirm, doing this fixed the issue.
