### ISSUE TITLE
null issue on fedora 

### ISSUE THREAD

**Issue by vs66388** [Aylur/dotfiles#28]
icon between dark and light mode switcher and bluetooth is missing 3 from right and 4 th from left side how can i fix it

**Comment by thyeun** [comment]
@vs66388 can you show your screenshot? it is hard to understand which icon you are missing it. 
Below is the full set of icon for ```notification center```.
![Screenshot_2023-05-26-22-25-26_31694](https://github.com/Aylur/dotfiles/assets/1939446/b6560a97-928e-424a-bd13-1cdb09e00e74)

**Comment by vs66388** [comment]
i dont mean notification center i mean the icon with arrow pointing downwords

**Comment by Aylur** [comment]
That is [asusctl](https://gitlab.com/asus-linux/asusctl). If you don't use an Asus laptop, you should just remove that widget. You can do so in `~/.config/eww/yuck/windows/noti_center.yuck`

**Comment by thyeun** [comment]
@vs66388 Original icon is for ```Asus ROG``` power status, i change it to ```Package check update```. And why cant you share out your screenshot, is more easy for us to understand what is your facing issue. 

Really dont understand it is so hard to share out your screenshot?

**Comment by vs66388** [comment]
> @vs66388 Original icon is for ```Asus ROG``` power status, i change it to ```Package check update```. And why cant you share out your screenshot, is more easy for us to understand what is your facing issue. 
> 
> Really dont understand it is so hard to share out your screenshot?

Thanks for that sir can you tell me how to do that
