### ISSUE TITLE
Trying to use greeter on Gentoo

### ISSUE THREAD

**Issue by sheikh1233** [Aylur/dotfiles#281]
Hello, I am running your Hyprland dotfiles on Gentoo, and I want to use the greeter that you made on greetd. However, I can't figure out how to do it. If you can explain how to run your greeter it would be appreciated

**Comment by Shentxt** [comment]
I managed to run it, although my problem was that when I started my hyprland session it immediately kicked me out

I did this:
config.toml
`command = "Hyprland --config /etc/greetd/hyprland.conf"`

I then created greeter.js and hyplrand.conf
`exec-once = ags --config /etc/greetd/greeter.js; hyprctl dispatch exit`

```
const greetd = await Service.import('greetd');

const name = Widget.Entry({
 placeholder_text: 'Username',
 on_accept: () => password.grab_focus(),
})

const password = Widget.Entry({
 placeholder_text: 'Password',
 visibility: false,
 on_accept: () => {
 greetd.login(name.text || '', password.text || '', 'Hyprland')
 .catch(err => response.label = JSON.stringify(err))
 },
})

const response = Widget.Label()

const win = Widget.Window({
 css: 'background-color: transparent;',
 anchor: ['top', 'left', 'right', 'bottom'],
 keymode: 'exclusive',
 child: Widget.Box({
 vertical: true,
 hpack: 'center',
 vpack: 'center',
 hexpand: true,
 vexpand: true,
 children: [
 yam,
 password,
 response,
 ],
 }),
})

App.config({ windows: [win] })
```

**Comment by sheikh1233** [comment]
> I managed to run it, although my problem was that when I started my hyprland session it immediately kicked me out
> 
> I did this: config.toml `command = "Hyprland --config /etc/greetd/hyprland.conf"`
> 
> I then created greeter.js and hyplrand.conf `exec-once = ags --config /etc/greetd/greeter.js; hyprctl dispatch exit`
> 
> ```
> const greetd = await Service.import('greetd');
> 
> const name = Widget.Entry({
>  placeholder_text: 'Username',
>  on_accept: () => password.grab_focus(),
> })
> 
> const password = Widget.Entry({
>  placeholder_text: 'Password',
>  visibility: false,
>  on_accept: () => {
>  greetd.login(name.text || '', password.text || '', 'Hyprland')
>  .catch(err => response.label = JSON.stringify(err))
>  },
> })
> 
> const response = Widget.Label()
> 
> const win = Widget.Window({
>  css: 'background-color: transparent;',
>  anchor: ['top', 'left', 'right', 'bottom'],
>  keymode: 'exclusive',
>  child: Widget.Box({
>  vertical: true,
>  hpack: 'center',
>  vpack: 'center',
>  hexpand: true,
>  vexpand: true,
>  children: [
>  yam,
>  password,
>  response,
>  ],
>  }),
> })
> 
> App.config({ windows: [win] })
> ```

Did you switch your display manager to greetd in `/etc/conf.d/display-manager?`

**Comment by sheikh1233** [comment]
I managed to get the greeter working by copying `.config/ags/greeter` to `/etc/greetd/ags/greeter`, then copying greeter.js to '/etc/greetd', then changing `const entry` in greeter.js to be equal to `/etc/greetd/ags/greeter/greeter.ts`. This made the greeter launch and get me into Hyprland, but it doesn't launch it with dbus-launch, and I can tell this because my spotify doesn't open unless I open it with dbus-launch.
