### ISSUE TITLE
Battery Icon

### ISSUE THREAD

**Issue by Notezi** [Aylur/dotfiles#29]
When I am utilizing your config , everything works perfectly but the battery icon shows up weird . It shows an icon like I am missing a font.

I have the nerd variants of rhe Ubuntu font and monoki font enabled .

Is there a font that I am missing ?

OS: Arch Linux

**Comment by thyeun** [comment]
@Notezi Can you show your screenshot? both battery icon should look like the below image.
![Screenshot_2023-05-26-22-24-47_21381](https://github.com/Aylur/dotfiles/assets/1939446/887bd104-7eeb-4d8d-9da5-9e72eed77f1e)

**Comment by Aylur** [comment]
I also have this issue after updating nerdfonts from nixpkgs.

**Comment by Notezi** [comment]
So I installed font awesome thinking that's what it was but now my battery icon is a globe icon and the left icon is the hieroglyphic icon you get when you have a missing font.

Not inky that the icon next to the crescent moon is just an empty space

**Comment by thyeun** [comment]
@Notezi that icon is ```Asus ROG``` if you not using it, you can hide it or change it like my to ```Package update check```.

**Comment by Notezi** [comment]
@thyeun  Which one of the icons are you referring to?

**Comment by thyeun** [comment]
@Notezi As below images
![Screenshot_2023-05-26-22-25-26_31694](https://github.com/Aylur/dotfiles/assets/1939446/e915ed69-d1f4-40bb-a660-b02e6f7ecb87)

**Comment by Notezi** [comment]
@thyeun I understand about the icon next to the crescent moon but why is the battery icon showing gibberish ?

**Comment by thyeun** [comment]
When it empty, same look like the one in old model handphone

**Comment by thyeun** [comment]
charging look in green as below image
![Screenshot_2023-06-09-19-25-44_2948](https://github.com/Aylur/dotfiles/assets/1939446/049f1a2f-b8c8-4dac-87f1-2d03df42c229)

**Comment by Notezi** [comment]
![Uploading IMG_20230609_072616_389.jpg…]()

This is my screen and what is being shown

**Comment by Notezi** [comment]
@thyeun No I am saying the icon is present but looks like the icon you get when there is missing font. A box with letters. Tried to upload image but it is not showing

**Comment by Notezi** [comment]
![IMG_20230609_072616_389](https://github.com/Aylur/dotfiles/assets/92166027/3d33204b-c487-498f-a5e2-da10906dad10)

Here is what I am talking about

**Comment by thyeun** [comment]
That icon is not missing, it is the icon as i mentioned from my previous comment, it is icon for Asus ROG, and what you see from my images, i change it to package update check, because im not using ASUS laptop, try read back my previous comment

**Comment by Notezi** [comment]
@thyeun I understand that part already. I am talking about the battery icon under the WiFi icon. From my screenshot, you can see that something is wrong with it

**Comment by thyeun** [comment]
🤭🤭🤭 sorry my mistake, that icon should be no issue, it is under ubuntu nerd font.

**Comment by Notezi** [comment]
@thyeun I have that installed but it is still not showing up?

**Comment by thyeun** [comment]
Which version nerd font you install? Latest version might give you alot of font issue, im using nerd font v2.3 from aur

**Comment by Notezi** [comment]
I am using the latest , and there is no other version I see on the aur. Can you post a link?

**Comment by thyeun** [comment]
https://aur.archlinux.org/packages/nerd-fonts-complete-starship here you go.

**Comment by Notezi** [comment]
@thyeun Thank you for helping me solve the issue
