### ISSUE TITLE
network icon

### ISSUE THREAD

**Issue by FR13NXD** [Aylur/dotfiles#30]
![image](https://github.com/Aylur/dotfiles/assets/127687150/09215cc2-6f71-4e77-92ab-d0e2d47614f2)
network icon show up disconnected after i connect to vpn (riseup vpn)

**Comment by thyeun** [comment]
@FR13NXD you can create one extra code inside yuck & scss to trigger ```VPN``` with another icon. Just a simple code. You can done it. =.=

**Comment by Aylur** [comment]
The code you might want to edit is `.config/eww/scripts/myshell/network.js`. I don't use a vpn though, can't help you with that.
