### ISSUE TITLE
FI Media Player

### ISSUE THREAD

**Issue by Notezi** [Aylur/dotfiles#31]
I had searched the issues about this and CME upon a comment that stated that it can be fixes in the main.js file but I have searched that file and cannot find the FI that is being referred to

**Comment by FR13NXD** [comment]
why is there a fj

**Comment by thyeun** [comment]
@Notezi You can find it, it is in the line 18 ```'deafult': '',``` replace that music icon from the nerd font cheatsheet, this one is codepoint error from nerd font, i already issue it to nerd font but they cant make change on it.

**Comment by Notezi** [comment]
@thyeun It is solved now. Thank you
