### ISSUE TITLE
unknown widget "small_toggle_bt"

### ISSUE THREAD

**Issue by FR13NXD** [Aylur/dotfiles#35]
![image](https://github.com/Aylur/dotfiles/assets/127687150/89ebdd3e-6cf9-41a1-b890-22381624d46f)

**Comment by FR13NXD** [comment]
![image](https://github.com/Aylur/dotfiles/assets/127687150/ad4c1ff3-7422-4d0f-9f8b-27fc70071391)
another error

**Comment by thyeun** [comment]
it is not related with this dotfile. check your setting on your hyprland. something that you trigger twice
