### ISSUE TITLE
Weather Widget

### ISSUE THREAD

**Issue by Notezi** [Aylur/dotfiles#37]
I have questions about the weather widget. Following the script, I created an API key but I am still unable to pull weather details. Is there anything else I have to do to pull the weather?

**Comment by Notezi** [comment]
So I am able to pull weather details now, is there a way to pinpoint specific cities?

**Comment by Aylur** [comment]
on [openweathermap.org](https://openweathermap.org/) search for a city then copy the digits from the url

**Comment by Notezi** [comment]
Thank you Aylur, was able to figure it out
