### ISSUE TITLE
Remove the buttons And Change the wallpaper

### ISSUE THREAD

**Issue by Fufu-S** [Aylur/dotfiles#41]
I'm using the eww branch and I'm using desktop. So the first question, how do I remove the buttons for the battery and brightness adjustment, and the last question, how do I change the wallpaper.

**Comment by Fufu-S** [comment]
My neofetch
![Screenshot_20230709_205219](https://github.com/Aylur/dotfiles/assets/43800368/a6b97c44-29e9-428f-a91e-1d57e433499e)

**Comment by Aylur** [comment]
you need to edit the yuck files and comment out or delete whatever you don't need

**Comment by Fufu-S** [comment]
> you need to edit the yuck files and comment out or delete whatever you don't need

how do I change the wallpaper?
