### ISSUE TITLE
No Window Gaps On Left [EWW]

### ISSUE THREAD

**Issue by SharpStormGames** [Aylur/dotfiles#43]
Today, i switched from the Left Bar to the Top Bar on the EWW version of the dotfiles, and there is no gaps between my windows and the left side of the screen, and there is a bigger gap then default between the Top bar and the top of the window, is there a way to fix this?

**Comment by SharpStormGames** [comment]
Solved, missed something in Hyprland configs

**Comment by kaibagley** [comment]
Can you please comment what exactly it was you changed? Having a similar problem and can't find the setting

**Comment by SharpStormGames** [comment]
https://wiki.hyprland.org/Configuring/Monitors/#custom-reserved-area

Set LEFT to 0 in Hyprland config file

**Comment by kaibagley** [comment]
Thanks for the info!
