### ISSUE TITLE
How the dock pin application sorted?

### ISSUE THREAD

**Issue by thyeun** [Aylur/dotfiles#45]
If i change the dock pin application to ```thunar```, i cant get it done, because it will automatically pin ```bulk rename```

Reason is, when i search ```thunar```, ```bulk rename``` will be the first one, then dock pin ```thunar``` will automatically pin to ```bulk rename```. As you can see from the below images

![Screenshot_2023-07-26-15-10-22_21486](https://github.com/Aylur/dotfiles/assets/1939446/25294b4d-6543-41a2-84b3-cd86bf5d5e2c)

![Screenshot_2023-07-26-15-16-55_7616](https://github.com/Aylur/dotfiles/assets/1939446/7bce1879-6b2d-4fb2-bbe3-ac191b293d3b)

**Comment by thyeun** [comment]
if i using ```thunar file manager``` it will automatically jump into ```file manager setting```, it still wont go to ```thunar```.

i been trying it a few time, and i even rename ```bulk rename``` and ```file manager setting```. and also i edit the .desktop file too.

But still cant make it work. if there are no way to done it, i will put ```ranger``` instead of ```thunar``` on dock pin =.=

**Comment by Aylur** [comment]
try `browse the filesystem`, it also tries to match descriptions

**Comment by thyeun** [comment]
Ok, understand. and it working now
