### ISSUE TITLE
Is that an alternative way to remove asusctl and replace with others executable application?

### ISSUE THREAD

**Issue by thyeun** [Aylur/dotfiles#46]
i been trying to remove ```asusctl``` from the file ```quicksetting,js``` but once i relogin, everythings will be stop working

Remove below section on ```quicksetting.js```

```
const asusctlToggle = smallToggle(
    'asusctl/profile-toggle',
    'asusctl/profile-indicator',
);

const asusmodeToggle = smallToggle(
    'asusctl/mode-toggle',
    'asusctl/mode-indicator',
);
```

**Comment by Aylur** [comment]
remove every reference of these variables, not just their definition

**Comment by thyeun** [comment]
ok, understand, and thanks

**Comment by thyeun** [comment]
For the latest update, i remove remove ```asusctl``` from the file ```quicksetting,js```.

And add the below two things
```
const UpdateToggle = () => Button({
    className: 'toggle',
    onClick: () => execAsync(['bash', '-c', "foot --app-id update -T update yay -Syu && notify-send 'The system has been updated' &"]),
    child: FontIcon({ icon: '' }),
});

const RecordToggle = () => Button({
    className: 'toggle',
    onClick: () => execAsync(['bash', '-c', "ags run-js 'ags.Service.Recorder.start()'"]),
    child: FontIcon({ icon: '' }),
});

```
And also make change on the below
```
children: Service.Asusctl?.available
                        ? [
                            Box({ children: [RecordToggle(), UpdateToggle(), DNDToggle()] }),
                            Box({ children: [AppmixerToggle(), ThemeToggle(), MuteToggle()] }),
```

But the new add in that replace ```asusctl``` are not appear on the ```quicksetting```

**Comment by fr13ndxd** [comment]
@thyeun just try doing 
```js
children: [
Box({ children: [RecordToggle(), UpdateToggle(), DNDToggle()] }),
Box({ children: [AppmixerToggle(), ThemeToggle(),MuteToggle()] }),
],
```

**Comment by thyeun** [comment]
@fr13ndxd no, it is not because of the ```]``` , before the new update on ```ags``` it working fine, but now not possible.

Might somethings i miss out. the whole code for that section is below.

```
Box({
            className: 'toggles-box',
            children: [
                Box({
                    vertical: true,
                    className: 'arrow-toggles',
                    children: [NetworkToggle(), BluetoothToggle()],
                }),
                Box({
                    vertical: true,
                    className: 'small-toggles',
                    vexpand: true,
                    hexpand: false,
                    children: Service.Asusctl?.available
                        ? [
                            Box({ children: [UpdateToggle(), RecordToggle(), DNDToggle()] }),
                            Box({ children: [AppmixerToggle(), ThemeToggle(), MuteToggle()] }),
                        ] : [
                            Box({ children: [DNDToggle(), MuteToggle()] }),
                            Box({ children: [AppmixerToggle(), ThemeToggle()] }),
                        ],
                }),
            ],
        }),

```

**Comment by fr13ndxd** [comment]
yeah replace the
```js
                    children: Service.Asusctl?.available
                        ? [
                            Box({ children: [UpdateToggle(), RecordToggle(), DNDToggle()] }),
                            Box({ children: [AppmixerToggle(), ThemeToggle(), MuteToggle()] }),
                        ] : [
                            Box({ children: [DNDToggle(), MuteToggle()] }),
                            Box({ children: [AppmixerToggle(), ThemeToggle()] }),
                        ],
```
with the code i gave you

**Comment by fr13ndxd** [comment]
if you removed the asusctl references then the `Service.Asusctl?` probably wont work and its bloat in this case

**Comment by thyeun** [comment]
@fr13ndxd I understand what you mean, but it no working by that way. if i change according to yours suggestion, the whole bar will be freeze, ```quicksetting```, ```datemenu``` and ```applauncher``` wont be clicker-able

**Comment by fr13ndxd** [comment]
huh? thats weird, i have no idea whats wrong

**Comment by thyeun** [comment]
@fr13ndxd same here, i change it because i'm not ```Asus``` user. =.=

What you suggested, i been try it out before. Hahahahaha, that why i know it not working. =.=

**Comment by fr13ndxd** [comment]
i will update my dotfiles tomorrow to new ags version, you can copy the buttons from it

**Comment by thyeun** [comment]
you have to update the latest ```ags``` release by @Aylur than try change replace that two button, than you might see different things =.= hahahhaha

**Comment by fr13ndxd** [comment]
thats what i said, i need to update it to latest ags

**Comment by fr13ndxd** [comment]
@thyeun also last question, does it show any error in terminal? the ags when it freeze

**Comment by thyeun** [comment]
@fr13ndxd No error show.

**Comment by fr13ndxd** [comment]
@thyeun i updated my dotfiles, it should work.

**Comment by thyeun** [comment]
@fr13ndxd I know my error come from this line

```
import * as asusctl from '../../modules/asusctl.js';
```

I should not commented out. if commented out it will freeze.

Thanks!!!
