### ISSUE TITLE
Border around ArcMenu Search

### ISSUE THREAD

**Issue by ImVaskel** [Aylur/dotfiles#5]
Hello, I'm trying to get a similar look to the arcmenu runner you have on your images (for gnome), but I cannot get the background image to be as large as yours. Is this a problem with the size of my screen or is there a setting I can change to increase the background image size?

**Comment by Aylur** [comment]
try adding some padding
```
.arcmenu-menu > * > * > * > * > *:first-child {
  border-radius: 10px;
  margin: 0;
  padding: 60px;
}
```
