### ISSUE TITLE
The uptime no more counting after the recent update!!

### ISSUE THREAD

**Issue by thyeun** [Aylur/dotfiles#50]
![Screenshot_2023-08-07-01-04-21_21685](https://github.com/Aylur/dotfiles/assets/1939446/7af3a074-9128-4499-96de-0f601b636c77)

**Comment by Aylur** [comment]
A few more other stuff won't work either, because there was a breaking change https://github.com/Aylur/ags/pull/26
I am currently working on my setup, will update this repo today or tomorrow.

**Comment by thyeun** [comment]
Sorry for that, i might too fast following your update, that cause this.
