### ISSUE TITLE
incorrect dock pinned and skip pinned for some application

### ISSUE THREAD

**Issue by thyeun** [Aylur/dotfiles#51]
```
const pinned = [
    'librewolf',
    'kitty',
    'browse the filesystem',
    'Sublime Text',
];
```
```
type: 'hyprland/taskbar',
            orientation,
            skip: pinned,
```
![Screenshot_2023-08-07-10-26-15_23487](https://github.com/Aylur/dotfiles/assets/1939446/448a5427-097f-4052-ad25-74a5813c4d60)

When the ```skip pinned``` same as the ```pinned```, it should not appear again on the dock right?

**Comment by thyeun** [comment]
And one more thing, do you notice that the icon on dock, ```sublime text``` on the left side some how dont have ```dot``` below the icon, but others got. 

It is normal?

**Comment by Aylur** [comment]
Because `Sublime Text` matches with an Application but it doesn't with the class listed in `hyprctl clients`. The dot only appears if the given string is found in a running client's class

**Comment by thyeun** [comment]
Using ```hyprctl clients -j``` check,  ```sublime text``` class give me ```subl```, after change according to ```hyprctl clients -j``` show, than it is correct now.

```
"floating": false,
    "monitor": 0,
    "class": "subl",
    "title": "~/.config/ags/layouts/widgets/dock.js - Sublime Text (UNREGISTERED)",
    "initialClass": "subl",
    "initialTitle": "~/.config/ags/layouts/widgets/dock.js - Sublime Text (UNREGISTERED)",
    "pid": 537261,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
```

I think for the moment ```kitty```and ```subl``` should be ok, but not ```LibreWolf``` and ```thunar```.  As ```LibreWolf``` appear correctly 

```
"floating": false,
    "monitor": 0,
    "class": "LibreWolf",
    "title": "incorrect dock pinned and skip pinned for some application · Issue #51 · Aylur/dotfiles — LibreWolf",
    "initialClass": "LibreWolf",
    "initialTitle": "LibreWolf",
    "pid": 537514,
    "xwayland": false,
    "pinned": false,
    "fullscreen": false,
    "fullscreenMode": 0,
    "fakeFullscreen": false,
    "grouped": [],
    "swallowing": null
```

But the ```dot``` not show on ```LibreWolf``` (thunar is weird case). As you can see below image.

![Screenshot_2023-08-07-23-59-15_21343](https://github.com/Aylur/dotfiles/assets/1939446/e768d13b-ccff-453c-a247-7127619fd2c5)

**Comment by thyeun** [comment]
I accept it and thanks for your explanation. It is ```librewolf``` and ```thunar``` issue.
