### ISSUE TITLE
Notthing works

### ISSUE THREAD

**Issue by Sohail-XD** [Aylur/dotfiles#53]
Followed the wiki & install dependancies and built the application but when I run ags toggle-window overwiew, nothing happens. A shadow appears around my active window but thats not intended. I copied and pasted your ags config.

**Comment by Sohail-XD** [comment]
I thought that won't be a problem. Everything is working now. I thought overview module would be like "alt-tab".  Is there a way to make it appear while holding down a key(s) and close it after releasing the key.

**Comment by Aylur** [comment]
Look into how to bind keys on Hyprland

**Comment by Sohail-XD** [comment]
I have a few more doubts @Aylur. Should I ask them here or make new issues. I don't want to be annoying, so answer at your own time.

**Comment by Aylur** [comment]
open up a new issue, maybe it helps other people too
