### ISSUE TITLE
How to use "enter" key to perform an action

### ISSUE THREAD

**Issue by Sohail-XD** [Aylur/dotfiles#56]
For example, in overview.js widget ```onClick: () => execAsync(`hyprctl dispatch workspace ${index}`).catch(print),```
I want to perform this action with "Enter" or any other key. 

Right now pressing "Enter" highlights the window and doesn't do anything. Double click is working to move workspace. It would be nice if it would just work with a single click or enter key

**Comment by Aylur** [comment]
that is a side effect of https://github.com/Aylur/ags/commit/318752eb6ecae011f8037b8984211ff4b79a4ad8
thanks for pointing that out
```js
{
  type: 'button',

  // onClick callbacks are for mouse clicks only
  onClick: (button) => { }

  connections: [
    // the 'clicked' signal can be used for reacting to enter
    ['clicked', (button) => { }],

    // the 'key-pressed-event' and 'key-released-event' can be used for other keyboard events
    ['key-pressed-event', (button, event) => {}],
  ],
}
```

**Comment by Sohail-XD** [comment]
Working perfectly. Thanks!!!!!!!!!!!!!!!
