### ISSUE TITLE
update for the gnome dotfiles?

### ISSUE THREAD

**Issue by Botan-Yuukan** [Aylur/dotfiles#57]
I am currently testing out the gnome theme on gnome 44 and for the most part everythings works besides a view visual issues when i go to the desktop/app overview. 

Do you have any idea on fixing that
![image](https://github.com/Aylur/dotfiles/assets/65094216/a3317daf-b6e2-47b2-976e-d1f337482459)

**Comment by Botan-Yuukan** [comment]
if you need i can be ur tester for the gnome theme's

**Comment by Aylur** [comment]
That theme is not maintained, and I am not interested in it currently, sorry.

**Comment by Botan-Yuukan** [comment]
umm what are some ways to resources to maintain the theme

**Comment by Aylur** [comment]
it is just a modification of the [gnome-shell theme](https://gitlab.gnome.org/GNOME/gnome-shell/-/tree/main/data/theme)
