### ISSUE TITLE
Icons not displaying for some apps

### ISSUE THREAD

**Issue by Sohail-XD** [Aylur/dotfiles#59]
I have hicolor and other default themes that have "inherit = hicolor,breeze", so there shouldn't be a problem with icon not existing.

![image](https://github.com/Aylur/dotfiles/assets/86248129/11149258-27ec-4a00-b8c0-f540fc0fc01b)

**Comment by Sohail-XD** [comment]
The two applications in the ss without icons are Pamac-manager and Anki

**Comment by Aylur** [comment]
these icons are derived from the client's `class` which you can get by running `hyprctl clients -j`, but sometimes this class doesn't match with the icon name, and you have to manually substitute it
in `layouts/widgets/overview.js` there is a `substitute` function where you can add them

**Comment by Sohail-XD** [comment]
This is not an issue for just a few apps.It happens if the package is from the aur. In the below picture "code" is displayed but other packages with no image are not. Is there a way to make it behave like rofi?

![image](https://github.com/Aylur/dotfiles/assets/86248129/ce7218a6-b90b-4950-a62a-d05473018a60)

**Comment by Aylur** [comment]
the only way to check for running apps is `hyprctl -j clients` as far as I know and the only information there that could hint for an icon name is `class`

**Comment by Sohail-XD** [comment]
Is there an example, how to use substitute function? There is `from carpine to facebook messenger`. Should I add other app names like that under it?

**Comment by Aylur** [comment]
yeah just add whatever you want to that function  `{ from: <class>, to: <icon-name> }`

**Comment by Sohail-XD** [comment]
Omg it's working & the problem was because of one capital letter??? wow. Super easy. Thanks for clearing beginner doubts.

**Comment by Sohail-XD** [comment]
How do I increase the icon size?
