### ISSUE TITLE
How to Install the shell theme for Rose?

### ISSUE THREAD

**Issue by Botan-Yuukan** [Aylur/dotfiles#6]
Can you please provide some steps to install the shell theme?

**Comment by Botan-Yuukan** [comment]
Found out that the instructions were wrong when we copied the rose theme files as they need to be in ~/.local/share/themes and not  ~/.local/themes

**Comment by Botan-Yuukan** [comment]
I am currently missing the dock so how would i get the dock?

**Comment by Aylur** [comment]
oops, fixed the typos
