### ISSUE TITLE
How to recreate the notification/calendar widget

### ISSUE THREAD

**Issue by Sohail-XD** [Aylur/dotfiles#60]
As if in what layout/widgets to keep in your config to display it with my own custom bar. Is there a way to connect or use ags widgets on a eww bar?

**Comment by Aylur** [comment]
You can use `ags run-js` or `ags toggle-window` to achieve this

**Comment by Sohail-XD** [comment]
Does the applaucher have cache? like rofi showing recently opened apps.

**Comment by Aylur** [comment]
it doesn't. you would have to implement it yourself

**Comment by Sohail-XD** [comment]
> it doesn't. you would have to implement it yourself

Some app icons aren't visible. Especially the ones I added manually to .desktop files. Any way or any specific path they should follow?

**Comment by Aylur** [comment]
> Does the applaucher have cache? like rofi showing recently opened apps. I get kde connect on top every time i launch it.

now it does.

**Comment by Aylur** [comment]
> Some app icons aren't visible. Especially the ones I added manually to .desktop files. Any way or any specific path they should follow?

currently only valid Gtk icons and installed icons show, for custom paths it needs some tinkering
