### ISSUE TITLE
Making Home Screen like this

### ISSUE THREAD

**Issue by Rafi1018** [Aylur/dotfiles#61]
Hey I want to make my desktop look like this on my debian PC. How can I make my PC look like this? It did be great if you can help :)

![image](https://github.com/Aylur/dotfiles/assets/142591064/77358cfc-eb00-497d-88e8-9f7952024304)

**Comment by Aylur** [comment]
that setup is using [eww](https://github.com/elkowar/eww) on top of [Hyprland](https://github.com/hyprwm/Hyprland)
if you manage to install those on Debian with list dependencies then just copy the config files from [the eww branch](https://github.com/Aylur/dotfiles/tree/eww) (which is not maintained anymore) and thats all

**Comment by Rafi1018** [comment]
I see thanks!
