### ISSUE TITLE
cant click quicksetting and datemenu, after the latest update for ags and dotfiles.

### ISSUE THREAD

**Issue by thyeun** [Aylur/dotfiles#63]
Cant click to see the quicksetting and datemenu after the latest update for ags and dotfiles.

Any extra things i need to update also?

**Comment by Aylur** [comment]
are you sure you are on the latest commit? and have changed anything?

**Comment by thyeun** [comment]
i need to remove the line 

```
import * as asusctl from '../../modules/asusctl.js';

```

Since i'm not using it. sorry for open this issue.
