### ISSUE TITLE
Apps in dock taskbar missing

### ISSUE THREAD

**Issue by cafetestrest** [Aylur/dotfiles#64]
Hi @Aylur,
I've noticed that some of the apps in the dock's Taskbar are missing.
From the ones I found missing are VSCodium and PHPStorm, but there could be more.

I'm able to add one by one back by hard coding the class in Taskbar and icon names in AppItem, but there must be a better way to accomplish so.

**Comment by fr13ndxd** [comment]
im not sure but i think the only way to add the icons is that way you did it

**Comment by thyeun** [comment]
You can add the apps into the dock by name or description.

**Comment by fr13ndxd** [comment]
@thyeun i think thats what he did

**Comment by Aylur** [comment]
the only information that is useful for identifying which app a running client corresponds to, is their class. and the class can differ based on what source was the program installed from, so you need to find a string that can match the class and the app
