### ISSUE TITLE
icons missing

### ISSUE THREAD

**Issue by bobblkabb** [Aylur/dotfiles#66]
![Screenshot](https://github.com/Aylur/dotfiles/assets/7815101/bcdf51d5-4588-4b9f-a36d-3016833b6e0f)

### Edit
Not only missing icons, those functions don't work.
###

Hi, 

I'm new in this. A few things I fixed myself but there's still some things to do.
Icons are missing.
What is going wrong? Which config files I have to change?
Which packages are probably missing?

BR,
Michael

**Comment by fr13ndxd** [comment]
i think aylur dont update the eww bar anymore, but the null means it couldnt get the icon. do you have all the depencies? show the eww logs.

**Comment by Aylur** [comment]
the eww config is unmaintained and I haven't used in a while, so you are on your own, but I guess you have a dependency missing which the error log should tell you if you do, or some scripts are not compatible with your system
