### ISSUE TITLE
how to open the dock without hovering on the bottom

### ISSUE THREAD

**Issue by Gxnum** [Aylur/dotfiles#68]
i just want to have a dock that doesnt hide
i am asking what is the name of the dock for when i want to open it with `ags --toggle-window` or `ags -t`because i cannot seem to find it

thanks!

**Comment by Gxnum** [comment]
nvm found out how to do it

**Comment by Aylur** [comment]
you can get a list of windows by running
```bash
ags -b hypr -r "Array.from(ags.App.windows.values()).map(w => w.name).join('\n')"
```

but even if you open it, it will close on hover lost, so you will need to edit the dock

**Comment by Gxnum** [comment]
ok tysm

**Comment by Gxnum** [comment]
![image](https://github.com/Aylur/dotfiles/assets/65645307/d4675163-def6-4268-83c1-7a4d2f48d16b)

is that supposed to happen?

**Comment by Aylur** [comment]
>is that supposed to happen?
you have an older version of my dotfiles

>EDIT 2: just tell me whats the name for the dock pls
its just `dock<monitor>` if you have one monitor its `dock0`

**Comment by Gxnum** [comment]
> you have an older version of my dotfiles

i removed .config/ags and then i git cloned the repository, did everything the guide asked and then when i ran ags it showed me this

```bash
(ags:2401): Gjs-WARNING **: 15:47:17.942: JS ERROR: TypeError: ags.Variable is not a function
@file:///home/bill/.config/ags/js/variables.js:13:27
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Aylur** [comment]
your ags is out of date
