### ISSUE TITLE
Spotify cover art doesn't display

### ISSUE THREAD

**Issue by MegaTKC** [Aylur/dotfiles#70]
Not using eww, but your ags fork. I've installed everything through the AUR and official Arch repos. I've played a song, and checked the status tray and found that the names are fetched.

However not the picture, and ran ags in the terminal to get this warning.
`(ags:8258): Gjs-WARNING **: 10:32:46.042: JS ERROR: failed to cache /home/thomas/.cache/ags/media/Ariana Grande-motive with Doja Cat: Gio.IOErrorEnum: Operation not supported
_cacheCoverArt/<@resource:///com/github/Aylur/ags/service/mpris.js:123:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

Am I missing something as a dependency? Or does the spotify flatpak just not work?

**Comment by fr13ndxd** [comment]
which version of aylurs-gtk-shell do you have? the -git one?

**Comment by MegaTKC** [comment]
I'm using aylurs-gtk-shell. The one without -git at the end of it.

**Comment by fr13ndxd** [comment]
try the package with -git

**Comment by MegaTKC** [comment]
I've uninstalled `aylurs-gtk-shell` and replaced it with `aylurs-gtk-shell-git`. The album art doesn't show. Same error.

`:26638): Gjs-WARNING **: 17:21:03.314: JS ERROR: failed to cache /home/thomas/.cache/ags/media/24kGoldn-Prada feat. Lil Tecca: Gio.IOErrorEnum: Operation not supported
_cacheCoverArt/<@resource:///com/github/Aylur/ags/service/mpris.js:123:24
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:26
6:34

Error: "failed to open image: No such file or directory (os error 2)"

(ags:26638): Gjs-WARNING **: 17:21:03.512: JS ERROR: failed to cache /home/thomas/.cache/ags/media/24kGoldn-Prada feat. Lil Tecca: Gio.IOErrorEnum: Operation not supported
_cacheCoverArt/<@resource:///com/github/Aylur/ags/service/mpris.js:123:24
_init/GLib.MainLoop.prototype.runAsync/</<@resour
ce:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

**Comment by fr13ndxd** [comment]
no idea, maybe try clearing ags cache `ags --clear-cache`

**Comment by MegaTKC** [comment]
Installing gvfs worked. I see album art now, thanks.
