### ISSUE TITLE
blank notifications

### ISSUE THREAD

**Issue by r4sso** [Aylur/dotfiles#71]
Notifications work, but when I click it, it appears blank (no text, no image).
 Did I miss some dependencies?
 
![2023-09-19T19:24:22,316994063+08:00](https://github.com/Aylur/dotfiles/assets/66033675/a73fce4c-23ae-4a68-a673-0dc5580e5a75)

**Comment by fr13ndxd** [comment]
did you edit the code?

**Comment by thyeun** [comment]
try press any indicator see any notification pop up or not, with latest notification center, the background wallpaper was remove, and same goes to app launcher.

For the missing icon on the temperature, you have to get the ```temperature-symbolic``` and update your icon cache.

if you want to switch left/right for your notification center, you have to edit your ```Dashboard.js```.

**Comment by r4sso** [comment]
@fr13ndxd only the clock format and font size

**Comment by r4sso** [comment]
I revert to original code, still have same issue. 
Inside notifications box its doesnt display anything and  i cant click it.
![2023-09-20T07:33:56,267167662+08:00](https://github.com/Aylur/dotfiles/assets/66033675/38bc0a26-69df-4d4c-980b-265a12f19917)

site i use to test notifications:
- https://www.bennish.net/web-notifications.html
- https://www.kenherbert.dev/browser-notification-tester/

same result when i use other site like youtube.

What I mean to looks like:
![preview](https://user-images.githubusercontent.com/104676705/266865226-12fa670d-da75-4108-b44e-c823c47f2679.png)

**Comment by r4sso** [comment]
> `temperature-symbolic`

I can't find the 'temperature-symbolic'. Could you provide the package name?

**Comment by r4sso** [comment]
> `temperature-symbolic` 

I couldn’t find 'temperature-symbolic' package. Could you provide the package name?

**Comment by r4sso** [comment]
> temperature-symbolic

I couldn’t find 'temperature-symbolic' package. Could you provide the package name?

**Comment by thyeun** [comment]
@r4sso It is not blank but might be a bug, for current change, you have to press the ```clear``` button first on ```notification center``` than only you will see the change/update of notify.

And for the ```song art``` not appear, it is disappear after the current change, i dont know why also.

For the ```temperature-symbolic``` if your current icon pack dont have, you have to get it from others icon pack. And you can change the icon inside the file ```icons.js```

My as below image.
![Screenshot_2023-09-20-09-02-03_1436](https://github.com/Aylur/dotfiles/assets/1939446/b952410e-85e3-4f0b-8956-8bfcf7e23044)

**Comment by thyeun** [comment]
@r4sso I remain the notification center wallpaper too, but the latest update it been remove.

**Comment by r4sso** [comment]
@thyeun Thank you for answering. I get the same result when I press 'clear.' If it's a bug, I will wait for fix :)

**Comment by thyeun** [comment]
@r4sso Look like the ```song art``` is there too, but you have to start ```spotify```, play a song first, than press ```clear```, than player a few more song, than only you will see the ```song art``` appear inside the notification center.

And you will find that, it is abit delay, if compare with old old version. (it might what i a feel only)

**Comment by r4sso** [comment]
@thyeun  By 'song art' do you mean, the media button in powermenu? its work.
(ignore the battery status/profile, i dont use laptop.)
![image](https://github.com/Aylur/dotfiles/assets/66033675/3f388481-40aa-4f3f-809b-851736dc5d47)

But for notifcations i got same results:
![image](https://github.com/Aylur/dotfiles/assets/66033675/1753125e-a34e-4641-b55e-256d22950540)

screenshot notifcations:
![image](https://github.com/Aylur/dotfiles/assets/66033675/d65671f8-c5d2-4dd4-922b-d5648ab79081)


I might miss dependencies for notifications.

**Comment by thyeun** [comment]
@r4sso the song art i mean is the notification center song art, for old version, if you play/change/forward a song from spotify, you will get a notify song art at notification center.

**Comment by thyeun** [comment]
@r4sso And you notice also, current change your ```spotify``` icon no more appear, the green icon beside your date/time. Not sure it is bug or not.

**Comment by Daemonical** [comment]
@r4sso I had the same notification issue, the latest ags update (1.3.0) fixed it for me.

**Comment by MegaTKC** [comment]
Installing the `-git` version helped for me.

**Comment by r4sso** [comment]
@Daemonical Thanks,
It's fixed now with the latest update (1.3.0).
![2023-09-21_08-31-21](https://github.com/Aylur/dotfiles/assets/66033675/02627291-ae16-4573-a480-b0be1bb4c5c0)
