### ISSUE TITLE
Lockscreen can be bypassed

### ISSUE THREAD

**Issue by cafetestrest** [Aylur/dotfiles#72]
Hi @Aylur ,
I'm fiddling around with the lockscreen, I'm able to bypass it as I can change the focused window in the background and open console / run ags -q while on the lockscreen thus killing the process.

Unsure if that is limitation of the Hyprland or ags though?

Also a good use case would be that it appears under powermenu.

**Comment by Aylur** [comment]
I get that its possible to start up a terminal, but how are you able to write to it? writing `ags -q` should be inhabited by the lockscreen's entry widget

**Comment by fr13ndxd** [comment]
it can be bypassed just by hitting ctrl + shift + r
because of this line in hyprland config:
```
bind = CTRL SHIFT, R,   exec, ags -b hypr quit; ags -b hypr
```

**Comment by cafetestrest** [comment]
@Aylur ,

I've just tested it and I can not focus with just my mouse, I need to strictly change focused program to the terminal and then once terminal is focused I'm able do write whatever there.

The way I replicate it, don't touch the mouse use only keyboard and try to open/ re-focus on a terminal and write there whatever.

> it can be bypassed just by hitting ctrl + shift + r because of this line in aylurs hyprland config:
Exactly, I can also run a terminal / execute whatever from my shortcuts list.

In case you find this useful, here is my hyprland.conf file: https://github.com/cafetestrest/nixos/blob/main/modules/hyprland/config/hyprland.conf

I even tried adding layers_hog_keyboard_focus in my config but I was still able to do so.

**Comment by ivanbalashov239** [comment]
a lockscreen should probably be a separate project, that implements wayland protocols and by being a separate process/client/etc is more secure,

could be also configurable and reuse ags code

https://github.com/jovanlanik/gtklock
https://git.sr.ht/~kennylevinsen/gtkgreet
