### ISSUE TITLE
white transparent box on left of screen in some widgets

### ISSUE THREAD

**Issue by zielOS** [Aylur/dotfiles#75]
Hi 

I was using your dotfiles for ags and I am this white box around some widgets. I have attached the pic for one of the power menu. The same thing happens for overview and application launcher as well smaller boxes around overview 
![2023-10-09_02-26-32](https://github.com/Aylur/dotfiles/assets/135585151/b18ab571-f555-432d-aec3-6c4ef4803110)

**Comment by Aylur** [comment]
these popup windows have a transparent border to make space for the drop shadow, and it seems you have set the layerrule to something else and its getting blurred by Hyprland
