### ISSUE TITLE
I reinstalled my system and downloaded ags but the old config isn't working

### ISSUE THREAD

**Issue by Sohail-XD** [Aylur/dotfiles#76]
I downloaded your ags config and that doesnt work either. When I try to open "overview" I get 
`Gjs-Console-CRITICAL **: 19:53:53.267: There is no window named overview`

**Comment by Aylur** [comment]
are you sure both are up to date?

**Comment by Sohail-XD** [comment]
Yes I am sure

**Comment by Sohail-XD** [comment]
Rebuilt again from source and similar error
`(com.github.Aylur.ags:104816): Gjs-Console-CRITICAL **: 20:29:11.297: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:95:27
ToggleWindow@resource:///com/github/Aylur/ags/app.js:178:24
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34`

**Comment by Sohail-XD** [comment]
Can you explain how to get "overview" window working without any other things in your dotfiles

**Comment by Aylur** [comment]
remove everything other than the overview widget?

**Comment by Sohail-XD** [comment]
> remove everything other than the overview widget

It has a few dependencies like option.js etc but even when I remove other js files, it still says "Another notification daemon is running" or "Another system tray is running"

**Comment by Aylur** [comment]
remove the unnecessary imports from `imports.js`

**Comment by Sohail-XD** [comment]
Thanks for being patient with me. Everytime I remove something, I get error like 
```(com.github.Aylur.ags:14650): Gjs-Console-CRITICAL **: 16:02:13.507: SyntaxError: ambiguous indirect export: Hyprland  

(com.github.Aylur.ags:14650): Gjs-Console-CRITICAL **: 16:04:53.147: Error: There is no window named overview
getWindow@resource:///com/github/Aylur/ags/app.js:95:27
toggleWindow@resource:///com/github/Aylur/ags/app.js:70:24
ToggleWindow@resource:///com/github/Aylur/ags/app.js:177:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:329:38
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34```
I don't know where would be the end for this

**Comment by Aylur** [comment]
google what ambiguous indirect export means
```js
import Hyprland from 'somewhere.js' // js module has no deafult export, so this throws an error
import { Hyprland } from 'somewhere.js' // is what you probably intended 
```

**Comment by Sohail-XD** [comment]
Well that's the thing, I do not have any imports like that and I only deleted lines I didn't need, didn't add any

**Comment by Aylur** [comment]
with `1.4.0` `App.instance` is no longer a thing, replace it with simply `App`

**Comment by Sohail-XD** [comment]
I retried the steps with your updated dots and it works perfectly now, I must have git cloned it right before some updates last week. Thank you so much for being so helpful and patient. You should also check this out, it's based on ags https://github.com/end-4/dots-hyprland/tree/illogical-impulse
