### ISSUE TITLE
Bluetooth hotfix not working with update 

### ISSUE THREAD

**Issue by cafetestrest** [Aylur/dotfiles#77]
After a bit of script tweaking this is the bare minimum what seems to reset it when I run the command: `ags run-js "$(cat script.js)"`

```
const { instance } = ags.Service.Bluetooth;

instance._getDevices().forEach(d => {
    instance._deviceRemoved(null, d);
});

instance._getDevices().forEach(d => {
    instance._deviceAdded(null, d);
});
```

_Originally posted by @cafetestrest in https://github.com/Aylur/dotfiles/issues/49#issuecomment-1666961154_
            

Hi, how can I accomplish the same thing as with the new updates I'm unable to retrieve instance from Service like so?
Thank you.

**Comment by Aylur** [comment]
you have to import with the `import` keyword
```js
const path = 'resource:///com/github/Aylur/ags/service/bluetooth.js';
import(path).then(({ default: bluetooth }) => {
    bluetooth._getDevices().forEach(d => {
        bluetooth._deviceRemoved(null, d);
        bluetooth._deviceAdded(null, d);
    });
});
```
