### ISSUE TITLE
Dock: Add Settings Options [Feature Request]

### ISSUE THREAD

**Issue by nine7nine** [Aylur/dotfiles#78]
It would be nice if Settings had a page for customizing the Dock. Specifically:

- Dock Placement: Bottom, Top, Left and Right sides
- Show: Static placement or reveal from screen edge (default behavior)
- Ability to set applications for the Dock in Settings too.
- Change icon size, background, etc.

Generally, I've been pretty happy with this simple dock, even if it isn't the best at tracking windows, along with some other limitations... But there really aren't any good options for Docks for Hyprland or Wayland... but I do plan on adding an OSK eventually to my setup - and it doesn't make much sense for the dock to be on the bottom, if i plan to use an OSK... it'd be nice to have a bit more flexibility built-in.

Furthermore, because I keep AGS / dot files synced (to avoid breakage on updates) it would be nice if Dock settings were actually integrated in AGS, rather than having to modify code on almost every update.

( generally-speaking I only require very minimal changes to the default settings. your shell is awesome, as is )

**Comment by Aylur** [comment]
Sorry, I have no desire to implement these options as I wouldn't be using them. But they shouldn't be that hard to implement.

> Furthermore, because I keep AGS / dot files synced (to avoid breakage on updates) it would be nice if Dock settings were actually integrated in AGS, rather than having to modify code on almost every update.

No widget implementation will be integrated into AGS, as that is just a library, and the widgets should be implemented by the user

**Comment by nine7nine** [comment]
Fair enough.

Poking around your code,  I'm starting to familiarize myself with it, despite not being a JS guy... a lot of it looks more straight-forward to modify than i initially thought. Sorry for the noise on that;

I think I'll have a stab at implementing an a better Dock, as you are likely correct that it shouldn't be that difficult to implement (at least the core / usability improvements)...  I already had some success at making a few unrelated changes: changing the overivew placement, adding icon scaling to it... The Dock changes can't be much harder.

very cool project, Aylur.
