### ISSUE TITLE
Workspaces don't update

### ISSUE THREAD

**Issue by System-x64** [Aylur/dotfiles#8]
Bro I am very new to using eww but i somehow managed to work other things...somehow, but i just can't get the workspaces widget to update if i'm moving to another workspace or i open something, it only updates when i make some changes to the code and eww auto reloads it...can you suggest any reason it aint working? thank you!

**Comment by System-x64** [comment]
oh btw it does go to the correct workspace on clicking it toh

**Comment by Aylur** [comment]
how does your variable definition look like?

**Comment by System-x64** [comment]
![image](https://user-images.githubusercontent.com/90208727/231440362-17710f54-3400-47fd-bc07-294374f7a444.png)

same as yours

**Comment by System-x64** [comment]
@Aylur i got it to work, i looked through the script and realized i didn't install socat on this build, installed it and everything is working as expected

 thx for the dots , i love your styling
