### ISSUE TITLE
Launching the lockscreen with keybind from hyprland? 

### ISSUE THREAD

**Issue by RoccoRakete** [Aylur/dotfiles#80]
Is this somehow possible? :)

**Comment by RoccoRakete** [comment]
EDIT: I found out it's working removing the "Monitor" variable from the Lockscreen, but after wakeup from suspend, the system is unlocked! That's not good :D

**Comment by Aylur** [comment]
make the Lockscreen service global then run `ags -r "lockscreen.lockscreen()"`
