### ISSUE TITLE
Installer is apparently stuck

### ISSUE THREAD

**Issue by Mikaral** [Aylur/dotfiles#82]
Hi! Recently I tried to install your dotfiles on an Arch Linux (Kernel 6.5.7) and the installer seems to be stuck, it's giving the same error messages for about an hour, the only thing that is being updated is the timer. I followed your commands listed on the README and installed all required and optional dependencies. Any idea how can I fix that? Thanks in advance! Your setup is beautiful! 

The error messages: 

```
(com.github.Aylur.ags:1908): Gjs-Console-CRITICAL **: 00:43:01.395: TypeError: out.split(...).find(...) is undefined
ram<.poll<@file:///home/mikael/.config/ags/js/variables.js:46:10
startPoll/this._interval</<@resource:///com/github/Aylur/ags/variable.js:41:44
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
  

(com.github.Aylur.ags:1908): Gjs-Console-CRITICAL **: 00:43:01.603: TypeError: out.split(...).find(...) is undefined
cpu<.poll<@file:///home/mikael/.config/ags/js/variables.js:39:10
startPoll/this._interval</<@resource:///com/github/Aylur/ags/variable.js:41:44
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

**Comment by Aylur** [comment]
these two lines mean that `top -b -n 1` and `free` didn't return what was expected, which to my knowledge can not happen, so there is probably something else to it

**Comment by Aylur** [comment]
theoretically it is possible tho, but now it is handled

**Comment by Mikaral** [comment]
Thanks! It worked flawlessly now!
