### ISSUE TITLE
Issue running ags

### ISSUE THREAD

**Issue by Mats357** [Aylur/dotfiles#83]
On NixOS and when logging in with Hyprland and running ags, I get these errors.

```
(com.github.Aylur.ags:4096): Gjs-Console-CRITICAL **: 21:44:35.713: {
    "stack": "subprocess@resource:///com/github/Aylur/ags/utils.js:164:37\nscssWatcher@file:///home/mats/.config/ags/js/utils.js:71:18\n@file:///home/mats/.config/ags/config.js:19:7\n_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34\n",
    "fileName": "resource:///com/github/Aylur/ags/utils.js",
    "lineNumber": 164,
    "columnNumber": 37
}
no colorpicker cache found
Error: "failed to open image: No such file or directory (os error 2)"

(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.147: value "-0,010000" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'

(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.149: value "-0,010000" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'

(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.150: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'

(com.github.Aylur.ags:4096): Gjs-CRITICAL **: 21:44:36.151: JS ERROR: Error: Wrong type undefined; string expected
set label@resource:///com/github/Aylur/ags/widgets/label.js:34:9
callback@resource:///com/github/Aylur/ags/widgets/widget.js:35:53
connect/<@resource:///com/github/Aylur/ags/utils.js:78:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34
```

Any idea of what is going wrong here?

**Comment by Aylur** [comment]
> (com.github.Aylur.ags:4096): Gjs-Console-CRITICAL **: 21:44:35.713: {
    "stack": "subprocess@resource:///com/github/Aylur/ags/utils.js:164:37\nscssWatcher@file:///home/mats/.config/ags/js/utils.js:71:18\n@file:///home/mats/.config/ags/config.js:19:7\n_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34\n",
    "fileName": "resource:///com/github/Aylur/ags/utils.js",
    "lineNumber": 164,
    "columnNumber": 37
}

install `inotify-tools` or you can ignore it,

> Error: "failed to open image: No such file or directory (os error 2)"

this one is from swww, the wallpaper file is missing

>(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.147: value "-0,010000" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'
>
>(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.149: value "-0,010000" of type 'gdouble' is invalid or out of range for property 'fraction' of type 'gdouble'
>
>(com.github.Aylur.ags:4096): GLib-GObject-CRITICAL **: 21:44:36.150: value "nan" of type 'gdouble' is invalid or out of range for property 'value' of type 'gdouble'

these ones can be from a few things, but I suspect its from mpris, you can just ignore it

>(com.github.Aylur.ags:4096): Gjs-CRITICAL **: 21:44:36.151: JS ERROR: Error: Wrong type undefined; string expected
set label@resource:///com/github/Aylur/ags/widgets/label.js:34:9
callback@resource:///com/github/Aylur/ags/widgets/widget.js:35:53
connect/<@resource:///com/github/Aylur/ags/utils.js:78:21
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34

this one doesn't contain any useful information, but I suspect a missing dependency here too

**Comment by Mikaral** [comment]
I solved the swww issue by installing the [swww-git](https://aur.archlinux.org/packages/swww-git) instead of the [swww](https://aur.archlinux.org/packages/swww) one.

**Comment by Mats357** [comment]
Thanks!
I'll look more into this.  I am missing the ~/Pictures/Wallpapers/ folder structure, so that could likely fix that problem.
