### ISSUE TITLE
New on Linux, how to install when already had a Hyprland 

### ISSUE THREAD

**Issue by CorvusCorax0000** [Aylur/dotfiles#84]
I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.

**Comment by Aylur** [comment]
Will update the readme and write a guide sometime in the near future, as I moved almost everything to nix, its a bit more than just `cp * ~/.config`
but  basically you have to install the dependencies listed and copy the contents of the `ags` directory to `~/.config/ags/`

**Comment by Balssh** [comment]
> I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.

If you still need help I can provide some, as I recently moved to using AGS with Hyprland on Arch.

**Comment by marocainperdu** [comment]
> > I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.
> 
> 
> 
> If you still need help I can provide some, as I recently moved to using AGS with Hyprland on Arch.

That would be appreciated please 🙏🏾

**Comment by Balssh** [comment]
I’m just reinstalling my arch comp with hyprland and ags. If I don’t forget
I’ll post here tomorrow how and what I did.

**Comment by Balssh** [comment]
> > > I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.
> > 
> > 
> > If you still need help I can provide some, as I recently moved to using AGS with Hyprland on Arch.
> 
> That would be appreciated please 🙏🏾

First make sure you have a hyprland config at hand that has the keybinds and setups for ags and also that you have a Nerd Font installed. Then install ags and its dependencies and copy a config to ~/.config/ags (either the one on this repo, or you can check my dotfiles or any other config). Then replace your current Hyprland config with the one you prepared earlier and restart Hyprland. 
Try this and send me a message if it doesn't work.

**Comment by Caraffa-git** [comment]
Hi, I'm also new to Hyprland. I installed everything but after running ags in the console nothing happens, I only get this:
```
(com.github.Aylur.ags:1732): Gjs-WARNING **: 00:03:26.074: JS ERROR: Error: Requiring NM, version none: Typelib file for namespace 'NM' (any version) not found
require@resource:///org/gnome/gjs/modules/esm/gi.js:16:28
@gi://NM:3:25
_init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:266:34


(com.github.Aylur.ags:1732): Gjs-Console-CRITICAL **: 00:03:26.077: cat: /sys/class/thermal/thermal_zone0/temp: No such file or directory
```
I know there is a fix for temp error but I'll do it later.

> First make sure you have a hyprland config at hand that has the keybinds and setups for ags and also that you have a Nerd Font installed.    

@Balssh what do you mean by "setups for ags"?


Also, how do you make ags start automatically?

**Comment by wamunyima3** [comment]
> > I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.
> 
> If you still need help I can provide some, as I recently moved to using AGS with Hyprland on Arch.

Is there a link to the help you gave so that even us can follow through

**Comment by keilmillerjr** [comment]
> > > I'm new on Linux, using Arch. I followed the tutorial and got this Hyprland https://github.com/soldoestech/hyprland. Now I want to install yours but got no idea where to start from. Please help me, thank you.
> > 
> > 
> > If you still need help I can provide some, as I recently moved to using AGS with Hyprland on Arch.
> 
> Is there a link to the help you gave so that even us can follow through

I literally posted exactly how to do it step by step, only one post above yours.

https://github.com/Aylur/dotfiles/issues/84#issuecomment-1964478287

**Comment by keilmillerjr** [comment]
I added `morewaita-git` as optional dependency to aylurs dotfiles. This resolved issues with missing icons such as steam. See (comment)[https://github.com/Aylur/dotfiles/issues/84#issuecomment-1964478287].
