### ISSUE TITLE
Desktop clock is not right:

### ISSUE THREAD

**Issue by xircon** [Aylur/dotfiles#85]
Lenovo Legion 5 laptop:

![image](https://github.com/Aylur/dotfiles/assets/1316691/39a4d131-f8ba-42b4-a3c9-5a7778d66a3d)

Don't know javascript really, have tried to find the reason, but am a bit stumped!

**Comment by Aylur** [comment]
you are on ags v1.4
I use the latest git version for my dotfiles

**Comment by xircon** [comment]
Thanks!
