### ISSUE TITLE
Aylur HW Specs

### ISSUE THREAD

**Issue by AdsonCicilioti** [Aylur/dotfiles#92]
Hi Aylur!

Great work with AGS, I'm going to start testing it, but I'm also interested in your personal config (this repo, right?) and I see that it uses Nvidia and something from Asus.  I would like to know if you use a laptop or desktop, and if you also use a second screen (or more).  Finally, could you put your hardware specifications in readme.md?

Thanks!

**Comment by Aylur** [comment]
Thanks, everything I have configured you can find in this repo, yes. I won't put my hardware info in the readme as it doesn't have to do much with my setup, but here you go
My main and only rig
- os: NixOs
- Asus ROG Strix G15 G513
- AMD Ryzen 7 5800H
- Nvidia 3050TI
- 16GB ram
- some xiaomi monitor as a second screen

**Comment by AdsonCicilioti** [comment]
Maravilha!
Thank you very much and I'm sorry if my proposal was a bit intrusive.
 My curiosity is due to the fact that I also own a (muxless) laptop with Nvidia and I am also using nixOS with hyprland.
 I wanted to make sure I could take full advantage of its configuration.
