### ISSUE TITLE
bring back on demand color change

### ISSUE THREAD

**Issue by umop3plsdn** [Aylur/dotfiles#93]
Any chance on bringing back on demand color change like it used to have when the input box lost focus? I noticed in the latest update it doesn't do it anymore so in order to try out different colors you have to save and reload and try it like that. Also, the Monospaced Font box doesn't open up the popup font picker dialog. Thanks for everything you do!

**Comment by Aylur** [comment]
You can still change the colors in the settings dialog, or through cli, or what do you mean by on demand color change?
The monospaced font is an entry and not a fontbutton, because I couldn't figure out how to not read the size from the button

**Comment by umop3plsdn** [comment]
strange the colors don't change for me anymore in the settings dialog anymore like they used to. I can put anything in there and it stays exactly the same in each one like background color and foreground color

**Comment by umop3plsdn** [comment]
if it's all working as intended it must be something wrong with just my instance of it. I'll try and figure it out. Sorry for creating an issue for it just wasn't working like it did for me before when I updated.
