### ISSUE TITLE
ags outdated

### ISSUE THREAD

**Issue by komprimiert** [Aylur/dotfiles#94]
hi at the start I just wanna say I'm new to linux and I'm sorry but it also seems like a easy problem but I can't fix it 

It said "my config expects 1.5.3 but your ags is 1.5.1" when running "ags"; I also cloned it separately and stuff but it doesn't seem to fix it and I can also see the changes on your project but it doesn't seem to recognize it in the installer

**Comment by Aylur** [comment]
You need to get ags from the main branch. If you are on Arch you need `aylurs-gtk-shell-git`, otherwise you need to build it from source, or use the nix flake.

**Comment by komprimiert** [comment]
> You need to get ags from the main branch. If you are on Arch you need `aylurs-gtk-shell-git`, otherwise you need to build it from source, or use the nix flake.

Ok it worked but now I got the problem as soon as I close the terminal all that the ags command applied will be removed

**Comment by Aylur** [comment]
I assume because you are killing the process. Detach it from the terminal
```bash
ags &
```

**Comment by komprimiert** [comment]
> I assume because you are killing the process. Detach it from the terminal
> 
> ```shell
> ags &
> ```

yeah you're right but in this case I get alot of errors in the terminal which could indicate a general problem so still as soon as I close the terminal it reverts but with ags running it does seem to be working somehow idk
