### ISSUE TITLE
Suggestion: Allow easier implementation of configs without other pkgs such as "bun, obsidian, bottles" etc. (unless there is a config)

### ISSUE THREAD

**Issue by imide** [Aylur/dotfiles#96]
Helps absolute smoothbrains like me to get started with Hyprland, AGS, Nix and more advanced Linux topics as a whole.

**Comment by Aylur** [comment]
I have these listed in `home-manager/packages.nix`. I wouldn't recommend using my nixos or home-manager config though or any other person's config as these are rather *personal*. If you are just starting out, you should rather look for a starter config like https://github.com/Misterio77/nix-starter-configs and then incorporate others into your existing one.

**Comment by imide** [comment]
yeah thats what i mean. since the configs are in nix file its not easily implemented outside of home-manager. or i may just be lazy, stupid, or both. by "config" i mean like the hyprland, ags, gtk themes and such.

**Comment by Aylur** [comment]
Other than my tmux and starship configs, I am not sure what you mean thats behind a nix file.
I use adw-gtk for the gtk heme.
For hyprland I list some bindings in the readme I suggest putting in your config, but the hyprland theme is handled by the ags config.
The ags config you can just copy, its there. Same for my nvim and wezterm configs.
The other stuff I have managed by home-manager doesn't have to do much with the theme.

**Comment by imide** [comment]
oh sorry, i must have gotten confused cause i saw a bunch of hyprland.nix files with what seems like a hyprland config thing. sorry i am fucking stupid

**Comment by Aylur** [comment]
you are correct, I do have my hyprland.conf managed by home-manager, but its just a few window rules, workspace/client navigation keybinds, layout and monitor settings which are unrelated to the theme itself
