### ISSUE TITLE
Overview style or ... edits?

### ISSUE THREAD

**Issue by daUnknownCoder** [Aylur/dotfiles#97]
Tried on both the git and non git versions, config.js and style.css are copypasted from 'https://github.com/Aylur/ags/tree/main/example/simple-bar', and what all i get is:

[Kooha-2023-11-27-22-36-08.webm](https://github.com/Aylur/ags/assets/84800625/e516a189-b5b0-4954-be8b-09711beb920d)

and the css for hyprland workspaces doesnt work, idk whats with the css, none of the rices on reddit work [ even though just copy-pastaing...], and idk whats in the middle coz i cant see it...

**Comment by Aylur** [comment]
moved this issue to my dotfiles, because none of your issues are ags related.

> i m using thorium-browser and i have a few problems

your icon theme doesn't have `Thorium-browser` named icon, you can substitute it to something else in `js/options.js`, you can look up existing icons by running `ags -r "iconBrowser()"` in terminal

same with `audio-card-pci` but for that you need to edit `getAudioTypeIcon` in `js/utils.js`

> mind if i ask you if i can remove this dock type thing

I am not sure if you mean the dock or applauncher by dock type thing, but you can comment out windows in `js/main.js` to exclude them

> and can u tell me how could i run rofi -show drun in the < icon next to the 'wifi' 'bt' 'aud' 'mic' box where the colorpicker is?

find the widget you want to edit, and look it up on the [wiki](https://github.com/Aylur/ags/wiki/Basic-Widgets#button)

> can i use a script where the colorpicker is

yes, [you can run external scripts](https://github.com/Aylur/ags/wiki/utils#running-external-commands)

> calendar thing lil less blurry coz its too messed up?

its not blurred, its fully transparent, if you want to blur it, you can do so with your compositor

**Comment by daUnknownCoder** [comment]
> its not blurred, its fully transparent, if you want to blur it, you can do so with your compositor
i m using Hyprland

> find the widget you want to edit, and look it up on the [wiki](https://github.com/Aylur/ags/wiki/Basic-Widgets#button)
i mean 
![image](https://github.com/Aylur/dotfiles/assets/84800625/5c1b5779-2941-45e2-9f1b-5ebaa0c0665a)
this thing, i dont know where its `js` is or what is the name of it

**Comment by Aylur** [comment]
> this thing

its at `js/bar/buttons/OverviewButton.js`

**Comment by daUnknownCoder** [comment]
> > this thing
> 
> its at `js/bar/buttons/OverviewButton.js`

how to change? i tried 
```js
import Utils from "../../utils.js";
    on_clicked: () => Utils.execAsync("rofi", "-show", "drun"),
```

but its not working...

**Comment by Aylur** [comment]
![image](https://github.com/Aylur/dotfiles/assets/104676705/0e73f972-714a-4853-b68d-7c380d9a4314)

you are passing multiple strings, "-show", and "drun" gets ignored

**Comment by daUnknownCoder** [comment]
> you are passing multiple strings, "-show", and "drun" gets ignored

so possible sollution?

**Comment by daUnknownCoder** [comment]
ok thanks, now help me with this:
![2023-11-30-154411_hyprshot](https://github.com/Aylur/dotfiles/assets/84800625/3c91ad7e-3876-4816-baae-444e001c824f)
![image](https://github.com/Aylur/dotfiles/assets/84800625/22a94265-172d-44b1-a18f-c9dc9208a76f)
what to do with this transparency issue, the bg is too transparent, i m on hyprland using arch, and in the second image, one is a youtube vid i m playing but there's always an another empty one which idk how to remove and in the youtube vid or any player the play/pause and the next ad prev buttons are very close to each other and in the second pic where there is the battery thing, it just has a ⚡, can i have the pattery perc too like "55 % ⚡"? and in the second pic, i have this uptime thing which shows "go sleep" idk why

**Comment by Aylur** [comment]
hyprland layerrules are handled in `js/settings/hyprland.js`, try debugging from there

there is an mpris interface exposed from a software thats faulty, add its bus name to `mpris.black_list` in `js/options.js`
```bash
# prints every mpris available
ags -r "(await import('./service/mpris.js')).default.players.map(p => p.busName)"
```

I can't help with the buttons being too close to each other, I have seen it with other people too, but have no idea what might be the cause

>can i have the pattery perc too like "55 % ⚡"

yes, edit the widget in `js/quicksettings/widgets/Header.js`

**Comment by daUnknownCoder** [comment]
this is the bar right now:
![image](https://github.com/Aylur/dotfiles/assets/84800625/1e6b6335-215f-4ac9-811f-55d794031696)

now i want two things, 
![image](https://github.com/Aylur/dotfiles/assets/84800625/7978fe10-bdc2-4d24-8799-4582846a98fa)
--> in the styling of this button, i increased its width, but it went like this:
![image](https://github.com/Aylur/dotfiles/assets/84800625/d8758efa-8b46-4eda-8f5d-1eb7e740003e)
i mean the icon doesnt come to the center...

this is the overview thing:
![image](https://github.com/Aylur/dotfiles/assets/84800625/92d6abc5-b305-4797-9b53-0c8387305c3e)
when i have 10 workspaces:
![image](https://github.com/Aylur/dotfiles/assets/84800625/0cfcba40-dafe-4847-b7ee-0cbc9ad5b3a5)
so these are only 8 fitting in the screen
this is end-4's dots, for eww: 
![image](https://github.com/Aylur/dotfiles/assets/84800625/f4a66d92-3d8b-4850-af47-e37b48f05b92)
he has it divided into two parts, can we achieve this in ags?

**Comment by Aylur** [comment]
>i mean the icon doesnt come to the center...

`hpack: 'center'` is what you are looking for

>can we achieve this in ags

you can either write some logic to have it split, or just set it to a fixed number with two box under one another

**Comment by daUnknownCoder** [comment]
> `hpack: 'center'` is what you are looking for

Where? In the overview.js or in the css? 

> you can either write some logic to have it split, or just set it to a fixed number with two box under one another

Logic? How do you get the whole overview thing in ur system? Like do u use <10 workspaces or ur screen is large?

**Comment by daUnknownCoder** [comment]
> If you use a dynamic number of workspaces, you could implement some logic that would split it into rows.

i am not using dynamic workpaces 
![image](https://github.com/Aylur/dotfiles/assets/84800625/86ffbe49-e015-4151-a0f4-0db07174588e)

splitting into rows?

**Comment by daUnknownCoder** [comment]
@Aylur, it works now, my approach was changing:
```js
    css: `
            min-width: ${1366 * SCALE}px;
            min-height: ${768 * SCALE}px;
        `,
```
from :
```js
            min-width: ${1920 * SCALE}px;
            min-height: ${1080 * SCALE}px
```
and the result is : 
![image](https://github.com/Aylur/dotfiles/assets/84800625/f1ed1a09-050a-4910-b62a-e8af701d08ce)

idk why the icon for thorium browser doesnt work, like in the options.js:
i did:       ['Thorium-browser', 'Thorium'], // in the title subsititutes
and i tried:       ['Thorium-browser', ''], // in the icon substitutes but it doesnt work, image above...

and yeah the extra music player was `Caprine` idk if its installed or what it is but removing it from the blacklist solved the extra thing

**Comment by Aylur** [comment]
maybe `hexpand: true` too

**Comment by daUnknownCoder** [comment]
> maybe `hexpand: true` too

that works, 
![image](https://github.com/Aylur/dotfiles/assets/84800625/b149f944-8d47-42a3-8290-de6f36c9dcb2)

this thing, i mean the `focusedclient.js` thing can i change the name to its icon? like can i keep it as a fallback that if there's no icon, then name it? like for kitty term, i have an icon so i replaced it and i dont have an icon for the AGS window so can i do that thing?

![image](https://github.com/Aylur/dotfiles/assets/84800625/97308671-0b87-455e-b58e-7164c6b27412)

and i dont have this temperature thing icon and it always stays 27 degs so what to do?

**Comment by Aylur** [comment]
>can i

yes

>i dont have this temperature thing icon

I have it installed with the `gnome-system-monitor` package

>it always stays 27 degs

set the temperature sys path in `options.js`

>it still stays on the current volume and doesnt switch to mute

https://github.com/Aylur/ags/issues/97 
![image](https://github.com/Aylur/dotfiles/assets/104676705/5bb0d38a-9f5b-445e-ab30-35b6c5cdc1fa)

>and this uptime thing stays go sleep

you can edit that in `variables.js`

**Comment by Aylur** [comment]
>how can i?

you'll have to figure that out

>i installed it with no changes, explicitly setting an icon?

your icon pack doesn't fallback to it then, you could specify a full path to the file, but it won't look good

>i tried this code:

I linked you an explanation already, your issue is this line
```js
Audio[type].is_muted = !Audio[type].is_muted;
```
and probably your keybind for `XF86AudioMute`

> i have remove Caprine

leave the empty array `[]` there

> for about.js external link symbolic

your icon theme doesn't have "external-link-symbolic"

**Comment by daUnknownCoder** [comment]
> you'll have to figure that out

If I could I won't have asked... 🙏 🙏 🙏 

> your icon pack doesn't fallback to it then, you could specify a full path to the file, but it won't look good

But I can't go on without an icon, Icon browser have a temperature-symbolic icon so can i use that in anyway? 


> I linked you an explanation already, your issue is this line
> 
> ```js
> Audio[type].is_muted = !Audio[type].is_muted;
> ```

So what should I do for that? Like I tried editing the code according to that issue but it doesn't help much... 

> and probably your keybind for `XF86AudioMute`

That's just a listener it doesn't matter


> leave the empty array `[]` there

Tried that, no mpris controllers were coming afterwards... Like if I remove the block completely, no mpris thing comes, if I keep it in an empty array, there's a $morris-blacklist or something like that error... 

> your icon theme doesn't have "external-link-symbolic"

Again any substitute I could use like I have an icon for link...

Sorry I Was out for a few days so couldnt post...
