### ISSUE TITLE
Screenshot not working

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#98]
Crop screenshot is not saving, and wayshot -f for full screenshot is undefined. ~Video is working, but no stop command was provided..~

EDIT: I saw the stop button in the bar, but still, the shortcut for screen recording isn't working (I should probably try a different one, but I'm sleepy atm).

But the wayshot screenshots are not saved anywhere.

**Comment by blacklightpy** [comment]
Sorry for not adding details, I was tired after trying to getting all of these to work for 2 days.

I'm on Hyprland, on Void Linux x86_64_musl.

Um, so I managed to get screenshots working for now by not using your `recorder.screenshot()` function, and instead using just `wayshot -s` and `wayshot`. But that doesn't save files in the right location and name them.

Currently in my hyprland.conf I have:
```
# screenshot & screenrecord
bind=SUPER SHIFT,R,  exec, ags -r 'recorder.start()'
bind=SUPER,P,        exec, wayshot -s  #ags -r 'recorder.screenshot()'
bind=SUPER SHIFT,P,  exec, wayshot     #ags -r 'recorder.screenshot(true)'
```
The shortcut key XF86Launch4 was working for recorder, but now it isn't working either, so I had to use SUPER SHIFT R. As for why I modified Print, it was because my external keyboard doesn't have that button, and my laptop's placed behind my monitor.

As for why it wasn't working, when I try `wayshot -h`, it doesn't list an option such as `-f`.. so that is listed as undefined. Also, I notice that now `wayshot [-s] [filename.png]` outputs to a file, instead of using `-f`. So maybe how wayshot commands work has changed?

Also I noticed that `wayshot -s` works just like that, but in your `screenrecord.js` you have stored the output of slurp into a separate variable `area` and executed wayshot as `await Utils.execAsync(['wayshot', '-s', area, '-f', file])`.

So maybe this method is outdated? I installed wayshot by adding the `wayshot` script from https://github.com/reinefjord/wayshot to `/usr/local/bin`.

**Comment by nine7nine** [comment]
Just to pipe in - I also noticed today that screenshot is broken. In my case, I'm using flameshot. When i try to take a screenshot it boots me back to GDM / Display Manager.

I rolled back AGS to commit: 3e5daa0bcc654d3afa3a910faba59ac538a1eca2
and rolled back me own dotfiles/shell by a few commits, basically to Aylur's dotfiles here: 97d8677261e357fbab291ee1b0b4e0dcc72b6732

after that, everything works fine again.

**Comment by blacklightpy** [comment]
@nine7nine I see strange javascript commit noises
"async" "promise"

Anyways I'll give it a try too.

But are you using flameshot from Hyprland or by modifying screenrecorder.js?
The former isn't problematic for me.

**Comment by nine7nine** [comment]
@blacklightpy - I'm using flameshot from hyprland as bind.

It's always worked fine that way, I didn't see any real reason to use screenrecorder.js

I also haven't had time to dig in further to see what may be happening (busy working), so I just quickly rolled back a few commits, to avoid any issues while I'm at work.

**Comment by blacklightpy** [comment]
> @blacklightpy - I'm using flameshot from hyprland as bind.

I used screenrecorder.js because I'm new to this, and was just following along with the README. So even though I can make it work, I just thought of opening the PR to see what's the issue with screenrecorder.js.

**Comment by Aylur** [comment]
Everything works for me as expected
ags 1.5.4
wayshot 1.3.0
slurp 1.4.0

**Comment by blacklightpy** [comment]
Looks like I got the wrong wayshot :laughing:

**Comment by blacklightpy** [comment]
Fixed.
