### ISSUE TITLE
About avatar not appearing in Quick Settings

### ISSUE THREAD

**Issue by blacklightpy** [Aylur/dotfiles#99]
Hyprland, Void Linux x86_64_musl. Although I think this is a widget problem.
I tried installing `gvfs` as was mentioned in https://github.com/Aylur/dotfiles/issues/70#issuecomment-1722984396, but it didn't do anything.

**Comment by blacklightpy** [comment]
Apparently there was an about Avatar which was supposed to be there too, and it isn't working either. So it's general for images in widgets.

**Comment by blacklightpy** [comment]
It totally randomly started working again.

**Comment by Aylur** [comment]
you can set the avatar permanently in `js/options.js`

**Comment by blacklightpy** [comment]
I don't know what to configure there.. It seems to look for a file in /var/lib/AccountService/icons/$USER, and another variable sets it as type. I don't use a WM, and don't have an image setup for my user in that folder. How do I proceed?

**Comment by Aylur** [comment]
it is just its default value, you can point it to any file, `/home/${USER}/Pictures/avatar.png` for example

**Comment by blacklightpy** [comment]
I tried copying aylur.jpg to /var/lib/AccountService/icons/${USER}.jpg and restarted ags, but didn't get it working..

**Comment by blacklightpy** [comment]
Also, why is aylur.jpg hardlinked in about.js?

**Comment by Aylur** [comment]
> I wonder what AccountService is really for

used mostly by DEs like KDE and Gnome to store information about a user, like their avatar
If you set your avatar with `gnome-control-center` it will put the image to `/var/lib/AccountService/icons/$USER`

>Also, why is aylur.jpg hardlinked in about.js?

branding basically

**Comment by blacklightpy** [comment]
Working. But I couldn't get AccountService to create an icon. I don't want to try logging out because I have many tabs open.
